### ISSUE TITLE
在家里wifi上不了vpn

### ISSUE THREAD

**Issue by zorro322** [cg3s/forum#100]
## 提交问题请按照格式填写

- 账号：32xxxx952@qq.com

- 操作系统：Mac|iOS

- [x] 是否已更新节点列表 ```(是: 在[]内填 x, 否: 留空) ```

- [x] 是否已查看最新系统公告

- [x] 是否已查看常见问题列表

- [] 是否已搜索已解决问题列表

**本问答为公开页面，为保护我们的服务安全和您的个人隐私，如截图中含有以下敏感信息，请马赛克处理。**
- 本站网址
- 本站节点的任何信息

### 问题描述：
在家里wifi下mac和iphone都上不了vpn，开始几天断断续续可以上，后来就完全不行了。但是手机4g网络模式下可以上vpn。
已经从启过路由器了，还是不行

### 备注：
- [常见问题列表](https://github.com/cg3s/forum/wiki/)
- [已解决问题列表](https://github.com/cg3s/forum/issues?q=is%3Aissue+is%3Aclosed)
- 如想立即得到我们的回复，请在我们的工作时间内提交问题（工作日的10:00-17:00）
- 如需上传截图，对敏感信息马赛克后拖拽或拷贝图片到本编辑器中即可。

**Comment by cg3s** [comment]
什么路由器呢，mac的话切换到全局模式是否ok

**Comment by zorro322** [comment]
路由器是华为的，Wi-Fi上网没问题，全局模式我在试一下。但是应该还是不行记得以前试过

**Comment by cg3s** [comment]
我们今天分别新开了北京和澳大利亚的windows机器，测试都正常，并且youtube可自动刷1080p视频，不知道您的电脑是不是网络环境出现了异常

方便的话，麻烦您装一下向日葵远程软件，然后发一下识别码，我们远程您看看。

**Comment by cg3s** [comment]
另外是否试过所有节点，比如洛杉矶，然后关闭节点均衡，切换节点后重启下ssr看看

**Comment by zorro322** [comment]
特别感谢您积极对我提供帮助，今天突然好用了，但是香港服务器都不行，现在用洛杉矶的可以上

**Comment by cg3s** [comment]
应该的，谢谢反馈，我们将对香港节点进行全面排查

**Comment by zorro322** [comment]
感谢感谢🙏
