### ISSUE TITLE
昨天mac都正常访问，今天就不行了，按照常用问题都检查过，未找到问题，怀疑是mac系统升级的影响，

### ISSUE THREAD

**Issue by ylaoban11** [cg3s/forum#101]
## 提交问题请按照格式填写

- 账号：93949xx48@qq.com

- 操作系统：【Mac】

- [√] 是否已更新节点列表 ```(是: 在[]内填 x, 否: 留空) ```

- [√] 是否已查看最新系统公告

- [√] 是否已查看常见问题列表

- [√] 是否已搜索已解决问题列表

**本问答为公开页面，为保护我们的服务安全和您的个人隐私，如截图中含有以下敏感信息，请马赛克处理。**
- 本站网址
- 本站节点的任何信息

### 问题描述：
一直使用谷歌浏览器，之前能正常使用，第二天就不行了，目前iPhone，win平台正常，唯独macprobook不行（版本10.13.6）1、账户未到期/2、已重新安装软件并配置，更新节点，3、
![image](https://user-images.githubusercontent.com/47581860/52681939-b9206600-2f78-11e9-8746-0c0daaeff54c.png)4、
![image](https://user-images.githubusercontent.com/47581860/52681965-c8071880-2f78-11e9-9b5c-1c7ef2ad7fe9.png)

### 备注：
- [常见问题列表](https://github.com/cg3s/forum/wiki/)
- [已解决问题列表](https://github.com/cg3s/forum/issues?q=is%3Aissue+is%3Aclosed)
- 如想立即得到我们的回复，请在我们的工作时间内提交问题（工作日的10:00-17:00）
- 如需上传截图，对敏感信息马赛克后拖拽或拷贝图片到本编辑器中即可。

**Comment by ylaoban11** [comment]
全局模式也不不行。。

**Comment by cg3s** [comment]
<img width="844" alt="screen shot 2019-02-13 at 10 53 55 am" src="https://user-images.githubusercontent.com/28707826/52683444-cb50d300-2f7d-11e9-98dd-09776576a41e.png">
我这边也升级了，youtube访问正常呢

**Comment by cg3s** [comment]
方便的话，您装个向日葵远程软件，把识别码发上来，我们远程您看看呢

**Comment by ylaoban11** [comment]
194  111   402

**Comment by ylaoban11** [comment]
感谢感谢，，厉害

**Comment by cg3s** [comment]
不客气，刚才忘记这个插件名了，麻烦留一下这个插件名呢，我们好存档

**Comment by cg3s** [comment]
用户出现safari访问正常，chrome访问故障，将chrome切换到访客模式则正常，最终排查为插件导致
后面如有用户出现此类情况，请关闭chrome插件测试。

**Comment by ylaoban11** [comment]
eagle   收集图片的插件

**Comment by cg3s** [comment]
@ylaoban11 ok, 谢谢
