### ISSUE TITLE
请指教

### ISSUE THREAD

**Issue by Justin0345** [cg3s/forum#103]
## 提交问题请按照格式填写

- 账号：(后台可模糊查询，请打码处理，如12345678@qq.com可填写为123xxx78@qq.com)

- 操作系统：[Windows|Mac|Linux|iOS|Android|路由器]

- [] 是否已更新节点列表 ```(是: 在[]内填 x, 否: 留空) ```

- [] 是否已查看最新系统公告

- [] 是否已查看常见问题列表

- [] 是否已搜索已解决问题列表

**本问答为公开页面，为保护我们的服务安全和您的个人隐私，如截图中含有以下敏感信息，请马赛克处理。**
- 本站网址
- 本站节点的任何信息

### 问题描述：
我使用NVIDIA CodeWorks for Android 下载 出现Downloading(error)

官网解释：注意：请注意，如果您使用的是使用代理服务器的公司网络，则下载过程可能会失败。要解决此问题，您可以http_proxy手动设置环境值以使用代理进行下载。
例如，您可以设置http_proxy= [http://10.19.216.147:portnum或http_proxy=](http://10.19.216.147:portnum%E6%88%96http_proxy=) [http://username:password@10.19.216.147:portnum。设置此环境变量后，安装程序将使用代理下载AndroidWorks组件

我想请教，这怎么搞？

### 备注：
- [常见问题列表](https://github.com/cg3s/forum/wiki/)
- [已解决问题列表](https://github.com/cg3s/forum/issues?q=is%3Aissue+is%3Aclosed)
- 如想立即得到我们的回复，请在我们的工作时间内提交问题（工作日的10:00-17:00）
- 如需上传截图，对敏感信息马赛克后拖拽或拷贝图片到本编辑器中即可。

**Comment by cg3s** [comment]
您是开发者？开发者应该很容易解决这个问题

**Comment by Justin0345** [comment]
我是游戏引擎开发，对网络不太熟，请指点一下，谢谢

**Comment by cg3s** [comment]
操作系统是什么，是在终端下载？

**Comment by Justin0345** [comment]
windows10，对，是终端下载

**Comment by cg3s** [comment]
在CMD窗口输入如下指令设置代理：
```
set http_proxy=socks5://127.0.0.1:1080
set https_proxy=socks5://127.0.0.1:1080
set ftp_proxy=socks5://127.0.0.1:1080
```
详细教程：https://segmentfault.com/a/1190000013587465

**Comment by Justin0345** [comment]
可以了谢谢

**Comment by cg3s** [comment]
不客气
