### ISSUE TITLE
我的账号目前无法使用，mac系统，麻烦帮忙看一下，邮箱： 127406354@qq.com

### ISSUE THREAD

**Issue by amo666** [cg3s/forum#104]
## 提交问题请按照格式填写

- 账号：(后台可模糊查询，请打码处理，如12345678@qq.com可填写为123xxx78@qq.com)

- 操作系统：[Windows|Mac|Linux|iOS|Android|路由器]

- [] 是否已更新节点列表 ```(是: 在[]内填 x, 否: 留空) ```

- [] 是否已查看最新系统公告

- [] 是否已查看常见问题列表

- [] 是否已搜索已解决问题列表

**本问答为公开页面，为保护我们的服务安全和您的个人隐私，如截图中含有以下敏感信息，请马赛克处理。**
- 本站网址
- 本站节点的任何信息

### 备注：
- [常见问题列表](https://github.com/cg3s/forum/wiki/)
- [已解决问题列表](https://github.com/cg3s/forum/issues?q=is%3Aissue+is%3Aclosed)
- 如想立即得到我们的回复，请在我们的工作时间内提交问题（工作日的10:00-17:00）
- 如需上传截图，对敏感信息马赛克后拖拽或拷贝图片到本编辑器中即可。

**Comment by cg3s** [comment]
请安装向日葵远程软件 ，然后发识别码

**Comment by amo666** [comment]
是这个哈，1274062354@qq.com

**Comment by cg3s** [comment]
所有节点都试了么，洛杉矶节点是否能用

**Comment by amo666** [comment]
> 所有节点都试了么，洛杉矶节点是否能用

都不行，都试过了

**Comment by cg3s** [comment]
你装个向日葵远程软件，发下识别码

**Comment by amo666** [comment]
739 205 923

**Comment by cg3s** [comment]
https://github.com/cg3s/forum/issues/101
你和这个用户的情况一样，这个eage插件有冲突

**Comment by amo666** [comment]
好的，谢谢啦

**Comment by cg3s** [comment]
不客气

**Comment by cg3s** [comment]
我们刚才测试了下这个插件，在mac上并没有出现和你一样的情况呢

**Comment by amo666** [comment]
啊。。。那我也不清楚了呢，我刚刚试着打开这个插件，依然访问不了，然后我又关掉了就能访问了。不过我朋友用的破解版的这个插件，还是可以访问

**Comment by cg3s** [comment]
暂时不知道具体原因了，你先关掉这个插件使用吧，回头我们多测试测试，找找问题的根源。

**Comment by amo666** [comment]
好的
