### ISSUE TITLE
按教程配置完成并反复检查后，http可以正常访问，https全都访问不了

### ISSUE THREAD

**Issue by wuhuaha** [cg3s/forum#105]
## 提交问题请按照格式填写

- 账号：cn_wangtxx@163.com

- 操作系统：ubuntu

- [] 是否已更新节点列表 ```(是: 在[]内填 x, 否: 留空) ```

- [] 是否已查看最新系统公告

- [] 是否已查看常见问题列表

- [] 是否已搜索已解决问题列表

**本问答为公开页面，为保护我们的服务安全和您的个人隐私，如截图中含有以下敏感信息，请马赛克处理。**
- 本站网址
- 本站节点的任何信息

### 问题描述：
按照教程配置完成后，使用curl进行测试，http可以正常访问谷歌等，但https无法访问了。使用git clone http 没有问题。使用git clone https 报错：
fatal: unable to access 'https://github.com/danielfrg/word2vec.git/': gnutls_handshake() failed: The TLS connection was non-properly terminated.

### 备注：
- [常见问题列表](https://github.com/cg3s/forum/wiki/)
- [已解决问题列表](https://github.com/cg3s/forum/issues?q=is%3Aissue+is%3Aclosed)
- 如想立即得到我们的回复，请在我们的工作时间内提交问题（工作日的10:00-17:00）
- 如需上传截图，对敏感信息马赛克后拖拽或拷贝图片到本编辑器中即可。

**Comment by cg3s** [comment]
这个跟我们的服务没有太大关系，请善用谷歌搜索 gnutls_handshake() failed: The TLS connection was non-properly terminated.

**Comment by wuhuaha** [comment]
可是我在照着教程安装以前，访问https都是正常的啊

**Comment by cg3s** [comment]
浏览器里访问也不行？

**Comment by cg3s** [comment]
ubuntu 哪个版本 16还是18 ,我们这边测一下

**Comment by wuhuaha** [comment]
18

**Comment by wuhuaha** [comment]
Ubuntu 18.04.1 LTS

**Comment by cg3s** [comment]
哦，教程当时测试的版本是16

**Comment by cg3s** [comment]
我们这边测一下18看看是否和你情况一样

**Comment by wuhuaha** [comment]
多谢了，我弄了一下午了没找到解决办法~

**Comment by wuhuaha** [comment]
我把教程里
     export https_proxy="https://127.0.0.1:8123"
改成
      export https_proxy="http://127.0.0.1:8123"
暂时可以了，但是我不知道这样会不会有什么不良影响

**Comment by cg3s** [comment]
哦，你是用git clone htttps吧，这个教程里没有加git的配置，
git config --global http.proxy 127.0.0.1:8123
git config --global https.proxy 127.0.0.1:8123
我加上这段后测试ok

**Comment by cg3s** [comment]
![image](https://user-images.githubusercontent.com/28707826/52845830-0d774180-3143-11e9-91f5-fa668832d96c.png)

**Comment by wuhuaha** [comment]
好的，多谢了

**Comment by cg3s** [comment]
不客气，linux相关的问题，我们默认用户有比较强的动手和思考能力，所以教程一般只是点到为止，具体的请自行思考。

**Comment by cg3s** [comment]
不对，教程里写的
```sh
export http_proxy="http://127.0.0.1:8123"
export https_proxy="https://127.0.0.1:8123"
```
是正确的，只是curl默认访问https的时候没有走代理
curl --proxy http://127.0.0.1:8123 https://www.google.com 
这样访问就ok了
