### ISSUE TITLE
链接数量与实际不符

### ISSUE THREAD

**Issue by lianna-mo** [cg3s/forum#106]
### 问题描述：
介绍了2个公司同事也购买了年费会员，但是大家一起用（各自用各自的付费账号）所有人的链接数量都会变成合计数……然后大家都不能用了……

**Comment by cg3s** [comment]
您的账号是什么

**Comment by lianna-mo** [comment]
656xxx29@qq.com

**Comment by cg3s** [comment]
你们现在刷一下youtube视频呢，我后台看看数据情况

**Comment by cg3s** [comment]
备注：
65xxx29@qq.com
58xxx24@qq.com
kaxxx26@126.com
仅供存档
