### ISSUE TITLE
移动网速异常

### ISSUE THREAD

**Issue by SimonHe96** [cg3s/forum#108]
- 账号：189XXXX95659.163.com

- 操作系统：Windows

- [x] 是否已更新节点列表 

- [x] 是否已查看最新系统公告

- [x] 是否已查看常见问题列表

- [x] 是否已搜索已解决问题列表

### 问题描述：
移动网速异常：
![default](https://user-images.githubusercontent.com/21353272/53551931-4cf75200-3b75-11e9-9e9b-22708f78d52a.png)

**Comment by cg3s** [comment]
这个我们控制不了，完全由测速时候的节点和移动的网络拥堵情况决定，观察窗对于我们来说主要用来观察节点是否被墙，在我们看来只要有速度就说明正常，但不一定决定一整天的网络情况，然后用户的话可以看哪些节点带宽最高，去选用哪个。

**Comment by cg3s** [comment]
![image](https://user-images.githubusercontent.com/28707826/53553146-e889c200-3b77-11e9-84aa-e52744fe91f1.png)
ps：这会的数据显示新加坡日本洛杉矶的带宽正常

**Comment by SimonHe96** [comment]
好的，感谢

**Comment by cg3s** [comment]
不客气，我们已经计划今晚上5个日本节点，到时候可以测试一下移动情况如何

**Comment by SimonHe96** [comment]
已正常。请教一下 SSR右键勾选“服务器负载均衡”，是否可以自动切换节点？

**Comment by cg3s** [comment]
恩，默认会自动的动态使用异常率（综合性能）最低的节点，但勾选的哪个节点不会变。
