### ISSUE TITLE
我的台式电脑最近总是会上不了，但是手机没问题

### ISSUE THREAD

**Issue by behonQ** [cg3s/forum#109]
## 提交问题请按照格式填写

- 账号：249xxxx934@qq.com

- 操作系统：Windows

- [x] 是否已更新节点列表 ```(是: 在[]内填 x, 否: 留空) ```

- [x] 是否已查看最新系统公告

- [x] 是否已查看常见问题列表

- [x] 是否已搜索已解决问题列表

**本问答为公开页面，为保护我们的服务安全和您的个人隐私，如截图中含有以下敏感信息，请马赛克处理。**
- 本站网址
- 本站节点的任何信息

### 备注：
- [常见问题列表](https://github.com/cg3s/forum/wiki/)
- [已解决问题列表](https://github.com/cg3s/forum/issues?q=is%3Aissue+is%3Aclosed)
- 如想立即得到我们的回复，请在我们的工作时间内提交问题（工作日的10:00-17:00）
- 如需上传截图，对敏感信息马赛克后拖拽或拷贝图片到本编辑器中即可。

**Comment by cg3s** [comment]
装个向日葵远程软件，发下识别码过来，我们远程你看下

**Comment by behonQ** [comment]
> 装个向日葵远程软件，然后发下识别码，我们远程你看下

我有team viewer行不行

**Comment by cg3s** [comment]
我们teamviewer没有充钱用不了了，免费试用时间被用尽了

**Comment by behonQ** [comment]
emmm，稍等，我没充钱也可以用其实

**Comment by behonQ** [comment]
237 300 377

**Comment by cg3s** [comment]
你是能用，我们的电脑用不了了

**Comment by behonQ** [comment]
可以操作吗

**Comment by cg3s** [comment]
![image](https://user-images.githubusercontent.com/28707826/53612818-f2aacf80-3c0e-11e9-91ba-f88f996ee5f8.png)
一直这样显示

**Comment by cg3s** [comment]
算了，我用QQ远程你把

**Comment by behonQ** [comment]
是需要正式版吗？向日葵

**Comment by cg3s** [comment]
不需要

**Comment by cg3s** [comment]
elage插件导致，禁用后正常
