### ISSUE TITLE
能不能加一个韩国节点

### ISSUE THREAD

**Issue by keep-slience** [cg3s/forum#110]
## 提交问题请按照格式填写

 账号：64xxxx036@qq.com)

### 问题描述：

有些韩国APP和页面有锁区，能否加一个韩国节点

**Comment by cg3s** [comment]
什么app呢，可以把地址发上来下么，我们好测试

**Comment by keep-slience** [comment]
这是一个韩国游戏预约，地址如下：
https://game.kakao.com/pr/destinychild?rtc=atb_K-GAM02M0019&token=824f2f1d-c19b-4a67-aa89-4e4c95296c17

**Comment by cg3s** [comment]
已添加韩国1号节点，因为vps是包月，对于我们来说不能试用，我们就不去测试了，你测试一下是否能过这个游戏的ip审核吧
