### ISSUE TITLE
新用户注册邮箱收不到验证码

### ISSUE THREAD

**Issue by DodgeV8** [cg3s/forum#113]
## 提交问题请按照格式填写

- 账号：517xxx30@qq.com

- 操作系统：[Windows10]

- [] 是否已更新节点列表 ```(是: 在[]内填 x, 否: 留空) ```

- [x] 是否已查看最新系统公告

- [x] 是否已查看常见问题列表

- [x] 是否已搜索已解决问题列表

**本问答为公开页面，为保护我们的服务安全和您的个人隐私，如截图中含有以下敏感信息，请马赛克处理。**
- 本站网址
- 本站节点的任何信息

### 备注：使用qq和谷歌邮箱均无法接收到验证邮件（已查看垃圾邮件）
- [常见问题列表](https://github.com/cg3s/forum/wiki/)
- [已解决问题列表](https://github.com/cg3s/forum/issues?q=is%3Aissue+is%3Aclosed)
- 如想立即得到我们的回复，请在我们的工作时间内提交问题（工作日的10:00-17:00）
- 如需上传截图，对敏感信息马赛克后拖拽或拷贝图片到本编辑器中即可。

**Comment by cg3s** [comment]
我这边测试邮件发送正常，你再试下看呢？

**Comment by cg3s** [comment]
注册好像是有问题，我们改一下发送邮箱

**Comment by cg3s** [comment]
好了，测试注册验证法发送成功，您再试下

**Comment by DodgeV8** [comment]
ok，已解决，谢谢啦

**Comment by cg3s** [comment]
不客气，也谢谢及时反馈问题

**Comment by EverlastingHopeX** [comment]
借楼，同样问题，gmail和qq都收不到，49xxxxx42@qq.com
