### ISSUE TITLE
APPID账号被锁了，能及时解锁更新吗？在线等 急...

### ISSUE THREAD

**Issue by Joney025** [cg3s/forum#121]
## 提交问题请按照格式填写

- 账号：(后台可模糊查询，请打码处理，如12345678@qq.com可填写为123xxx78@qq.com)

- 操作系统：[Windows|Mac|Linux|iOS|Android|路由器]

- [] 是否已更新节点列表 ```(是: 在[]内填 x, 否: 留空) ```

- [] 是否已查看最新系统公告

- [] 是否已查看常见问题列表

- [] 是否已搜索已解决问题列表

**本问答为公开页面，为保护我们的服务安全和您的个人隐私，如截图中含有以下敏感信息，请马赛克处理。**
- 本站网址
- 本站节点的任何信息

### 备注：
- [常见问题列表](https://github.com/cg3s/forum/wiki/)
- [已解决问题列表](https://github.com/cg3s/forum/issues?q=is%3Aissue+is%3Aclosed)
- 如想立即得到我们的回复，请在我们的工作时间内提交问题（工作日的10:00-17:00）
- 如需上传截图，对敏感信息马赛克后拖拽或拷贝图片到本编辑器中即可。

**Comment by Joney025** [comment]
软件下载：Shadowrocket （国区已被下架，请使用本站加拿大区账户免费下载）
Apple ID: appca@cgsss.net
你们提供的公共账号被锁了，能及时解锁更新吗？急用...

**Comment by cg3s** [comment]
在你提交问题之前我们已经解锁了，现在是可用的

**Comment by Joney025** [comment]
很奇怪，我这边一直登录不了，不知道 这个密码是否正确：CGS.net&*123 （区分大小写）

**Comment by cg3s** [comment]
不正确，请到用户中心查看最新密码

**Comment by cg3s** [comment]
现在已经修复密码刷新的bug了。

**Comment by Joney025** [comment]
好的，问题已解决！谢谢(*^__^*)

**Comment by cg3s** [comment]
不客气，也谢谢您及时提交问题反馈，让我们及时修复bug
