### ISSUE TITLE
我打不开充值页面？？？？

### ISSUE THREAD

**Issue by Justin0345** [cg3s/forum#123]
## 提交问题请按照格式填写

- 账号：(后台可模糊查询，请打码处理，如12345678@qq.com可填写为123xxx78@qq.com)

- 操作系统：[Windows|Mac|Linux|iOS|Android|路由器]

- [] 是否已更新节点列表 ```(是: 在[]内填 x, 否: 留空) ```

- [] 是否已查看最新系统公告

- [] 是否已查看常见问题列表

- [] 是否已搜索已解决问题列表

**本问答为公开页面，为保护我们的服务安全和您的个人隐私，如截图中含有以下敏感信息，请马赛克处理。**
- 本站网址
- 本站节点的任何信息

### 备注：
- [常见问题列表](https://github.com/cg3s/forum/wiki/)
- [已解决问题列表](https://github.com/cg3s/forum/issues?q=is%3Aissue+is%3Aclosed)
- 如想立即得到我们的回复，请在我们的工作时间内提交问题（工作日的10:00-17:00）
- 如需上传截图，对敏感信息马赛克后拖拽或拷贝图片到本编辑器中即可。

**Comment by cg3s** [comment]
我的钱包页面？还是购买卡密的页面？

**Comment by Justin0345** [comment]
还没有修复成功啊，还是进入不了

**Comment by cg3s** [comment]
您是点的用户中心里面的“立即充值”按钮？

**Comment by Justin0345** [comment]
不是啊，商店——》去充值这个按钮
------------------ 原始邮件 ------------------
发件人: "notifications"<notifications@github.com>;
发送时间: 2019年5月7日(星期二) 中午11:31
收件人: "cg3s/forum"<forum@noreply.github.com>;
抄送: "Justin lin"<351316217@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [cg3s/forum] 我打不开充值页面？？？？ (#123)




您是点的用户中心里面的“立即充值”按钮？

**Comment by cg3s** [comment]
现在好了，您刷新一下，那个按钮就是我的钱包页面，之前的url没有更新到最新的url上

**Comment by Justin0345** [comment]
可以了，已充值完成

**Comment by cg3s** [comment]
好的，由于最近我们最近在添加新的主题（过几天会看到），切换了充值页面的url，但现在的主题忘记更新几个按钮的url了，所以出现打不开的问题。
谢谢反馈
