### ISSUE TITLE
gui-config.json文件需要密码

### ISSUE THREAD

**Issue by YuanfeiL** [cg3s/forum#125]
## 提交问题请按照格式填写

- 账号：209xxx17@qq.com
(后台可模糊查询，请打码处理，如12345678@qq.com可填写为123xxx78@qq.com)

- 操作系统：Windows
[Windows|Mac|Linux|iOS|Android|路由器]

- [x] 是否已更新节点列表 ```(是: 在[]内填 x, 否: 留空) ```

- [x] 是否已查看最新系统公告

- [x] 是否已查看常见问题列表

- [x] 是否已搜索已解决问题列表

**本问答为公开页面，为保护我们的服务安全和您的个人隐私，如截图中含有以下敏感信息，请马赛克处理。**
- 本站网址
- 本站节点的任何信息

### 问题描述：

突然无法访问外网，gui-config.json需要输入密码，类型变成After Effects JSON。
重装后不再需要密码，但依旧无法连接。

日志如下：
[2019-05-12 09:47:37] [Info] Disconnect go.microsoft.com:443
[2019-05-12 09:47:37] [Info] Connect raw.githubusercontent.com:443
[2019-05-12 09:47:39] [Info] Disconnect raw.githubusercontent.com:443
[2019-05-12 09:47:39] [Error] connect to update server error

无法访问前的动作：打开Quicktime，打开AE。

### 备注：
- [常见问题列表](https://github.com/cg3s/forum/wiki/)
- [已解决问题列表](https://github.com/cg3s/forum/issues?q=is%3Aissue+is%3Aclosed)
- 如想立即得到我们的回复，请在我们的工作时间内提交问题（工作日的10:00-17:00）
- 如需上传截图，对敏感信息马赛克后拖拽或拷贝图片到本编辑器中即可。

**Comment by cg3s** [comment]
A3节点流量被用完了，已经自动停止使用，请换一个节点，比如香港A4

**Comment by YuanfeiL** [comment]
别的节点页连不上？


![not_only_a3](https://user-images.githubusercontent.com/46511608/57576896-dc867e80-749d-11e9-98ce-f934f3f67db2.png)

**Comment by cg3s** [comment]
切到全局模式呢

**Comment by YuanfeiL** [comment]
> 切到全局模式呢

是用的全局模式，CGWList，绕过局域网和大陆呀

**Comment by cg3s** [comment]
全局模式不需要gui_config.json文件，要不方便的话您装下向日葵远程软件，把机器识别码发上来，我们远程您

**Comment by YuanfeiL** [comment]
> 全局模式不需要gui_config.json文件，要不方便的话您装下向日葵远程软件，把机器识别码发上来，我们远程您

幸苦您帮忙看看吧，543 755 850

**Comment by YuanfeiL** [comment]
> 全局模式不需要gui_config.json文件，要不方便的话您装下向日葵远程软件，把机器识别码发上来，我们远程您

非常感谢！大概多久需要更新一次订阅呢？

**Comment by cg3s** [comment]
下载的应用程序不建议放到C盘的program file里，这个是系统级别的文件夹，需要执行软件的用户使用管理员模式启动，才不会出现有输入密码的情况，一般我们是将ssr放到我的文档里就行或者里自己喜欢的其他非管理员权限的目录

**Comment by cg3s** [comment]
您的订阅更新有问题，我们暂时不知道为什么（订阅更新是每次电脑开机后 会自动更新节点列表的）

**Comment by YuanfeiL** [comment]
总之感谢！

**Comment by cg3s** [comment]
不客气，哦，刚才说错了，我以为是pac文件
