### ISSUE TITLE
为什么显示端口被占用

### ISSUE THREAD

**Issue by fan19291300** [cg3s/forum#126]

**Comment by fan19291300** [comment]
而且  也没有帮助文档说的高级设置啊

**Comment by fan19291300** [comment]
一直是这个问题 好久了   家里电脑就没关系

**Comment by fan19291300** [comment]
有人嘛？

**Comment by fan19291300** [comment]
大佬们？

**Comment by fan19291300** [comment]
现在设置了   没有显示端口占用的   但是 连不上外网

**Comment by cg3s** [comment]
那就是全局设置里，改一下代理端口就行

**Comment by cg3s** [comment]
您的账户是什么？
首先，请确保节点配置为最新，
然后不行就重新按照教程走一遍

**Comment by fan19291300** [comment]
我都是重新走流程的   从下载软件开始的账户：1726348052@qq.com

**Comment by fan19291300** [comment]
现在  1.‘’更新ssr服务订阅（不通过代理）‘’ 没问题，2.在选项设置里勾选允许来自局域网的连接，本地端口1080给成1085 解决了端口占用的问题。现在是：PAC / 更新PAC为GFWList   错误，显示 ：‘’Failed to update PAC file  操作过程中出现异常，结果无效。有关异常的详细信息，请查看InnerException’’ 啊啊啊 死活连不上外网

**Comment by cg3s** [comment]
不用pac模式，选全局模式加绕过大陆和局域网组合
另外后面我们更新了软件，理论上不应该出现更新pac有错误的情况了

**Comment by cg3s** [comment]
给用户远程一切正常
