### ISSUE TITLE
谷歌频繁出现验证码，已关负载均衡

### ISSUE THREAD

**Issue by seejudge** [cg3s/forum#128]
## 提交问题请按照格式填写

- 账号：(后台可模糊查询，请打码处理，如12345678@qq.com可填写为123xxx78@qq.com)

- 操作系统：[Windows|Mac|Linux|iOS|Android|路由器]

- [] 是否已更新节点列表 ```(是: 在[]内填 x, 否: 留空) ```

- [] 是否已查看最新系统公告

- [] 是否已查看常见问题列表

- [] 是否已搜索已解决问题列表

**本问答为公开页面，为保护我们的服务安全和您的个人隐私，如截图中含有以下敏感信息，请马赛克处理。**
- 本站网址
- 本站节点的任何信息

### 备注：
- [常见问题列表](https://github.com/cg3s/forum/wiki/)
- [已解决问题列表](https://github.com/cg3s/forum/issues?q=is%3Aissue+is%3Aclosed)
- 如想立即得到我们的回复，请在我们的工作时间内提交问题（工作日的10:00-17:00），大多数时候我们能保持快速响应，但不排除我们的工作人员在忙其他的事情，如果我们没有及时回应，请耐心等待。
- 如需上传截图，对敏感信息马赛克后拖拽或拷贝图片到本编辑器中即可。

**Comment by cg3s** [comment]
关掉负载均衡后，理论上不应该出现ip频繁变化。

**Comment by seejudge** [comment]
<img width="1060" alt="捕获" src="https://user-images.githubusercontent.com/50795880/57981192-34f1e900-7a67-11e9-9d76-9d6bbfa3c15b.PNG">

**Comment by seejudge** [comment]
<img width="856" alt="捕获" src="https://user-images.githubusercontent.com/50795880/57981217-91550880-7a67-11e9-9b6f-40753f8d2002.PNG">

**Comment by cg3s** [comment]
不能看这里，你得用google查
https://www.google.com/search?newwindow=1&safe=active&source=hp&ei=6zXhXMPLA8qC-QbAsJKQDQ&q=my+ip&oq=my+ip&gs_l=psy-ab.12..35i39l2j0i131j0l7.1114.2044..2350...0.0..0.261.1437.0j2j5......0....1..gws-wiz.....0..0i67j0i10.138gnxtGQqQ

**Comment by seejudge** [comment]
好的，谢谢，我再试一下

**Comment by cg3s** [comment]
如果谷歌查的ip还是频繁变动，您可以装下向日葵远程软件，把识别码这里

**Comment by seejudge** [comment]
问题已经处理好了，是谷歌的二次验证，谷歌邮件关闭浏览器之后再次登陆要求手机验证。  不是ip变动导致的（ps. 自己查IP的方法不对）， 多谢
