### ISSUE TITLE
什么网站都可以上，唯独脸书上不去。所有浏览器都试过，电脑重启过，

### ISSUE THREAD

**Issue by cgdvs** [cg3s/forum#132]
## 提交问题请按照格式填写

- 账号：(后台可模糊查询，请打码处理，如12345678@qq.com可填写为123xxx78@qq.com)

- 操作系统：[Windows|Mac|Linux|iOS|Android|路由器]

- [] 是否已更新节点列表 ```(是: 在[]内填 x, 否: 留空) ```

- [] 是否已查看最新系统公告

- [] 是否已查看常见问题列表

- [] 是否已搜索已解决问题列表

**本问答为公开页面，为保护我们的服务安全和您的个人隐私，如截图中含有以下敏感信息，请马赛克处理。**
- 本站网址
- 本站节点的任何信息

### 备注：
- [常见问题列表](https://github.com/cg3s/forum/wiki/)
- [已解决问题列表](https://github.com/cg3s/forum/issues?q=is%3Aissue+is%3Aclosed)
- 如想立即得到我们的回复，请在我们的工作时间内提交问题（工作日的10:00-17:00），大多数时候我们能保持快速响应，但不排除我们的工作人员在忙其他的事情，如果我们没有及时回应，请耐心等待。
- 如需上传截图，对敏感信息马赛克后拖拽或拷贝图片到本编辑器中即可。

**Comment by cg3s** [comment]
这个跟我们的节点关系不大，您可以试下chrome的访客模式，看看是不是有什么插件冲突了。

**Comment by SimonHe96** [comment]
@cg3s 同题主的问题：
https://www.youtube.com/，https://www.facebook.com/ 都不能上。
https://music.youtube.com/ 可以上。

**Comment by cg3s** [comment]
模式：全局模式，代理规则：全局也这样？
我们这边测试没这个情况

**Comment by SimonHe96** [comment]
可以了，修改为：
模式：全局模式，代理规则：全局 

我之前是：
模式：PAC，代理规则：绕过局域网和大陆

**Comment by cg3s** [comment]
那你改成 模式：全局，代理规则：绕过局域网和大陆。
两个都全局，国内网站也会走代理。

**Comment by SimonHe96** [comment]
已改成：
模式：全局，代理规则：绕过局域网和大陆


又不能上了

**Comment by SimonHe96** [comment]
很奇怪，改成：
模式：全局模式，代理规则：全局
可以上。

再改回：
模式：PAC，代理规则：绕过局域网和大陆
也可以上。

**Comment by cg3s** [comment]
pac模式下，代理规则是不起作用的
代理规则只在模式改为全局的情况下才有用
你更新下pac呢

**Comment by cg3s** [comment]
可能跟dns有关系，你把系统的dns改成谷歌的 8.8.8.8和8.8.4.4试试

**Comment by cg3s** [comment]
另外如果您用的版本从GFWList更新pac报错，请重新下载软件再更新。

**Comment by SimonHe96** [comment]
1.模式：PAC，代理规则：绕过局域网和大陆
从GFWList更新PAC成功，但youtube不能上。

DNS改为8.8.8.8和8.8.4.4，youtube不能上。

chrome，切到访客模式。youtube不能上。

2.模式：全局模式，代理规则：全局
可以上。

**Comment by SimonHe96** [comment]
要不远程我吧，teamviewer

1 262 831 567
vkq793

**Comment by cg3s** [comment]
teamviewer我们没有购买商业授权，已经超过使用限制了，您可以装个向日葵远程，发个识别码过来，另外你最好单独提交一个issue，不然这个issue的动态会邮件到发起者。

**Comment by SimonHe96** [comment]
哦哦好的

**Comment by cg3s** [comment]
原因可能为公司wifi的dns解析异常，[参考 #136 ](#136 )
