### ISSUE TITLE
能否看Netflix ，是不是跟节点有关？？

### ISSUE THREAD

**Issue by seejudge** [cg3s/forum#133]
## 提交问题请按照格式填写

- 账号：(后台可模糊查询，请打码处理，如12345678@qq.com可填写为123xxx78@qq.com)

- 操作系统：[Windows|Mac|Linux|iOS|Android|路由器]

- [] 是否已更新节点列表 ```(是: 在[]内填 x, 否: 留空) ```

- [] 是否已查看最新系统公告

- [] 是否已查看常见问题列表

- [] 是否已搜索已解决问题列表

**本问答为公开页面，为保护我们的服务安全和您的个人隐私，如截图中含有以下敏感信息，请马赛克处理。**
- 本站网址
- 本站节点的任何信息

### 备注：
- [常见问题列表](https://github.com/cg3s/forum/wiki/)
- [已解决问题列表](https://github.com/cg3s/forum/issues?q=is%3Aissue+is%3Aclosed)
- 如想立即得到我们的回复，请在我们的工作时间内提交问题（工作日的10:00-17:00）
- 如需上传截图，对敏感信息马赛克后拖拽或拷贝图片到本编辑器中即可。

**Comment by cg3s** [comment]
跟节点落地IP是否原生相关，目前洛杉矶C2节点支持美区netflix，港区暂无

**Comment by seejudge** [comment]
没有找到C2节点，已经重新下载软件重新配置过了，仍然只有新加坡香港日本的B类节点

**Comment by cg3s** [comment]
目前，我们还没有全面支持netflix，您所在的用户组是B组，所以看不到C组节点。需要的话我们可以给您转到C组，不过我估计您的netflix账户应该是港区吧。

**Comment by seejudge** [comment]
<img width="43" alt="ki" src="https://user-images.githubusercontent.com/50795880/59077903-292f6f00-890f-11e9-9420-07abaaf6471b.png">

**Comment by seejudge** [comment]
麻烦转到C组

**Comment by cg3s** [comment]
您账户是什么

**Comment by seejudge** [comment]
23975**757@qq.com，这样可以么

**Comment by cg3s** [comment]
已转，更新节点列表后用洛杉矶C2测试美区是否ok

**Comment by seejudge** [comment]
好的，多谢了

**Comment by cg3s** [comment]
不客气，您先测试下行不行

**Comment by seejudge** [comment]
<img width="650" alt="ki" src="https://user-images.githubusercontent.com/50795880/59078780-2afb3180-8913-11e9-94ab-e109802d01bb.png">
<img width="643" alt="kil" src="https://user-images.githubusercontent.com/50795880/59078785-3189a900-8913-11e9-832c-76ffe72a9525.png">

**Comment by seejudge** [comment]
用的是C2节点，负载均衡也关掉了

**Comment by cg3s** [comment]
那还是有问题，我们稍后更新下ip配置

**Comment by cg3s** [comment]
刚看了下，之前挂的流媒体dns失效了，我们稍后上线一个支持netflix的港区节点

**Comment by seejudge** [comment]
好的，上线之后在网站的公告里可以看到相关信息么，谢谢

**Comment by cg3s** [comment]
刚升级了下服务，洛杉矶C2我们测试可以看了，您测试下。

**Comment by cg3s** [comment]
目前洛杉矶C2对奈飞的支持仅为小部分测试阶段，暂时不在公告发布，需要的用户我们才提供相应技术支持。

**Comment by seejudge** [comment]
试了下，可以正常观看奈飞了，多谢。

**Comment by cg3s** [comment]
不客气
