### ISSUE TITLE
360被卸载了，审计记录里还有“屏蔽360”。这很奇怪。网页主页不是360的，进程里没有360相关的进程。哪来的？

### ISSUE THREAD

**Issue by cgdvs** [cg3s/forum#134]
## 提交问题请按照格式填写

- 账号：(后台可模糊查询，请打码处理，如12345678@qq.com可填写为123xxx78@qq.com)

- 操作系统：[Windows|Mac|Linux|iOS|Android|路由器]

- [] 是否已更新节点列表 ```(是: 在[]内填 x, 否: 留空) ```

- [] 是否已查看最新系统公告

- [] 是否已查看常见问题列表

- [] 是否已搜索已解决问题列表

**本问答为公开页面，为保护我们的服务安全和您的个人隐私，如截图中含有以下敏感信息，请马赛克处理。**
- 本站网址
- 本站节点的任何信息

### 备注：
- [常见问题列表](https://github.com/cg3s/forum/wiki/)
- [已解决问题列表](https://github.com/cg3s/forum/issues?q=is%3Aissue+is%3Aclosed)
- 如想立即得到我们的回复，请在我们的工作时间内提交问题（工作日的10:00-17:00），大多数时候我们能保持快速响应，但不排除我们的工作人员在忙其他的事情，如果我们没有及时回应，请耐心等待。
- 如需上传截图，对敏感信息马赛克后拖拽或拷贝图片到本编辑器中即可。

**Comment by cgdvs** [comment]
不知道从哪里找起。真的是蛋疼。

**Comment by cgdvs** [comment]
360被删掉好几天了。却一直有记录“屏蔽360”

**Comment by cg3s** [comment]
https://github.com/cg3s/forum/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E5%88%97%E8%A1%A8#14-%E5%B7%B2%E7%BB%8F%E5%8D%B8%E8%BD%BD%E4%BA%86360%E7%9B%B8%E5%85%B3%E8%BD%AF%E4%BB%B6%E8%B4%A6%E6%88%B7%E4%BE%9D%E7%84%B6%E8%A2%AB%E7%A6%81%E7%94%A8
