### ISSUE TITLE
google正常用，youtube、facebook不能上。

### ISSUE THREAD

**Issue by SimonHe96** [cg3s/forum#136]
- 账号：189XXXX95659.163.com

- 操作系统：Windows

- [x] 是否已更新节点列表 

- [x] 是否已查看最新系统公告

- [x] 是否已查看常见问题列表

- [x] 是否已搜索已解决问题列表

### 问题描述：
google正常用，目前发现youtube、facebook不能上。

**Comment by SimonHe96** [comment]
698 879 725

**Comment by SimonHe96** [comment]
583 749 970

**Comment by cg3s** [comment]
建议先用以下几种方式做排除，
1 在公司同事电脑上测试，
2 系统新建账户测试
或者
在连了wifi的手机上测试，但这个系统环境不一样，只能排除是否是公司网络问题

看看哪种方式正常

**Comment by SimonHe96** [comment]
嗯嗯试了，公司网络有问题，非常感谢。

手机连了公司wifi，不能上youtube。
手机使用4G，可以上youtube。

**Comment by cg3s** [comment]
恩，估计是公司dns设置问题，把youtube facebook解析成国内ip了，就只能全局模式才能访问。
不客气，谢谢反馈
