### ISSUE TITLE
负载均衡能以超时为准么？

### ISSUE THREAD

**Issue by xtvjxk123456** [cg3s/forum#137]
## 提交问题请按照格式填写

- 账号：xxxxxx123456maya@163.com

- 操作系统：[Windows]

- [x] 是否已更新节点列表 

- [x] 是否已查看最新系统公告

- [x] 是否已查看常见问题列表

- [x] 是否已搜索已解决问题列表

### 问题描述：
最近超时超的有些厉害，负责均衡能以超时次数为准么？

**Comment by cg3s** [comment]
你是用的电信联通还是移动？
超时严重都是哪些节点呢？
负载均衡可在选项设置里设置，如下图
![image](https://user-images.githubusercontent.com/28707826/59562773-57c1ee00-9063-11e9-88fb-532c7f7071b2.png)

**Comment by xtvjxk123456** [comment]
电信，北京的,好几个节点都会超时，会不会是我这边本身线路就本稳定?

**Comment by cg3s** [comment]
具体是哪几个节点？

**Comment by xtvjxk123456** [comment]
我常用的是香港那几个,其中用的最多的是3和4

**Comment by cg3s** [comment]
是最近几天才出现么，是白天还是晚上，是否有时段区别
这个月因为一些敏感事件，我们暂时不好确定是否为线路问题

**Comment by xtvjxk123456** [comment]
好的，我试试再说

**Comment by cg3s** [comment]
ok, 另外您之前提交的申购记录因为没多少人参与，我们就给取消了，您可以再点下取消，就可以退回积分了。
