### ISSUE TITLE
app无法更新了

### ISSUE THREAD

**Issue by yongqing-wei** [cg3s/forum#138]
## 提交问题请按照格式填写
咱们的id被封了，18号晚上还是不能更新，你们需要解封账号。。
- 账号：(后台可模糊查询，请打码处理，如12345678@qq.com可填写为123xxx78@qq.com)

- 操作系统：[Windows|Mac|Linux|iOS|Android|路由器]

- [] 是否已更新节点列表 ```(是: 在[]内填 x, 否: 留空) ```

- [] 是否已查看最新系统公告

- [] 是否已查看常见问题列表

- [] 是否已搜索已解决问题列表

**本问答为公开页面，为保护我们的服务安全和您的个人隐私，如截图中含有以下敏感信息，请马赛克处理。**
- 本站网址
- 本站节点的任何信息

### 备注：
- [常见问题列表](https://github.com/cg3s/forum/wiki/)
- [已解决问题列表](https://github.com/cg3s/forum/issues?q=is%3Aissue+is%3Aclosed)
- 如想立即得到我们的回复，请在我们的工作时间内提交问题（工作日的10:00-17:00）
- 如需上传截图，对敏感信息马赛克后拖拽或拷贝图片到本编辑器中即可。

**Comment by cg3s** [comment]
我们故意不解封的，使用页面有最新的账户密码，详细说明可查看最新公告。

**Comment by yongqing-wei** [comment]
我用的是最新的账户和密码。。Apple ID: appca@cgsss.com 
密      码: CGS.com!@123（为避免滥用，会不定期更改）
就这个  登进去密码显示账户需要解封！

发送自 Windows 10 版邮件应用

发件人: CGS小管家
发送时间: 2019年6月19日 9:42
收件人: cg3s/forum
抄送: yongqing-wei; Author
主题: Re: [cg3s/forum] app无法更新了 (#138)

我们故意不解封的，使用页面有最新的账户密码，详细说明可查看最新公告。

**Comment by cg3s** [comment]
这个账户没有被锁定，您当前登录的应该还是appca@cgsss.net这个账户，更新的话还需要用原来的账户，我们马上对.net的账户进行解锁，然后把原来的账户密码同步到网站上。

**Comment by yongqing-wei** [comment]
好的  ，我都不知道哪个是哪个账户了， 只要能更新就行啊

发送自 Windows 10 版邮件应用

发件人: CGS小管家
发送时间: 2019年6月19日 9:49
收件人: cg3s/forum
抄送: yongqing-wei; Author
主题: Re: [cg3s/forum] app无法更新了 (#138)

这个账户没有被锁定，您当前登录的应该还是appca@cgsss.net这个账户，更新的话还需要用原来的账户，我们马上对.net的账户进行解锁，然后把原来的账户密码同步到网站上。

**Comment by cg3s** [comment]
因为账户经常被人拿来作为个人长期使用，我们为了避免滥用，就才去多个账户切换着用了，但这个会对用户更新软件造成影响，所以我们会提供多个账户。

您用这个账户：
appca@cgsss.net
CGS.net!)123

**Comment by yongqing-wei** [comment]
好的 明白。我先去更新。

发送自 Windows 10 版邮件应用

发件人: CGS小管家
发送时间: 2019年6月19日 9:52
收件人: cg3s/forum
抄送: yongqing-wei; Author
主题: Re: [cg3s/forum] app无法更新了 (#138)

因为账户经常被人拿来作为个人长期使用，我们为了避免滥用，就才去多个账户切换着用了，但这个会对用户更新软件造成影响，所以我们会提供多个账户。
您用这个账户：
appca@cgsss.net
CGS.net!)123

**Comment by cg3s** [comment]
另外你最好不要用邮箱来频繁回复这个问答，不然您的github账户可能会被封（之前有用户出现该情况）

**Comment by yongqing-wei** [comment]
好的 好的  非常感谢！！

**Comment by cg3s** [comment]
不客气
