### ISSUE TITLE
本站VPN笔记本电脑为什么不能用？笔记本用是不是要设置下。

### ISSUE THREAD

**Issue by addie-zhang** [cg3s/forum#139]
## 提交问题请按照格式填写

- 账号：(后台可模糊查询，请打码处理，如12345678@qq.com可填写为123xxx78@qq.com)

- 操作系统：[Windows|Mac|Linux|iOS|Android|路由器]

- [] 是否已更新节点列表 ```(是: 在[]内填 x, 否: 留空) ```

- [] 是否已查看最新系统公告

- [] 是否已查看常见问题列表

- [] 是否已搜索已解决问题列表

**本问答为公开页面，为保护我们的服务安全和您的个人隐私，如截图中含有以下敏感信息，请马赛克处理。**
- 本站网址
- 本站节点的任何信息

### 备注：
- [常见问题列表](https://github.com/cg3s/forum/wiki/)
- [已解决问题列表](https://github.com/cg3s/forum/issues?q=is%3Aissue+is%3Aclosed)
- 如想立即得到我们的回复，请在我们的工作时间内提交问题（工作日的10:00-17:00），大多数时候我们能保持快速响应，但不排除我们的工作人员在忙其他的事情，如果我们没有及时回应，请耐心等待。
- 如需上传截图，对敏感信息马赛克后拖拽或拷贝图片到本编辑器中即可。

**Comment by cg3s** [comment]
笔记本是什么系统呢？理论上按照我们的教程来就行，与是不是笔记本电脑没关系，我们的用户中有大部分人都用笔记本电脑。

**Comment by addie-zhang** [comment]
苹果笔记本，系统是win，我下载了按照教程安装不能用。不知道怎么回事，你这边有没有笔记本设置我看下。


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: CGS小管家 <notifications@github.com>
发送时间: 2019年6月24日 22:28
收件人: cg3s/forum <forum@noreply.github.com>
抄送: addie-zhang <309324996@qq.com>, Author <author@noreply.github.com>
主题: 回复：[cg3s/forum] 本站VPN笔记本电脑为什么不能用？笔记本用是不是要设置下。 (#139)




笔记本是什么系统呢？理论上按照我们的教程来就行，与是不是笔记本电脑没关系，我们的用户中有大部分人都用笔记本电脑。

**Comment by cg3s** [comment]
方便的话，您可以装下向日葵远程软件，启动后把机器识别码发上来，我们远程您看看

**Comment by addie-zhang** [comment]
今天我账号登录不上了




------------------ 原始邮件 ------------------
发件人: "CGS小管家"<notifications@github.com>;
发送时间: 2019年6月27日(星期四) 上午10:23
收件人: "cg3s/forum"<forum@noreply.github.com>;
抄送: "精灵鼠"<309324996@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [cg3s/forum] 本站VPN笔记本电脑为什么不能用？笔记本用是不是要设置下。 (#139)




Closed #139.
