### ISSUE TITLE
Netflix 香港A4节点 看不了 提示似乎在使用解锁器或者 Proxy。请关闭服务后，再试一次

### ISSUE THREAD

**Issue by yutingdd** [cg3s/forum#140]
## 提交问题请按照格式填写

- 账号：11274xxxx4@qq.com

- 操作系统：Windows

- [是] 是否已更新节点列表 ```(是: 在[]内填 x, 否: 留空) ```

- [是] 是否已查看最新系统公告

- [是] 是否已查看常见问题列表

- [是] 是否已搜索已解决问题列表

**本问答为公开页面，为保护我们的服务安全和您的个人隐私，如截图中含有以下敏感信息，请马赛克处理。**
- 本站网址
- 本站节点的任何信息

### 问题描述：
网飞 香港A4 看不了 提示似乎使用解锁器或proxy

### 备注：
- [常见问题列表](https://github.com/cg3s/forum/wiki/)
- [已解决问题列表](https://github.com/cg3s/forum/issues?q=is%3Aissue+is%3Aclosed)
- 如想立即得到我们的回复，请在我们的工作时间内提交问题（工作日的10:00-17:00），大多数时候我们能保持快速响应，但不排除我们的工作人员在忙其他的事情，如果我们没有及时回应，请耐心等待。
- 如需上传截图，对敏感信息马赛克后拖拽或拷贝图片到本编辑器中即可。

**Comment by cg3s** [comment]
由于服务商解析的dns ip有调整,我们没有及时更新系统设置,导致netflix解析无效,现已恢复,谢谢反馈.
