### ISSUE TITLE
关于充值时间的问题

### ISSUE THREAD

**Issue by hrnun** [cg3s/forum#142]
## 提交问题请按照格式填写

- 账号：hrnunXX@126.com

- 操作系统：Mac book pro

- [x] 是否已更新节点列表 ```(是: 在[ x]内填 x, 否: 留空) ```

- [x] 是否已查看最新系统公告

- [x] 是否已查看常见问题列表

- [x] 是否已搜索已解决问题列表

**本问答为公开页面，为保护我们的服务安全和您的个人隐私，如截图中含有以下敏感信息，请马赛克处理。**
- 本站网址
- 本站节点的任何信息

### 问题描述：
季度会员，本来是7月17日到期，今天充值了一个季度，但时间变为10月1，而不是10月16，
提前充值不会顺延时间而是覆盖原本时间吗？求问，希望可以往后顺延时间呀
（不然提早充值图个啥，还吃掉了17天……）谢谢！

### 备注：
- [常见问题列表](https://github.com/cg3s/forum/wiki/)
- [已解决问题列表](https://github.com/cg3s/forum/issues?q=is%3Aissue+is%3Aclosed)
- 如想立即得到我们的回复，请在我们的工作时间内提交问题（工作日的10:00-17:00）
- 如需上传截图，对敏感信息马赛克后拖拽或拷贝图片到本编辑器中即可。

**Comment by cg3s** [comment]
好的，我们看下，可能是因为昨天调整了商品配置，导致时间计算出现了问题

**Comment by cg3s** [comment]
已修复，谢谢反馈，你账户的时间已经补上了

**Comment by hrnun** [comment]
感谢！赞效率！
