### ISSUE TITLE
Netflix香港B4节点看不了

### ISSUE THREAD

**Issue by 18919329161** [cg3s/forum#145]
- 账号：alexxx12@qq.com
- 操作系统：[Windows]

- [是] 是否已更新节点列表 ```(是: 在[]内填 x, 否: 留空) ```

- [是] 是否已查看最新系统公告

- [是] 是否已查看常见问题列表

- [是] 是否已搜索已解决问题列表

### 问题描述：
如题所示，更新了节点，打开还是proxy串流错误。

### 备注：
- [常见问题列表](https://github.com/cg3s/forum/wiki/)
- [已解决问题列表](https://github.com/cg3s/forum/issues?q=is%3Aissue+is%3Aclosed)
- 如想立即得到我们的回复，请在我们的工作时间内提交问题（工作日的10:00-17:00），大多数时候我们能保持快速响应，但不排除我们的工作人员在忙其他的事情，如果我们没有及时回应，请耐心等待。
- 如需上传截图，对敏感信息马赛克后拖拽或拷贝图片到本编辑器中即可。

**Comment by cg3s** [comment]
已修复，您试试看呢
