### ISSUE TITLE
支付宝付款成功，银通却提示未付款？

### ISSUE THREAD

**Issue by qq150593** [cg3s/forum#147]
## 提交问题请按照格式填写

- 账号：15059***05@qq.com

- 操作系统：[Windows]

- [] 是否已更新节点列表 ``` ```

- [] 是否已查看最新系统公告

- [] 是否已查看常见问题列表

- [] 是否已搜索已解决问题列表

**本问答为公开页面，为保护我们的服务安全和您的个人隐私，如截图中含有以下敏感信息，请马赛克处理。**
- 本站网址
- 本站节点的任何信息

### 问题描述：
支付宝付款成功，银通却提示未付款？

### 备注：我的图片无法载入进来，拖进来就把网页最大化了，公司电脑，浏览器版本较低。我有telegram，要看图片可以发你。
- [常见问题列表](https://github.com/cg3s/forum/wiki/)
- [已解决问题列表](https://github.com/cg3s/forum/issues?q=is%3Aissue+is%3Aclosed)
- 如想立即得到我们的回复，请在我们的工作时间内提交问题（工作日的10:00-17:00），大多数时候我们能保持快速响应，但不排除我们的工作人员在忙其他的事情，如果我们没有及时回应，请耐心等待。
- 如需上传截图，对敏感信息马赛克后拖拽或拷贝图片到本编辑器中即可。

**Comment by cg3s** [comment]
你填的联系方式是什么

**Comment by qq150593** [comment]
我填的是我的邮箱，15059***05@qq.com

**Comment by cg3s** [comment]
http://www.ka40.com/Order/Query 这里查到的的确是未支付呢
你可以压缩一下图片发上来么。

**Comment by qq150593** [comment]
我发不了图片

**Comment by cg3s** [comment]
那你发到邮箱 service@cgsss.net 吧

**Comment by qq150593** [comment]
你给个别的什么联系方式都行，邮箱或者别的

**Comment by qq150593** [comment]
好的

**Comment by qq150593** [comment]
发了，收到了吗？

**Comment by cg3s** [comment]
收到了

**Comment by qq150593** [comment]
知道这是什么情况么？

**Comment by cg3s** [comment]
![image](https://user-images.githubusercontent.com/28707826/60787069-300a0580-a18b-11e9-9cd0-5372fed98537.png)
你重新下个订单吧，这个他们说过两天会退款给你

**Comment by qq150593** [comment]
那行，是不是不能用花呗支付？

**Comment by cg3s** [comment]
我这边刚才用花呗测试正常呢，你这个情况我们也是第一次遇到，之前从没有过，放心哈，银通网我们已经挂了几年了，每次故障他们都会积极解决。

本来我们是打算直接先给你卡密，但他们是退款给你的话，感觉你可以再下个订单就行，过两天要是没退款的话，你再到这里找我们就行。

你就按正常的步骤来就行，应该是他们的系统刚才出了一点点故障。

**Comment by qq150593** [comment]
行，那我从新下单

**Comment by cg3s** [comment]
好的，谢谢理解

**Comment by cg3s** [comment]
你购买套餐后我们给你加10天有效期吧

**Comment by qq150593** [comment]
谢谢大佬~

**Comment by cg3s** [comment]
不客气的，退款后请记得在这里回应一下。

**Comment by cg3s** [comment]
请问收到退款了么

**Comment by qq150593** [comment]
还没有，本来想昨天联系你的，但昨天是第二天，想着等第二天过去在联系你。

**Comment by cg3s** [comment]
好的，我们再跟银通网联系一下

**Comment by qq150593** [comment]
嗯嗯，谢谢

**Comment by cg3s** [comment]
不客气的，可能要晚点回复你哦

**Comment by qq150593** [comment]
嗯嗯

**Comment by cg3s** [comment]
他们财务说没办法原路退回，今天下午先转给我们，我们再转给你哈。

**Comment by qq150593** [comment]
行，麻烦你啦

**Comment by cg3s** [comment]
我们已经收到了，麻烦你提供下微信收款码呢（我们不走支付宝，请理解）

**Comment by qq150593** [comment]
收款码发你邮箱了

**Comment by qq150593** [comment]
我网页还是发不了图片

**Comment by cg3s** [comment]
恩，好的，发邮箱更好

**Comment by cg3s** [comment]
已转，收到请回应下哈

**Comment by qq150593** [comment]
收到，谢谢~

**Comment by cg3s** [comment]
不客气
