### ISSUE TITLE
总有个不是自己的IP在线正常么？如果不正常怎么办？可以禁用那个IP么？

### ISSUE THREAD

**Issue by wuhuaha** [cg3s/forum#149]
## 提交问题请按照格式填写

- 账号：cn_wangxx@163.com
- 操作系统：Windows

- [] 是否已更新节点列表 ```(是: 在[]内填 x, 否: 留空) ```

- [] 是否已查看最新系统公告

- [] 是否已查看常见问题列表

- [] 是否已搜索已解决问题列表

**本问答为公开页面，为保护我们的服务安全和您的个人隐私，如截图中含有以下敏感信息，请马赛克处理。**
- 本站网址
- 本站节点的任何信息

### 问题描述：
总有个不是自己的IP在线正常么？如果不正常怎么办？可以禁用那个IP么？(IP是124.90.47.66，杭州联通的，肯定不是自己的IP，“最近5分钟使用IP”里一直有这个IP，我把自己的电脑和手机全都退出了之后这个IP也一直在)

### 备注：
- [常见问题列表](https://github.com/cg3s/forum/wiki/)
- [已解决问题列表](https://github.com/cg3s/forum/issues?q=is%3Aissue+is%3Aclosed)
- 如想立即得到我们的回复，请在我们的工作时间内提交问题（工作日的10:00-17:00），大多数时候我们能保持快速响应，但不排除我们的工作人员在忙其他的事情，如果我们没有及时回应，请耐心等待。
- 如需上传截图，对敏感信息马赛克后拖拽或拷贝图片到本编辑器中即可。

**Comment by cg3s** [comment]
你可以在【节点设置】里修改节点连接密码，并且重置订阅链接，重置后你自己更新一下节点就行了。

**Comment by wuhuaha** [comment]
好的，多谢了

**Comment by wuhuaha** [comment]
比较奇怪  我从来没给过别人 怎么会被别人用呢？

**Comment by cg3s** [comment]
这就不知道了，你再去我的账户里更新一下网站登录密码吧

**Comment by cg3s** [comment]
56417 | 3107 | 八音幻梦 | 36.5.97.76 | 安徽省合肥市电信 | 2019-07-15 02:20:10 | 成功
55923 | 3107 | 八音幻梦 | 183.212.175.235 | 江苏省南京市移动 | 2019-07-11 08:47:22 | 成功
53568 | 3107 | 八音幻梦 | 101.67.155.87 | 浙江省杭州市联通 | 2019-06-24 22:37:28 | 成功
52621 | 3107 | 八音幻梦 | 112.10.75.248 | 浙江省杭州市移动 | 2019-06-18 21:05:44 | 成功
45432 | 3107 | 八音幻梦 | 112.10.84.150 | 浙江省杭州市移动 | 2019-04-26 18:56:14 | 成功
45431 | 3107 | 八音幻梦 | 112.10.84.150 | 浙江省杭州市移动 | 2019-04-26 18:56:06 | 失败
45375 | 3107 | 八音幻梦 | 123.158.49.9 | 浙江省台州市联通 | 2019-04-26 11:18:37 | 成功
44916 | 3107 | 八音幻梦 | 112.10.84.150 | 浙江省杭州市移动 | 2019-04-21 21:43:22 | 成功
38614 | 3107 | 八音幻梦 | 221.12.20.22 | 浙江省杭州市联通 | 2019-02-25 16:30:39 | 成功
34483 | 3107 | 八音幻梦 | 221.12.20.22 | 浙江省杭州市联通 | 2019-01-15 15:01:36 | 成功
31763 | 3107 | 八音幻梦 | 61.164.32.170 | 浙江省杭州市电信 | 2018-12-19 12:03:41 | 成功

这是你账户曾经的登录记录，你用的手机卡号归属地是哪里呢

**Comment by wuhuaha** [comment]
这些都是正常的 手机双卡的，安徽的和合肥的，再加上家里的和公司的杭州IP。你列表里没有124.90.47.66这个异常IP么？

**Comment by wuhuaha** [comment]
我发现的异常IP124.90.47.66你的列表里没有 是不是就说明这个IP其实并没有通过我的账号登录，不用管他？

**Comment by cg3s** [comment]
我只是贴的你的登录ip列表，在线ip不一定和登录ip匹配，只是用来看看你的账户是不是被别人登录过。
你修改下节点连接密码，并重置订阅链接后，再看看这个ip是否还在。

**Comment by cg3s** [comment]
你说有公司的杭州ip，这个ip是不是你公司的呢

**Comment by wuhuaha** [comment]
不是，我离职了，最近不可能在公司登过

**Comment by cg3s** [comment]
那这就很明显了，你离职的那台电脑还挂着你之前装的软件并且还在使用你的账户配置。

**Comment by wuhuaha** [comment]
刚问过了，不是公司的

**Comment by wuhuaha** [comment]
那个，修改完密码后，客户端的操作是 服务器->编辑服务器->修改密码 ->确定   这个步骤么？

**Comment by wuhuaha** [comment]
另外，顺便问一下，最大在线数是两个，但是因为那个异常IP的存在，导致现在的在线IP经常达到3个，这个会有什么影像呢？

**Comment by cg3s** [comment]
不是，先在网站节点设置页面里，修改节点连接密码，重置订阅连接后，再到客户端设置订阅链接，然后刷新下节点列表就行，不用手动去客户端修改节点，超过最大ip数量后，最后加入的那个ip可能会被踢出去，造成连不上网。

**Comment by wuhuaha** [comment]
好的，多谢了。
