### ISSUE TITLE
新加坡节点

### ISSUE THREAD

**Issue by 43932170** [cg3s/forum#150]
支持奈飞的只有港区？新加坡区有没有？

**Comment by cg3s** [comment]
需要就可以加，回头我们加上，估计今晚能ok。

**Comment by 43932170** [comment]
建议有新加坡，香港，台湾各一个奈飞节点最好了

**Comment by 43932170** [comment]
香港节点连接速度最快，但是经常挂，能否多开一个奈飞节点？或者弄个专用奈飞节点（限制P2P之类下载）？




------------------ 原始邮件 ------------------
发件人: "CGS小管家"<notifications@github.com>;
发送时间: 2019年7月18日(星期四) 晚上8:12
收件人: "cg3s/forum"<forum@noreply.github.com>;
抄送: "43932170"<43932170@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [cg3s/forum] 新加坡节点 (#150)




恩，新加坡已经加上了，台湾目前还没有节点，有节点了我们再加吧，谢谢建议哈，我们会考虑的。

**Comment by cg3s** [comment]
这个月因为有用户购买了超大的流量包，并且无限制的使用香港节点下载数据，目前我们已经下架所有流量包，香港节点将在14日完全恢复，下个月这个问题会完全避免。目前您可以选择新加坡4号节点访问奈飞。
谢谢您的建议，我们后台限制了bt下载的，用户不一定是下的bt，这个只能通过观察后台数据及时调整运营方案来处理。只是之前我们没控制得非常严格，导致当前周期出现香港节点流量耗尽下线的情况。

**Comment by cg3s** [comment]
我们给您调整了用户组别，现在给您换到A组了，A组香港节点全部在线。
更换组别后请刷新下节点列表。
