### ISSUE TITLE
ie浏览器可以正常访问外网，手机也可以正常访问各个网站，谷歌浏览器和360极速都不能访问。

### ISSUE THREAD

**Issue by Fanwen-J** [cg3s/forum#151]
## 提交问题请按照格式填写

- 账号：877xxx856@qq.com

- 操作系统：Windows
- [x] 是否已更新节点列表 

- [x] 是否已查看最新系统公告

- [x] 是否已查看常见问题列表

- [x] 是否已搜索已解决问题列表

### 问题描述：
ie浏览器可以正常访问外网，手机也可以正常访问各个网站，谷歌浏览器和360极速都不能访问。不是刚开始使用，已经使用很久了，之前都正常，今天突然发现不能访问外网了(artstation...)，打开手机试了一下可以正常使用，又打开了ie试了一下也可以正常使用。试了很多方法谷歌浏览器、极速都不可以。

### 备注：
- [常见问题列表](https://github.com/cg3s/forum/wiki/)
- [已解决问题列表](https://github.com/cg3s/forum/issues?q=is%3Aissue+is%3Aclosed)
- 如想立即得到我们的回复，请在我们的工作时间内提交问题（工作日的10:00-17:00），大多数时候我们能保持快速响应，但不排除我们的工作人员在忙其他的事情，如果我们没有及时回应，请耐心等待。
- 如需上传截图，对敏感信息马赛克后拖拽或拷贝图片到本编辑器中即可。
![RD$JX655$9~C}ZY3O{$HU01](https://user-images.githubusercontent.com/53142437/61590718-d1637380-abef-11e9-9152-827392ff2505.png)
![S`_VUF8KJ%IG459A5IK0 FT](https://user-images.githubusercontent.com/53142437/61590720-d45e6400-abef-11e9-84bd-2f1b72834a90.png)
![RZS)E_UASJBKD@Z))9S{I@2](https://user-images.githubusercontent.com/53142437/61590729-e7713400-abef-11e9-8b0a-950f33c44f57.png)
![IMG_20190721_194510](https://user-images.githubusercontent.com/53142437/61590746-19829600-abf0-11e9-8388-d1b5cb28985d.jpg)

**Comment by cg3s** [comment]
方便的话，您装下向日葵远程软件，发个识别码上来，我们远程您看看

**Comment by Fanwen-J** [comment]
好的，识别码是：518 502 143




------------------ 原始邮件 ------------------
发件人: "CGS小管家"<notifications@github.com>;
发送时间: 2019年7月21日(星期天) 晚上9:23
收件人: "cg3s/forum"<forum@noreply.github.com>;
抄送: "877037856"<877037856@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [cg3s/forum] ie浏览器可以正常访问外网，手机也可以正常访问各个网站，谷歌浏览器和360极速都不能访问。 (#151)




方便的话，您装下向日葵远程软件，发个识别码上来，我们远程您看看

**Comment by Fanwen-J** [comment]
你好，我找到原因了，是最近两天刚安装的连接校园网的软件把360和谷歌拦截了，卸载之后就好了。

**Comment by cg3s** [comment]
我们以为你没做任何操作就变成这样了，所以没想是因为装了什么软件导致
解决了就好
