### ISSUE TITLE
如何快速找到哪个服务器到某个地址的速度最快

### ISSUE THREAD

**Issue by xtvjxk123456** [cg3s/forum#152]
- 操作系统：[Windows]

- [x] 是否已更新节点列表 ```(是: 在[]内填 x, 否: 留空) ```

- [x] 是否已查看最新系统公告

- [x] 是否已查看常见问题列表

- [x] 是否已搜索已解决问题列表

想要稳定的快速的访问某个地址，如何选择服务器

**Comment by cg3s** [comment]
勾选节点均衡，打开服务器/服务器统计就可以看到各个节点的速度表现了。

**Comment by xtvjxk123456** [comment]
均衡条件可以改成低超时次数为准么？我这边超时的几率有点大

**Comment by cg3s** [comment]
那个选项你自己可以随便改的，反正就是根据不同的条件去优先选择节点，不会造成不良影响
你是用的哪家的宽带，超时主要是哪些节点，手机上测速延迟如何。

**Comment by xtvjxk123456** [comment]
手机上浏览网页可以接受，不过连接shotgunsoftware.com不够快(手机和pc上都是)
pc 是四川电信，手机流量

**Comment by cg3s** [comment]
访问没有被和谐的域名请将代理规则临时设置到全局模式

**Comment by xtvjxk123456** [comment]
这个方法快多了，那这个方法可以一直这样设置么？

**Comment by cg3s** [comment]
你之前用的pac模式么，如果是，请切换到全局+绕过大陆和局域网的配置。

**Comment by xtvjxk123456** [comment]
并不是，之前一直是全局模式+绕过大陆局域网

**Comment by cg3s** [comment]
那就访问这个网站的时候临时将代理规则切换到全局吧，我们测试了下，推测是因为在绕过大陆和局域网的代理规则模式下，该网站的js代码还是没有走代理，造成访问缓慢。

**Comment by xtvjxk123456** [comment]
ipad 客户端可以测速，pc端这个能测速么？

**Comment by cg3s** [comment]
你指的ipad测速是指shadowrocket里的延迟测试吧？
服务器统计里有相关的实时数据。

**Comment by xtvjxk123456** [comment]
不像是实时的吧

**Comment by cg3s** [comment]
你刷新下页面（比如youtube),延迟数据就会刷新了
