### ISSUE TITLE
写下您的问题概述

### ISSUE THREAD

**Issue by yutingdd** [cg3s/forum#153]
## 提交问题请按照格式填写

- 账号：112747****@qq.com
- 操作系统：Windows

- [] 是否已更新节点列表：是

- [] 是否已查看最新系统公告：是

- [] 是否已查看常见问题列表：是

- [] 是否已搜索已解决问题列表：是

**本问答为公开页面，为保护我们的服务安全和您的个人隐私，如截图中含有以下敏感信息，请马赛克处理。**
- 本站网址
- 本站节点的任何信息

### 问题描述：
新加坡A4和香港A4 看网飞提示使用解锁器 但是手机上是正常的

### 备注：
- [常见问题列表](https://github.com/cg3s/forum/wiki/)
- [已解决问题列表](https://github.com/cg3s/forum/issues?q=is%3Aissue+is%3Aclosed)
- 如想立即得到我们的回复，请在我们的工作时间内提交问题（工作日的10:00-17:00），大多数时候我们能保持快速响应，但不排除我们的工作人员在忙其他的事情，如果我们没有及时回应，请耐心等待。
- 如需上传截图，对敏感信息马赛克后拖拽或拷贝图片到本编辑器中即可。

**Comment by cg3s** [comment]
可以截个图么

**Comment by yutingdd** [comment]
![Uploading QQ截图20190729223121.png…]()

**Comment by yutingdd** [comment]
![QQ截图20190729223121](https://user-images.githubusercontent.com/52329255/62056710-c8f2e480-b250-11e9-9ee7-5805891f2068.png)

**Comment by cg3s** [comment]
你电脑是不是开了节点均衡？

**Comment by yutingdd** [comment]
是

**Comment by cg3s** [comment]
用奈飞要关掉节点均衡，不然会频繁跳到其他节点上去。
