### ISSUE TITLE
IOS账号2个密码均无法使用

### ISSUE THREAD

**Issue by cmccc521** [cg3s/forum#154]
- 账号：(403xxx91@qq.com)

- 操作系统：[iOS]

- [ x] 是否已更新节点列表
-  x[] 是否已查看最新系统公告
- [ x] 是否已查看常见问题列表
-  x[] 是否已搜索已解决问题列表

### 问题描述：

IOS账号2个密码均无法使用

**Comment by cg3s** [comment]
我们测试正常，你确定正确拷贝了密码？

**Comment by cmccc521** [comment]
> 我们测试正常，你确定正确拷贝了密码？
> 注：拷贝密码是直接点击密码的链接，不是手动去选择密码后拷贝

可以了  之前是照着上面手动输入的  原来 复制剪贴板是不同的  智商被压制了

**Comment by cg3s** [comment]
回头我们更新下提示信息，现在的提示对手机不友好。
