### ISSUE TITLE
在使用skype这个软件出现不能打开图片，一直提示正在连接，网络都是正常的，其他软件可以正常使用。

### ISSUE THREAD

**Issue by liuerdong** [cg3s/forum#155]
## 提交问题请按照格式填写

- 账号：(edaijj@xxx.com)

- 操作系统：[Windows]

- [] 是否已更新节点列表 ```(是: 在[]内填 x, 否: 留空) ```

- [] 是否已查看最新系统公告

- [] 是否已查看常见问题列表

- [] 是否已搜索已解决问题列表

### 问题描述：

在使用skype这个软件出现不能打开图片，一直提示 "正在连接......"，网络都是正常的，其他软件可以正常使用。使用自己的网络也没有问题，节点也换了几个还是不行。

**Comment by cg3s** [comment]
skype里面设置了代理么

**Comment by liuerdong** [comment]
没有的，我找其他的vpn测试了下没有问题，可以正常接收信息和图片，现在skype是断网的状态


在2019年8月2日 16:19，CGS小管家<notifications@github.com> 写道：

skype里面设置了代理么

**Comment by cg3s** [comment]
那你把ssr代理模式设置为全局 代理规则也设置为全局试试

**Comment by liuerdong** [comment]
不行，没有网络
在2019年8月2日 16:22，CGS小管家<notifications@github.com> 写道：

那你把ssr代理模式设置为全局 代理规则也设置为全局试试

**Comment by liuerdong** [comment]
你可以上去测试下是不是vpn的问题，其他聊天软件都是可以的，qq,微信，请贵公司尽快找到问题原因         
在2019年8月2日 16:22，CGS小管家<notifications@github.com> 写道：

那你把ssr代理模式设置为全局 代理规则也设置为全局试试

**Comment by liuerdong** [comment]
手机端我测试skype可以使用，Windows电脑端不行









| |
刘大大
|
|
邮箱：edaijj@163.com
|

签名由 网易邮箱大师 定制

在2019年08月02日 16:42，刘大大 写道：


你可以上去测试下是不是vpn的问题，其他聊天软件都是可以的，qq,微信，请贵公司尽快找到问题原因         
在2019年8月2日 16:22，CGS小管家<notifications@github.com> 写道：

那你把ssr代理模式设置为全局 代理规则也设置为全局试试

**Comment by cg3s** [comment]
我们这边拿发送图片作为测试，mac上ok, windows图片发不出去。

**Comment by cg3s** [comment]
我们这边升级下skype就好了
