### ISSUE TITLE
如果我在不同地方使用手机登录，ip不一样会不会被禁用

### ISSUE THREAD

**Issue by oocjing** [cg3s/forum#156]
## 提交问题请按照格式填写

- 账号：4717***41@qq.com

- 操作系统：Windows iOS

- [x] 是否已更新节点列表 ```(是: 在[]内填 x, 否: 留空) ```

- [x] 是否已查看最新系统公告

- [x] 是否已查看常见问题列表

- [x] 是否已搜索已解决问题列表

**本问答为公开页面，为保护我们的服务安全和您的个人隐私，如截图中含有以下敏感信息，请马赛克处理。**
- 本站网址
- 本站节点的任何信息

### 问题描述：
如果我在不同地方使用手机登录，ip不一样会不会被禁用?

### 备注：
- [常见问题列表](https://github.com/cg3s/forum/wiki/)
- [已解决问题列表](https://github.com/cg3s/forum/issues?q=is%3Aissue+is%3Aclosed)
- 如想立即得到我们的回复，请在我们的工作时间内提交问题（工作日的10:00-17:00），大多数时候我们能保持快速响应，但不排除我们的工作人员在忙其他的事情，如果我们没有及时回应，请耐心等待。
- 如需上传截图，对敏感信息马赛克后拖拽或拷贝图片到本编辑器中即可。

**Comment by cg3s** [comment]
不会禁用，默认最多同时在线2个ip，如果已经在线了2个ip，后面加入的新ip会连不上的
