### ISSUE TITLE
157xxxxx16@qq.com

### ISSUE THREAD

**Issue by Zhenghe-code** [cg3s/forum#158]
## 提交问题请按照格式填写

- 账号：(后台可模糊查询，请打码处理，如12345678@qq.com可填写为123xxx78@qq.com)

- 操作系统：[Windows|Mac|Linux|iOS|Android|路由器]

- [] 是否已更新节点列表 ```(是: 在[]内填 x, 否: 留空) ```

- [] 是否已查看最新系统公告

- [] 是否已查看常见问题列表

- [] 是否已搜索已解决问题列表

**本问答为公开页面，为保护我们的服务安全和您的个人隐私，如截图中含有以下敏感信息，请马赛克处理。**
- 本站网址
- 本站节点的任何信息

### 备注：
- [常见问题列表](https://github.com/cg3s/forum/wiki/)
- [已解决问题列表](https://github.com/cg3s/forum/issues?q=is%3Aissue+is%3Aclosed)
- 如想立即得到我们的回复，请在我们的工作时间内提交问题（工作日的10:00-17:00）
- 如需上传截图，对敏感信息马赛克后拖拽或拷贝图片到本编辑器中即可。
![_ W)}6~4~HKOBUT~J OW39A](https://user-images.githubusercontent.com/53827170/62549795-accbf480-b89b-11e9-983e-e553e58316b5.png)

**Comment by Zhenghe-code** [comment]
windows
x
x
x
x
这个问题怎么解决

**Comment by Zhenghe-code** [comment]
157xxxxx16@qq.com
windows
x
x
x
x
这个问题怎么解决
![_ W)}6~4~HKOBUT~J OW39A](https://user-images.githubusercontent.com/53827170/62550288-983c2c00-b89c-11e9-8868-c94726ee3c47.png)

**Comment by cg3s** [comment]
请换个浏览器再试

**Comment by Zhenghe-code** [comment]
我用了谷歌浏览器还是不行咋回事




------------------ 原始邮件 ------------------
发件人: "CGS小管家"<notifications@github.com>; 
发送时间: 2019年8月6日(星期二) 晚上11:12
收件人: "cg3s/forum"<forum@noreply.github.com>; 
抄送: "( &#xFF65;&#x1DC4;&#x1F62;&#xFF65;&#x1DC5; )"<1571548316@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [cg3s/forum] 157xxxxx16@qq.com (#158)




请换个浏览器再试

**Comment by cg3s** [comment]
请参考这个链接设置, https://jingyan.baidu.com/article/63f236286bb2c90208ab3d34.html

**Comment by Zhenghe-code** [comment]
我已经设置了Tls1.0 1.1 1.2那个策略组安全功能没找到
 



------------------ 原始邮件 ------------------
发件人: "CGS小管家"<notifications@github.com>; 
发送时间: 2019年8月9日(星期五) 上午10:33
收件人: "cg3s/forum"<forum@noreply.github.com>; 
抄送: "( &#xFF65;&#x1DC4;&#x1F62;&#xFF65;&#x1DC5; )"<1571548316@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [cg3s/forum] 157xxxxx16@qq.com (#158)




请参考这个链接设置, https://jingyan.baidu.com/article/63f236286bb2c90208ab3d34.html

**Comment by cg3s** [comment]
没找到就安装,请自行百度
