### ISSUE TITLE
##导入了订阅号还是无法fq，急急急急急

### ISSUE THREAD

**Issue by Cocokathy** [cg3s/forum#166]
## 小飞机不能飞起来

- 账号：1484xxx560@qq.com 

- 操作系统：MacOS 版本10.14.4

- [x] 是否已更新节点列表 

- [x] 是否已查看最新系统公告

- [x] 是否已查看常见问题列表

- [] 是否已搜索已解决问题列表

**本问答为公开页面，为保护我们的服务安全和您的个人隐私，如截图中含有以下敏感信息，请马赛克处理。**
- 本站网址
- 本站节点的任何信息

### 问题描述：
我的笔记本之前用的小飞机是ShadowsocksX-NG 版本 1.8.2 (1), 是测试了好多个版本后发现在我的本子上可以使用的，具体为啥别的版本的我就是上不了网..um....我也很苦恼哇。但是呢 我发现这个版本虽然适合我的电脑但是没有服务器 > 编辑订阅...呃呃呃这就很尴尬了。
于是我就回到第一步指示的，下载了ShadowsocksX-NG-R8，以下的那些步骤倒是再没提出错误了，但...就是上不去。这时不甘心的我决定还是打开我之前常用的那个小飞机，打开后惊喜的发现里面的服务器地址自动添加了，这真是柳暗花明啊.. 
然鹅..喜悦的心情并没有持续很久，那些地址我都一一试过了还是不能够打开谷歌..卒。

Ps, 之前在ShadowsocksX-NG 点击 从GFWList更新PAC，但提示从GFWList下载更新失败，我已经在下载了pac.txt文件放进了ShadowsocksX-NG包文件内。现在点击 从GFWList更新PAC 不出现任何提示信息，但还是不能连接外网，不知道怎么解决 急。

PPs, 或者有什么可以联系的方式么 您可以给我发邮箱或是什么.. 感觉我的问题有点儿复杂啊哭哭=。=

### 备注：
- [常见问题列表](https://github.com/cg3s/forum/wiki/)
- [已解决问题列表](https://github.com/cg3s/forum/issues?q=is%3Aissue+is%3Aclosed)
- 如想立即得到我们的回复，请在我们的工作时间内提交问题（工作日的10:00-17:00）
- 如需上传截图，对敏感信息马赛克后拖拽或拷贝图片到本编辑器中即可。

**Comment by Cocokathy** [comment]
访问GitHub没出现安全问题 用火狐开小飞机插件

**Comment by Cocokathy** [comment]
谷歌访问GitHub出现ERR_CONNECTION_CLOSED 是因为没有连接外网的问题，一个是网速慢还一个是墙 所以GitHub会拒绝访问 浏览器提示访问错误。以前开小飞机访问这些网站是没有问题的 
555~ 话说回来 我的小飞机为啥飞不起来啊哭唧唧 T_T

**Comment by cg3s** [comment]
您新建个系统账户，切到新账户里测试下看看呢

**Comment by cg3s** [comment]
我们服务器没任何异常，并且用您的账户配置在我们的mac上使用也正常，推测只能是您个人电脑环境问题，还请多使用排除法测试。

**Comment by Cocokathy** [comment]
请问怎么解决啊，是不是小飞机版本问题？之前使用ss是可以的，现在ssr为什么出错了呢

**Comment by Cocokathy** [comment]
能不能联机下帮我看看？ 电脑不能用小飞机好麻烦啊

**Comment by cg3s** [comment]
您新建了账户测试了？您开一下向日葵吧

**Comment by Cocokathy** [comment]
> 您新建了账户测试了？您开一下向日葵吧

现在还在吗？

**Comment by Cocokathy** [comment]
您看今天什么时间合适 我今天都有时间的，您时间定下来后能否发我邮箱通知我下？ 因为这里没有提示而且小飞机插件总是掉 555~
邮箱号 1484476560@qq.com

**Comment by cg3s** [comment]
麻烦您等下向日葵，不开软件我们没法远程

**Comment by Cocokathy** [comment]
283318106

**Comment by Cocokathy** [comment]
本机识别码

**Comment by Cocokathy** [comment]
邮箱是gmail的…尴尬😅

**Comment by Cocokathy** [comment]
重新控制下吧

**Comment by Cocokathy** [comment]
刚才我点了允许 为啥会没控制上… 好奇怪啊

**Comment by cg3s** [comment]
新建系统账户后一切正常，mac账户出现未知问题。
