### ISSUE TITLE
紧急通告

### ISSUE THREAD

**Issue by cg3s** [cg3s/forum#167]
## 紧急通告
为避免因"国家网络安全周"和"70周年国庆"带来的不必要麻烦，我们已将本站节点全部下线。为弥补对用户造成的影响，我们已对所有vip用户延长7天可用时间。

在此期间我们会对部分节点进行限速安全性测试，有关进展将在下面不断更新，如您有任何疑问，欢迎在下面留言。

## 关于本次紧急通告的说明
1. 每年国庆期间墙都会升高，只是今年高度有点吓人。
2. 国庆期间尽量外出，减少网络使用，尤其是视频大流量行为，力争为国家GDP做出贡献。 
3. 自本公告发布起，补偿7天均为我们手动操作，在您购买套餐后，可用时间不会马上发生变化，请稍等几个小时再看。

## 节点状态更新

**2019-09-18 11:36 测试上线日本A4/B4/C4节点，并限速1Mbps，仅适用于谷歌查询，对联通移动友好。**

- 12:00 日本C4节点不到半小时被墙，ip为新的，不确定是否与未更换域名相关，将对节点域名进行替换。
- 12:18 添加新节点替换日本C4，同时更该节点域名，使用需刷新节点列表。
- 17:42 全新并更换域名的日本C4依然被墙，感觉可能与端口号非443相关。

**2019-09-18 17:44 全面上线日本节点进行安全性测试，限速2Mbps，观察一天，如果A组节点固若金汤，仅B组和C组被墙，则可能与暴露高位端口有关。**

**2019-09-19 00:16 节点均已恢复上线，请所有用户刷新节点列表，认准带A的节点使用，B/C组节点将陆续划到A组。**

**Comment by AbodeCHEN** [comment]
????

**Comment by AbodeCHEN** [comment]
什么时候恢复？

**Comment by AbodeCHEN** [comment]
好歹用完套餐先啊

**Comment by cg3s** [comment]
> 好歹用完套餐先啊

我们也很想让大家正常使用，但最近两天fq领域受安全周和70周年影响特别大，比去年还大。
因为我们的节点已经被墙了几个，如果不下线，很大可能会全部被墙（如此，会造成维护特别耗时）。

**Comment by AbodeCHEN** [comment]
> > 好歹用完套餐先啊
> 
> 我们也很想让大家正常使用，但最近两天FQ领域受安全周和70周年影响特别大，比去年还大。
> 因为我们的节点已经被墙了几个，如果不下线，很大可能会全部被墙（如此，会造成维护特别耗时）。
> 
> 这两天其他机场挂的节点也很多，我们算影响较小的
> 
> 今天我们会测试日本区节点的安全系数，如果风险不大，会上线部分日区节点。

可以的   还好只是暂时~~~

**Comment by cg3s** [comment]
@AbodeCHEN 每年的国庆期间基本都是fq界的重宅期，毕竟不能因为一小部分人的网络自由影响国家重大事件的正常进展。

**Comment by AbodeCHEN** [comment]
> @AbodeCHEN 每年的国庆期间基本都是fq界的安全期，毕竟不能因网络自由影响国家重大事件的正常进展。

了解！！   可以理解~

**Comment by cg3s** [comment]
@AbodeCHEN 谢谢理解！

**Comment by 13026677290** [comment]
我刚刚购买了专业版季度，没有看到这边暂时下线，有没有7天的延长

**Comment by cg3s** [comment]
您用户名是DDZET？7天是我们手动加，今天购买的会稍有延迟，已经给您加了7天了。

现在除了日本4号节点，其他都下线了，您可能勾了负载均衡，软件自动切到日本4号节点了，所以还能使用。

**Comment by cg3s** [comment]
> 我刚刚购买了专业版季度，没有看到这边暂时下线，有没有7天的延长

您用户名是DDZET？7天是我们手动加，今天购买的会稍有延迟，已经给您加了7天了。

现在除了日本4号节点，其他都下线了，您可能勾了负载均衡，软件自动切到日本4号节点了，所以还能使用。

**Comment by 13026677290** [comment]
多谢啦

**Comment by jimie1988** [comment]
我也是才充值的，也没收到7天····难怪我折腾了半天也上不了···原来是被下了，我还以为是我设置有问题···

**Comment by cg3s** [comment]
> 我也是才充值的，也没收到7天····难怪我折腾了半天也上不了···原来是被下了，我还以为是我设置有问题···

您账户是什么

**Comment by jimie1988** [comment]
liu &nbsp; &nbsp; &nbsp;,邮箱留的就是这个邮箱，vimeo登陆不了 显示you have been temporarily blocked也是因为被下线的原因么



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: CGS小管家 <notifications@github.com&gt;
发送时间: 2019年9月18日 19:14
收件人: cg3s/forum <forum@noreply.github.com&gt;
抄送: jimie1988 <225208443@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[cg3s/forum] 紧急通告 (#167)



 
我也是才充值的，也没收到7天····难怪我折腾了半天也上不了···原来是被下了，我还以为是我设置有问题···
  
您账户是什么

**Comment by cg3s** [comment]
> liu &nbsp; &nbsp; &nbsp;,邮箱留的就是这个邮箱，vimeo登陆不了 显示you have been temporarily blocked也是因为被下线的原因么 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: CGS小管家 <notifications@github.com&gt; 发送时间: 2019年9月18日 19:14 收件人: cg3s/forum <forum@noreply.github.com&gt; 抄送: jimie1988 <225208443@qq.com&gt;, Comment <comment@noreply.github.com&gt; 主题: 回复：[cg3s/forum] 紧急通告 (#167) 我也是才充值的，也没收到7天····难怪我折腾了半天也上不了···原来是被下了，我还以为是我设置有问题··· 您账户是什么 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

你的输入法有问题么，没看到任何邮箱

**Comment by jimie1988** [comment]
225208443@qq.com ，留的这个邮箱



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: CGS小管家 <notifications@github.com&gt;
发送时间: 2019年9月18日 19:18
收件人: cg3s/forum <forum@noreply.github.com&gt;
抄送: jimie1988 <225208443@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[cg3s/forum] 紧急通告 (#167)



 
liu &nbsp; &nbsp; &nbsp;,邮箱留的就是这个邮箱，vimeo登陆不了 显示you have been temporarily blocked也是因为被下线的原因么 发自我的iPhone
 …
 ------------------ 原始邮件 ------------------ 发件人: CGS小管家 <notifications@github.com&gt; 发送时间: 2019年9月18日 19:14 收件人: cg3s/forum <forum@noreply.github.com&gt; 抄送: jimie1988 <225208443@qq.com&gt;, Comment <comment@noreply.github.com&gt; 主题: 回复：[cg3s/forum] 紧急通告 (#167) 我也是才充值的，也没收到7天····难怪我折腾了半天也上不了···原来是被下了，我还以为是我设置有问题··· 您账户是什么 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.
  
你的输入法有问题么，没看到任何邮箱

**Comment by cg3s** [comment]
@jimie1988 在您回帖之前我们就已经给您加了7天了，请自行查看。

**Comment by jimie1988** [comment]
哦哦哦 看见了 谢谢 ，意思是未来这7天都上不了是吧？以后有使用问题都直接回复这封邮件就可以了？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: CGS小管家 <notifications@github.com&gt;
发送时间: 2019年9月18日 19:19
收件人: cg3s/forum <forum@noreply.github.com&gt;
抄送: jimie1988 <225208443@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[cg3s/forum] 紧急通告 (#167)




@jimie1988 在您回帖之前我们就已经给您加了7天了，请自行查看。

**Comment by cg3s** [comment]
@jimie1988 vimeo不能访问是因为目前仅开放日本节点测试，因为日本节点的ip可能之前被人用来爬虫，导致ip被vimeo封锁

目前我们还在测试安全性，可能还需要观察1天日本节点的表现，目前发现安全隐患可能是因为高位端口导致，我们会采取技术措施尽量避免。这个帖子是公开的，每个参与的人都会收到邮件提醒，为避免打扰，一楼里已经告知的，就最好不要重复讨论了。

**Comment by jimie1988** [comment]
好滴 谢谢



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: CGS小管家 <notifications@github.com&gt;
发送时间: 2019年9月18日 19:26
收件人: cg3s/forum <forum@noreply.github.com&gt;
抄送: jimie1988 <225208443@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[cg3s/forum] 紧急通告 (#167)




@jimie1988 vimeo不能访问是因为目前仅开放日本节点测试，因为日本节点的ip可能之前被人用来爬虫，导致ip被vimeo封锁
 
目前我们还在测试安全性，可能还需要观察1天日本节点的表现，目前发现安全隐患可能是因为高位端口导致，我们会采取技术措施尽量避免。这个帖子是公开的，每个参与的人都会收到邮件提醒，为避免打扰，一楼里已经告知的，就最好不要重复讨论了。

**Comment by sworduc** [comment]
所有节点都无法上网！
显示错误如下：
![图片](https://user-images.githubusercontent.com/54285906/65825984-3bfbf400-e2b0-11e9-9c47-fef2d8b62826.png)

firefox/chome/IE
