### ISSUE TITLE
ios下载app,需要验证密码,粘贴密码提示账号或密码错误,无法下载app

### ISSUE THREAD

**Issue by a4736435** [cg3s/forum#168]
## 提交问题请按照格式填写

- 账号：(后台可模糊查询，请打码处理，如12345678@qq.com可填写为123xxx78@qq.com)

- 操作系统：[Windows|Mac|Linux|iOS|Android|路由器]

- [] 是否已更新节点列表 ```(是: 在[]内填 x, 否: 留空) ```

- [] 是否已查看最新系统公告

- [] 是否已查看常见问题列表

- [] 是否已搜索已解决问题列表

**本问答为公开页面，为保护我们的服务安全和您的个人隐私，如截图中含有以下敏感信息，请马赛克处理。**
- 本站网址
- 本站节点的任何信息

### 备注：
- [常见问题列表](https://github.com/cg3s/forum/wiki/)
- [已解决问题列表](https://github.com/cg3s/forum/issues?q=is%3Aissue+is%3Aclosed)
- 如想立即得到我们的回复，请在我们的工作时间内提交问题（工作日的10:00-17:00），大多数时候我们能保持快速响应，但不排除我们的工作人员在忙其他的事情，如果我们没有及时回应，请耐心等待。
- 如需上传截图，对敏感信息马赛克后拖拽或拷贝图片到本编辑器中即可。

**Comment by cg3s** [comment]
我这边测试了一下，粘贴复制过去的账户密码都能正常登录

**Comment by a4736435** [comment]
我在翻到底部,下载shadow软件的时候提示我输入app账户密码    但是账号显示的却是50开头的qq邮箱

**Comment by cg3s** [comment]
您都登录了app store找到软件下载的地方了，还需要什么账户密码？

**Comment by a4736435** [comment]
正常下载app,右边是一个云的图标,但是shadow的那个右边却是一个  updown(拼写可能有误)的按钮,点击按钮就要验证密码,用粘贴的密码死活不行~~~~而且验证的账号居然是50开头的qq邮箱账号

**Comment by cg3s** [comment]
我看看

**Comment by a4736435** [comment]
我也纳闷啊,appstore登录的就是你的账号密码,也找到你藏软件的那个位置了,下载的时候居然要我验证密码,而且居然是50开头的qq邮箱的密码,我倒腾了一下午,现在手机还给朋友了,只能下次再试试了

**Comment by cg3s** [comment]
![image](https://user-images.githubusercontent.com/28707826/65371200-d72f1100-dc93-11e9-848f-02138155472c.png)
![image](https://user-images.githubusercontent.com/28707826/65371202-db5b2e80-dc93-11e9-98ea-dd5bda83d8b8.png)
![image](https://user-images.githubusercontent.com/28707826/65371204-deeeb580-dc93-11e9-90f5-0b29d884e86c.png)
测试正常，应该是您的设备原因

**Comment by a4736435** [comment]
你点击那个update的,也不用输入密码吗??

**Comment by cg3s** [comment]
目测您用的设备之前不是用的我们的账户下载的这个软件，点update自然会要求输入原始账户，这种一般删掉软件重新用我们的账户下载即可。

**Comment by a4736435** [comment]
哦哦,好的,我回头试一下,谢谢

**Comment by a4736435** [comment]
再问一下,就是说,以前从别的地方下载到shadow软件不能用,只能用你们那个账号(加拿大)下载的软件才能用是吗??因为以前是从别的国家id下载的

**Comment by cg3s** [comment]
https://www.zhihu.com/question/333507551/answer/739285082

**Comment by sharkhardman** [comment]
> 我们这边测试了一下，两个账户粘贴复制过去的账户密码都能正常登录，我们不至于犯这种低级错误，一般用户只会遇到账户需要解锁的情况。

我刚注册的，因为更新了最新的ios系统，app store登录时会跳到浏览器，输入账户-2的账号密码时，跳出了密保问题，第一个宠物的名字，第二个是你的梦想工作，英文的，咋整？？？

**Comment by cg3s** [comment]
@sharkhardman 系统版本多少？

**Comment by sharkhardman** [comment]
> @sharkhardman 系统版本多少？

13.0

**Comment by sharkhardman** [comment]
> @sharkhardman 系统版本多少？

是用不了吗？还是怎么回事？

**Comment by cg3s** [comment]
我们手上无13.0的系统，暂时无法测试

**Comment by sharkhardman** [comment]
> 我们手上无13.0的系统，暂时无法测试

那我iphonex暂时是不能用了对吧？

**Comment by cg3s** [comment]
您可以多查询相关资料。

**Comment by sharkhardman** [comment]
> 您可以多查询相关资料。

目前不是不能用，是我登录你们提供的两个id时，提示需要回答问题，这两个密保问题，你们应该有答案的啊。

**Comment by cg3s** [comment]
我们不会提供安全问题的答案，因为会涉及其他用户的个人隐私。

**Comment by sharkhardman** [comment]
> 我们不会提供安全问题的答案，因为会涉及其他用户的个人隐私。

好的，那就等新用户更多的反馈吧。希望你们可以尽快解决这个问题。我比较急用……

**Comment by sharkhardman** [comment]
> 我们不会提供安全问题的答案，因为会涉及其他用户的个人隐私。
或者您这边还有其他方法下载ios客户端的软件么？捷径方式有没有？？？快捷指令这样的安装器。

**Comment by sharkhardman** [comment]
> 我们不会提供安全问题的答案，因为会涉及其他用户的个人隐私。

或者您这边还有其他方法下载ios客户端的软件么？捷径方式有没有？？？快捷指令这样的安装器。

**Comment by cg3s** [comment]
没有，您也可以自己注册非国区appleid，然后购买shadowrocket软件

**Comment by wanggang-ing** [comment]
> > 我们这边测试了一下，两个账户粘贴复制过去的账户密码都能正常登录，我们不至于犯这种低级错误，一般用户只会遇到账户需要解锁的情况。
> 
> 我刚注册的，因为更新了最新的ios系统，应用商店登录时会跳到浏览器，输入帐户-2的账号密码时，跳出了密保问题，第一个宠物的名字，第二个是你的梦想工作，英文的，咋整???

我现在也出现这个问题，我都不知道怎么填写，求解，谢谢。

**Comment by wanggang-ing** [comment]
> 我们不会提供安全问题的答案，因为会涉及其他用户的个人隐私。

![f0ec9928b47aef5f9899a055c0ce8d3](https://user-images.githubusercontent.com/55678115/65401084-71a86500-ddf8-11e9-9c8e-05e18dad3377.jpg)

**Comment by wanggang-ing** [comment]
现在的情况就是这样的，现在需要怎么下载软件。因为我换了一个手机，现在需要重新下载这个软件。

**Comment by cg3s** [comment]
请等待我们在ios13上测试，目前因为没有该系统的手机无法提供任何技术支持。

**Comment by wanggang-ing** [comment]
好的，谢谢。




------------------ 原始邮件 ------------------
发件人: "CGS小管家"<notifications@github.com>; 
发送时间: 2019年9月23日(星期一) 中午12:05
收件人: "cg3s/forum"<forum@noreply.github.com>; 
抄送: "〔〕summer、倾夏"<748618639@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [cg3s/forum] ios下载app,需要验证密码,粘贴密码提示账号或密码错误,无法下载app (#168)




请等待我们在ios13上测试，目前因为没有该系统的手机无法提供任何技术支持。

**Comment by wanggang-ing** [comment]
我这边注册了美国的ID，请问怎么充值购买软件呢？主要是充值问题

**Comment by cg3s** [comment]
@wanggang-ing 请自行百度谷歌搜索 “如何购买美区App Store软件”

**Comment by wanggang-ing** [comment]
你好，反馈一下，现在13.0可以登录，点击头像后往下面划-选择登出，然后再登录你们提供的账号即可。

**Comment by cg3s** [comment]
@wanggang-ing 对啊，但是登录的时候不是要通过浏览器跳转到appleid.apple.com登录么，在这里登录需要填写问题答案。

您可以发个登录后的截图么

**Comment by wanggang-ing** [comment]
![32d08fa58963be173e5b9579e2995c8](https://user-images.githubusercontent.com/55678115/65494516-94657700-dee7-11e9-81df-7b858a0778ff.jpg)点击IDto头像进去，
![a6a31e9a95f4134aa4c71a6c7176d01](https://user-images.githubusercontent.com/55678115/65494547-a0e9cf80-dee7-11e9-8aeb-bc848230f10c.jpg)
划到最下边，点击登出，然后就可以登录你们提供的账号了。

**Comment by cg3s** [comment]
哦，那就是以前的地方，只是13很坑爹，把app更新全部塞到中间区域了，列表太长就懒得刷到最下面了，一会我们测试一下。谢谢反馈

**Comment by cg3s** [comment]
@wanggang-ing 为表示感谢，已为您账户延长一个月可用时间。

**Comment by sharkhardman** [comment]
> @wanggang-ing 为表示感谢，已为您账户延长一个月可用时间。

我这边13.0还是不能使用，仍然提示密保问题。

**Comment by cg3s** [comment]
楼上不是已经说了，切换账户的地方么
另外，我们在教程ios页面更新了提示信息。其实和以前是一样的，只是app更新列表嵌入到了账户页面，导致容易找不到地方而已。
