### ISSUE TITLE
最近一周,突然更新失败

### ISSUE THREAD

**Issue by cgdvs** [cg3s/forum#169]
## 提交问题请按照格式填写

- 账号：cgdxxx78@qq.com)

- 操作系统：[Windows]

- [] 是否已更新节点列表 ```(是: 在[]内填 x, 否: 留空) ```

- [] 是否已查看最新系统公告

- [] 是否已查看常见问题列表

- [] 是否已搜索已解决问题列表

**本问答为公开页面，为保护我们的服务安全和您的个人隐私，如截图中含有以下敏感信息，请马赛克处理。**
- 本站网址
- 本站节点的任何信息

### 问题描述：就是最近一周,突然用不了了.我以为是最近无法使用,后来我问其他人,他们一直都很正常.我也找不到任何原因.只是突然不能使用了.
  表现为,打开程序后,要近一分钟才会提示,更新错误.再次打开也是如此.在这之前,一直都很正常.

### 备注：
- [常见问题列表](https://github.com/cg3s/forum/wiki/)
- [已解决问题列表](https://github.com/cg3s/forum/issues?q=is%3Aissue+is%3Aclosed)
- 如想立即得到我们的回复，请在我们的工作时间内提交问题（工作日的10:00-17:00）
- 如需上传截图，对敏感信息马赛克后拖拽或拷贝图片到本编辑器中即可。

**Comment by cg3s** [comment]
可能您电脑dns解析有问题，也就是解析我们的官网域名有问题，您可以在节点列表里用扫码的方式添加节点，然后选到能用的节点后，在【服务器订阅】菜单点击第二项【更新订阅节点】

**Comment by cgdvs** [comment]
![图片](https://user-images.githubusercontent.com/51322547/65762316-53719a80-e153-11e9-9ea1-df205d66ed64.png)
![图片](https://user-images.githubusercontent.com/51322547/65762337-5f5d5c80-e153-11e9-8453-98a0649732a7.png)
如果DNS解析问题.怎么会是突然出现的呢?这样说来,我以前也可能无法用才对啊.

**Comment by cg3s** [comment]
正常情况下，如果您不开ssr就能打开我们的官网，那么这里订阅理论上就能正常更新，如果打不开官网，这里也应该不行

![image](https://user-images.githubusercontent.com/28707826/65766098-92f0b480-e15c-11e9-958d-8485613dc8f1.png)
蓝色连接点一下里面有二维码，可以扫描添加，也可以根据上面的配置信息手动添加，这个不需要教程，稍微对我们网站熟悉一下就明白了。

**Comment by cg3s** [comment]
如果还是不行，您可以发个向日葵识别码过来，我们远程您。

**Comment by cgdvs** [comment]
谢谢谢谢.今天用二维码就连接成功了.先这样用着.感谢.

**Comment by cg3s** [comment]
不客气，但为了以后的方便最好还是通过订阅方式，国庆之后我们节点会有比较大的调整，请留意最新公告。
