### ISSUE TITLE
代理无法打开网页

### ISSUE THREAD

**Issue by sworduc** [cg3s/forum#170]
## 提交问题请按照格式填写

- 账号：50**40@qq.com

- 操作系统：Windows 10

- [] 是否已更新节点列表 ```是 ```

- [] 是否已查看最新系统公告

- [] 是否已查看常见问题列表

- [] 是否已搜索已解决问题列表

**本问答为公开页面，为保护我们的服务安全和您的个人隐私，如截图中含有以下敏感信息，请马赛克处理。**
- 本站网址
- 本站节点的任何信息

### 问题描述：
昨天开始代理无法打开网页，显示内容为：
![图片](https://user-images.githubusercontent.com/54285906/65825933-89c42c80-e2af-11e9-9a1a-6a6e9348f388.png)

**建立安全连接失败
载入页面时与服务器的连接被重置。
    由于不能验证所收到的数据是否可信，无法显示您想要查看的页面。
    建议向此网站的管理员反馈这个问题。**

试过“火狐、chome和IE都是如此”，请问怎么解决？
### 备注：
- [常见问题列表](https://github.com/cg3s/forum/wiki/)
- [已解决问题列表](https://github.com/cg3s/forum/issues?q=is%3Aissue+is%3Aclosed)
- 如想立即得到我们的回复，请在我们的工作时间内提交问题（工作日的10:00-17:00），大多数时候我们能保持快速响应，但不排除我们的工作人员在忙其他的事情，如果我们没有及时回应，请耐心等待。
- 如需上传截图，对敏感信息马赛克后拖拽或拷贝图片到本编辑器中即可。

**Comment by cg3s** [comment]
请查看 常见问题列表

**Comment by sworduc** [comment]
> 
> 
> e¯·æ¥c一¸¸e§e®e¢一e¡¨

反复看了几次常见问题列表！都不知道怎么解决！这是突然出现的！
能给个解决方案吗？

**Comment by cg3s** [comment]
开了节点负载均衡么，没开的话，换个节点试试。

**Comment by sworduc** [comment]
> 
> 
> 开了节点负载均衡么，没开的话，换个节点试试。

开了！几乎换了所有的节点都不行！昨天突然出现的！

**Comment by cg3s** [comment]
那您发个向日葵识别码过来，我们远程您

**Comment by sworduc** [comment]
我用的是TeamViewer
ID:1 375 701 443
密码：653bbn

**Comment by cg3s** [comment]
teamviewer我们设备使用太多，已经不能使用了，还请提供向日葵识别码

**Comment by sworduc** [comment]
那你等等我装一个

**Comment by sworduc** [comment]
393 377 297
Hf1h41

**Comment by cg3s** [comment]
原ssr所在文件夹出现未知问题，重下软件重新配置后一切正常。

**Comment by sworduc** [comment]
谢谢！以后知道怎么解决了！

**Comment by cg3s** [comment]
不知道跟您的杀毒软件有没有关系，之前的ssr根本没连上我们的服务器，您的系统不知道哪个地方把软件屏蔽了。

**Comment by sworduc** [comment]
我是前天晚上更新WIN10系统后 昨天发现用不了的！
其他所有设置都没有动过！
杀毒软件的问题我一开始就排除了！
昨天一直以为浏览器的问题
后来试了FireFox、chome、IE都一样的问题才求助你们的！

**Comment by cg3s** [comment]
那可能是升级系统后，ssr被系统的防火墙拦截了

**Comment by cg3s** [comment]
正常情况第一次启动ssr，不是有个弹出窗口勾选后让防火墙放行的么，升级系统后win10为了系统安全这个机制可能要重新配置

**Comment by sworduc** [comment]
这个问题我也排除了
我在防火墙里设置白名单了
应该是代理程序出了问题
我刚刚把软件重新放进以前的文件夹可以正常使用！
应该是软件本身的问题！
