### ISSUE TITLE
iOS端不能使用了，和账号无关。我把订阅删除了，重新填写订阅连接，节点列表为空。

### ISSUE THREAD

**Issue by pinguo-mazhong** [cg3s/forum#171]
- 操作系统：iOS 13.1 
- 操作步骤：
1. 打开APP后显示的以前的节点都不能正常使用。
2. 删除之前的订阅和所有节点，重新配置订阅，点击“完成”，无任何节点显示。

**Comment by cg3s** [comment]
我们也测试了下，的确有此问题，您可以通过以下两种方式：
1、在节点列表页面通过扫描配置节点
2、使用账号2下载Quantumult应用（Hidden Purchases列表倒数第二个），同样通过订阅链接更新节点列表，然后开启软件即可。

**Comment by cg3s** [comment]
更新说明:
出现这个情况可能和近期国庆相关,我们在wifi状态下刷新节点列表也出现无节点的情况,但切好4G网络就正常了.

所以怀疑和国庆期间访问本站的网络延迟有关,接下来我们将优化国内到本站的延迟情况.

**Comment by nyjjky** [comment]
windows客户端订阅刷新只有free节点

**Comment by cg3s** [comment]
@nyjjky 我们这边在windows下测试正常呢。
手动将所有cgs节点删除，然后重启软件，订阅更新成功，节点列表能刷新出所有cgs可用的节点。

**Comment by nyjjky** [comment]
尝试了还是不行哦，重新删除软件，再添加订阅，订阅更新成功的是free组，只有限速的几个节点

**Comment by cg3s** [comment]
你可以在浏览器里试试打开订阅链接如果能正常弹出下载txt文件的提示，就说明是正常的。

**Comment by nyjjky** [comment]
会自动复制到剪切板

**Comment by cg3s** [comment]
你确定正确的设置了订阅链接么
