### ISSUE TITLE
续费问题

### ISSUE THREAD

**Issue by Kevinsaifer** [cg3s/forum#172]
## 提交问题请按照格式填写

- 账号：(kevxxxxxxr@foxmail,com)

- 操作系统：[Windows10]

- [是] 是否已更新节点列表 ```(是: 在[]内填 x, 否: 留空) ```

- [是] 是否已查看最新系统公告

- [是] 是否已查看常见问题列表

- [] 是否已搜索已解决问题列表

**本问答为公开页面，为保护我们的服务安全和您的个人隐私，如截图中含有以下敏感信息，请马赛克处理。**
- 本站网址
- 本站节点的任何信息

### 问题描述：

一开始买的是基础版，然后再升级专业版发现没有改变月供流量，而且只是加长了使用时间，但我想要的是每个月专业版流量使用。为什么升级不是补价而是还要再买一个专业版？

### 备注：
- [常见问题列表](https://github.com/cg3s/forum/wiki/)
- [已解决问题列表](https://github.com/cg3s/forum/issues?q=is%3Aissue+is%3Aclosed)
- 如想立即得到我们的回复，请在我们的工作时间内提交问题（工作日的10:00-17:00）
- 如需上传截图，对敏感信息马赛克后拖拽或拷贝图片到本编辑器中即可。

**Comment by cg3s** [comment]
谢谢反馈
主要之前为了考虑流量滥用问题，我们稍后升级下这个功能
同时已为您取消基础版的购买记录，并撤销一年的使用期限，同时退回基础版的费用，请查看您的账号余额，另外如果需要退回这120，可提供微信收款码。

**Comment by Kevinsaifer** [comment]
多谢解答。还是退款吧。基础版不会再买了，充值方面不能选自由价位充值还是有点伤。




------------------ 原始邮件 ------------------
发件人: "CGS小管家"<notifications@github.com>;
发送时间: 2019年9月29日(星期天) 晚上8:12
收件人: "cg3s/forum"<forum@noreply.github.com>;
抄送: "为美好的人生献上诅咒"<Kevinsaifer@foxmail.com>;"Author"<author@noreply.github.com>;
主题: Re: [cg3s/forum] 续费问题 (#172)




谢谢反馈
 主要之前为了考虑流量滥用问题，我们稍后升级下这个功能
 同时已为您取消基础版的购买记录，并撤销一年的使用期限，同时退回基础版的费用，请查看您的账号余额，另外如果需要退回这120，可提供微信收款码。

**Comment by cg3s** [comment]
@Kevinsaifer , 直接支付宝微信付款我们早就有这个功能，但会暴露一些安全问题，所以从来没正式使用使用。
现在升级功能已调整，点击升级会只计算差价部分，不会新购续期。

您可以发个微信收款码过来，可直接发到这里或者发到我们邮箱 service@cgsss.net
