### ISSUE TITLE
关于无法加载pornhub视频问题

### ISSUE THREAD

**Issue by daya0413** [cg3s/forum#174]
我也记不清是什么时候  大概是在一个半月前左右吧  我就无法加载出pornhub的视频了 网站能进去 就是视频缓冲一直缓冲无法播放  起初我以为我是电脑的问题 然后用我朋友的电脑也试了（我朋友也是我推荐用的这款vpn）也一样无法打开 现在过了一些日子 依然是打不开 但是ytb和其他视频网站都能正常播放  这让我在想是不是vpn的原因？节点什么的 我都换过很多次了  不清楚还有没有人和我一样无法加载出pornhub的视频 目前我只知道我和我朋友无法加载出

**Comment by cg3s** [comment]
我们这边能正常播放

**Comment by leixianya** [comment]
> 我们在win / mac / linux各个环境下测试均能正常播放，而且服务器没有该网站采用任何限制措施，理论上大家应该都没有这个问题，
> 请问你们是在家里使用吗？你们可以测试下手机4G环境是否正常。

我也遇到了这样的问题 在家使用 4g环境正常

**Comment by cg3s** [comment]
官方有这个问题的问答页面
http://feedback.pornhub.com/forums/184663-pornhub-feedback-and-suggestions/suggestions/34604833-fix-video-is-not-available-at-the-moment?page=1&per_page=20

**Comment by cg3s** [comment]
#176 参考这个issue下的内容

**Comment by foxli91** [comment]
我使用的是Chrome+ssr即使开全局模式把所有的广告过滤插件关闭也无法观看，换浏览器，清空缓存，切换运营商都无法解决这种问题，只是偶尔刷新之后能看极个别视频，我个人觉得应该是p站自己的问题。

**Comment by cg3s** [comment]
@foxli91 访客模式试过么

**Comment by foxli91** [comment]
Chrome的所有模式都试过，还是有这种问题，使用老ie，edge，也是能访问网站，但是看不了视频，但是看油管的视频无论哪个浏览器都可以。很久没用火狐了，我回头试一试，朋友除了这个还有啥解决办法吗？下载pb上面的视频登录了账号下载也会出问题，我记得19年7月份之前都没这个问题，就是从11月之后就出现了这个问题。

**Comment by foxli91** [comment]
@cg3s  Chrome的所有模式都试过，还是有这种问题，使用老ie，edge，也是能访问网站，但是看不了视频，但是看油管的视频无论哪个浏览器都可以。很久没用火狐了，我回头试一试，朋友除了这个还有啥解决办法吗？下载pb上面的视频登录了账号下载也会出问题“无法访问此网站网址为 https://dd1.phncdn.com/video......”，我记得19年7月份之前都没这个问题，就是从11月之后就出现了这个问题。

**Comment by cg3s** [comment]
这个我们这边测试从未出现不能播放视频的问题，只能远程你电脑看看

**Comment by foxli91** [comment]
@cg3s 怎么联系您呢，我的是win10系统。

**Comment by cg3s** [comment]
发一下向日葵远程软件的识别码

**Comment by foxli91** [comment]
@cg3s 谢谢朋友的回复，我的那个梯子抽风了一直没登录上github，最后我排查了对比了其他的机场供应商，是他们线路不稳定，最后换成了他们的v2ray路线使用他们专门的节点就解决这个问题了，如果有人搜到了这个问题也提醒一下墙内后来的朋友，遇到这种情况肯定是自身梯子的问题，更换节点或者换个机场。

**Comment by cg3s** [comment]
@foxli91 囧，您不是我们的用户哦

**Comment by daya0413** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"CGS小管家"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月9日(星期天) 晚上9:22
收件人:&nbsp;"cg3s/forum"<forum@noreply.github.com&gt;;
抄送:&nbsp;"♚丫丫♚"<1428225891@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [cg3s/forum] 关于无法加载pornhub视频问题 (#174)




@foxli91 囧，您不是我们的用户哦
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

我的用户账号是2732930163@qq.com&nbsp; 我是你们用户啊

**Comment by cg3s** [comment]
@daya0413 楼上foxli91这个账户也是你？
