### ISSUE TITLE
请问可以解决eagle插件的问题吗

### ISSUE THREAD

**Issue by behonQ** [cg3s/forum#175]
## 提交问题请按照格式填写

- 账号：(后台可模糊查询，请打码处理，如12345678@qq.com可填写为123xxx78@qq.com)

- 操作系统：[Windows|Mac|Linux|iOS|Android|路由器]

- [x] 是否已更新节点列表 ```(是: 在[]内填 x, 否: 留空) ```

- [x] 是否已查看最新系统公告

- [x] 是否已查看常见问题列表

- [x] 是否已搜索已解决问题列表

**本问答为公开页面，为保护我们的服务安全和您的个人隐私，如截图中含有以下敏感信息，请马赛克处理。**
- 本站网址
- 本站节点的任何信息

### 备注：
- [常见问题列表](https://github.com/cg3s/forum/wiki/)
- [已解决问题列表](https://github.com/cg3s/forum/issues?q=is%3Aissue+is%3Aclosed)
- 如想立即得到我们的回复，请在我们的工作时间内提交问题（工作日的10:00-17:00）
- 如需上传截图，对敏感信息马赛克后拖拽或拷贝图片到本编辑器中即可。

**Comment by cg3s** [comment]
谢谢反馈，这样说eagle的问题根源可能是阻碍了ssr的443端口链接？
这几天我们还不会分组，还要等一段时间，等分组后，我们再给您换到C组吧，您现在可以换个不装eagle插件的浏览器使用。

**Comment by behonQ** [comment]
不知道为什么关了eagle也不可以了

**Comment by behonQ** [comment]
可以远程看一下吗

**Comment by cg3s** [comment]
您可以重新下载软件走一遍流程看看，今天我们可能没有时间远程。

**Comment by behonQ** [comment]
按流程还是不能，一直没办法，之前我是A节点的时候也是不行，然后换了C才可以，会不会和这个有关

**Comment by behonQ** [comment]
现在这样我一直不能用，可以解决吗？大概什么时候

**Comment by cg3s** [comment]
您先可以试下chrome的访客模式,看行不行,如果访客模式ok的话,就不是我们的问题了.

**Comment by cg3s** [comment]
![image](https://user-images.githubusercontent.com/28707826/66624887-8e300400-ec24-11e9-841e-61a747251ed0.png)
打开访客模式的方式

之前远程我们应该演示过这个方法

**Comment by behonQ** [comment]
还是不行

**Comment by cg3s** [comment]
你发个向日葵识别码吧,这会方便远程?

**Comment by behonQ** [comment]
手机可以，电脑不行

**Comment by behonQ** [comment]
713 472 747

**Comment by behonQ** [comment]
所以是什么原因？IP地址？

**Comment by cg3s** [comment]
eagle软件和ssr有冲突吧,具体怎么冲突不详

**Comment by behonQ** [comment]
这已经发展到软件问题了？

**Comment by cg3s** [comment]
我刚才退出eagle软件,就ok了啊,这就很明显可能是eagle占用了什么资源,导致ssr不能用.

**Comment by cg3s** [comment]
具体的我们这边会抽时间用eagle进行测试,看看能不能找到具体原因.

**Comment by behonQ** [comment]
那麻烦你们尽早解决这个问题吧，eagle也是很需要用的，我印象中他们自己也有在弄梯子，不知道会不会有影响，谢谢啦

**Comment by cg3s** [comment]
哦? 是么，他们也在弄梯子？
装上试了，但没有复现你遇到的状况。

**Comment by behonQ** [comment]
不是，是加了公号才知道他们有搭梯子，我这边也是偶尔可以用，偶尔就不行

**Comment by cg3s** [comment]
是微信公众号?这个还敢在微信里聊?
