### ISSUE TITLE
无法加载pornhub视频 显示vieao is not available at the moment

### ISSUE THREAD

**Issue by leixianya** [cg3s/forum#176]
无法加载pornhub视频 显示vieao is not available at the moment  更换节点也不行 在家其他功能正常使用 4g正常

**Comment by cg3s** [comment]
是不是公司网管封锁了pornhub呢

**Comment by cg3s** [comment]
Guys, It's cause u use KA-block. You have to disable it (not only on page, but whole extension)... you are welcome

伙计们，这是因为你们使用了 ka- 阻挡。 你必须禁用它(不仅在第页，但整个扩展) ... 欢迎你

**Comment by cg3s** [comment]
retards, it's a safety measure. There's probably something like a video view cookie that expires in an hour or two, so if you wait long enough the video view will expire and it works when you refresh the page.

白痴们，这是安全措施。 可能有类似视频视图 cookie 的东西在一两个小时后过期，所以如果你等待足够长的时间，视频视图就会过期，当你刷新页面时它就会工作。

**Comment by cg3s** [comment]
目测这个情况跟我们服务器没多大关系，感觉像是pornhub的保护机制，不能让你频繁刷新页面，让您再等等再看视频，就像玩游戏有个时间限制一样。
