### ISSUE TITLE
自动禁用出错服务器，一直不能用？

### ISSUE THREAD

**Issue by xtvjxk123456** [cg3s/forum#178]
客户端自动禁用出错服务器，一直都不能时候，体验有些差，有其他可以自动禁用出错客户端的客户端么？我这边既有超时，又有出错的情况，现在的客户端太不好用了

**Comment by cg3s** [comment]
请问您是指“屏蔽流氓软件”的问题么

**Comment by xtvjxk123456** [comment]
不是，是自动禁用出错服务器（看客户端里有相关设置，但是灰色的无法使用），我这边，好多延迟，外加时不时的出错，需要一个更智能的客户端

**Comment by cg3s** [comment]
你关掉负载均衡，选个稳定的节点就是了，我们不推荐使用负载均衡，因为会导致ip频繁变动，影响体验，关掉负载均衡后，那个选项也无所谓了。

**Comment by xtvjxk123456** [comment]
问题是关掉后，我不知道哪个服务器是稳定的，大都是超时，或出错的服务器，我想固定在香港服务器这组内。不想使用其他组的（香港这组有几个经常出错和超时的）

**Comment by cg3s** [comment]
这个月受国庆gfw发力影响，体验的确会比往常有所下降，我们会陆续升级并增加服务器降低节点负载。

客户端的问题，可能也是因为节点这两天频繁掉线导致，我看您是电信，可以先用A8

**Comment by xtvjxk123456** [comment]
好的

**Comment by cg3s** [comment]
新加坡 香港 洛杉矶都是CN2线路对电信都比较友好，关掉节点负载，优先选择数字大的，因为我们新增的节点都会排序靠后，新增的节点人数相对来说会少很多。
