### ISSUE TITLE
10.11日无法科学上网

### ISSUE THREAD

**Issue by Cocokathy** [cg3s/forum#179]
## 提交问题请按照格式填写

- 账号：1484xxx560@qq.com)

- 操作系统：[MacOS  版本10.14.6]

- [x] 是否已更新节点列表

- [x] 是否已查看最新系统公告

- [x] 是否已查看常见问题列表

- [x] 是否已搜索已解决问题列表

**本问答为公开页面，为保护我们的服务安全和您的个人隐私，如截图中含有以下敏感信息，请马赛克处理。**
- 本站网址
- 本站节点的任何信息

### 备注：
- [常见问题列表](https://github.com/cg3s/forum/wiki/)
- [已解决问题列表](https://github.com/cg3s/forum/issues?q=is%3Aissue+is%3Aclosed)
- 如想立即得到我们的回复，请在我们的工作时间内提交问题（工作日的10:00-17:00），大多数时候我们能保持快速响应，但不排除我们的工作人员在忙其他的事情，如果我们没有及时回应，请耐心等待。
- 如需上传截图，对敏感信息马赛克后拖拽或拷贝图片到本编辑器中即可。

**Comment by Cocokathy** [comment]
对了 更新订阅啥的都正常的，

**Comment by cg3s** [comment]
您的节点列表不对.链接都是老的了,请删掉所有节点,再更新

**Comment by cg3s** [comment]
香港A3节点,流量用完了,自然就不能连了,您更新节点后选香港A9吧,刚加的

**Comment by Cocokathy** [comment]
奥奥 好的 谢谢～

**Comment by cg3s** [comment]
不客气，这种问题一般请先关注下节点列表页面，节点列表只要一片绿，并且人数不为0，就都是正常的，而你所连的节点如果没在节点列表里，就很可能是流量用完自动下线了，等流量重置日就会自动上线。
