### ISSUE TITLE
请教:v2ray服务因为系统时间滞后且无法更改，现在还能否使用ssr服务

### ISSUE THREAD

**Issue by xtvjxk123456** [cg3s/forum#18]
如题，因为系统时间无法更改且延后了3-4分，想用以前的ssr,不知还能用不

**Comment by cg3s** [comment]
ssr已死，不会再提供ssr了

**Comment by xtvjxk123456** [comment]
了解了

**Comment by cg3s** [comment]
您好，我们部署了一个ssr节点，您可以过渡使用下，请选择香港A6使用。

**Comment by cg3s** [comment]
> 了解了

 您好，我们部署了一个ssr节点，您可以过渡使用下，请选择香港A6使用。
