### ISSUE TITLE
积分兑换邀请码无法使用的问题！

### ISSUE THREAD

**Issue by JaxonBjer** [cg3s/forum#180]
账号：zbxxx53@163.com

- 操作系统：Windows

-是否已更新节点列表：是

- [是] 是否已查看最新系统公告

- [是] 是否已查看常见问题列表

- [是] 是否已搜索已解决问题列表

### 问题描述：
为一位同行朋友分享邀请码。积分兑换一次邀请码后，邀请码列表没有更新，又尝试一次后依然没有更新。邀请码不显示，无法分享。

![image](https://user-images.githubusercontent.com/52449008/66702992-2d95e980-ed40-11e9-9601-88a5cc4f2f9b.png)

**Comment by cg3s** [comment]
账户等级过期了，自然不能查看，升级下就好了
我们看您已经升级了，所以这个issue可以关闭了。
