### ISSUE TITLE
每次使用完vpn 下次重启电脑网络会连接不上 需使用火绒的修复工具修复 说是ie代理错误

### ISSUE THREAD

**Issue by leixianya** [cg3s/forum#182]
每次使用完vpn 下次重启电脑网络会连接不上 需使用火绒的修复工具修复 说是ie代理错误 无法正常连接网站

**Comment by leixianya** [comment]
代理服务器没有响应

•检查你的代理设置127.0.0.1:1080。
转到“工具”>“Internet 选项”>“连接”。如果你在 LAN 中，请单击“局域网设置”。
•确保你的防火墙设置没有阻止 Web 访问。
•向你的系统管理员求助。

**Comment by cg3s** [comment]
您没有设置ssr开机自启动? 设置下开机自启动就好了.

**Comment by leixianya** [comment]
必须设置开机自启动吗

**Comment by cg3s** [comment]
如果不设置开机自启动的话,需要您在关机之前手动关闭ssr软件,下次开机系统代理就正常了.

**Comment by leixianya** [comment]
好的谢谢

**Comment by cg3s** [comment]
不客气
