### ISSUE TITLE
可以退款吗？

### ISSUE THREAD

**Issue by behonQ** [cg3s/forum#183]
## 提交问题请按照格式填写

- 账号：(后台可模糊查询，请打码处理，如12345678@qq.com可填写为123xxx78@qq.com)

- 操作系统：[Windows|Mac|Linux|iOS|Android|路由器]

- [x] 是否已更新节点列表 ```(是: 在[]内填 x, 否: 留空) ```

- [x] 是否已查看最新系统公告

- [x] 是否已查看常见问题列表

- [x] 是否已搜索已解决问题列表

**本问答为公开页面，为保护我们的服务安全和您的个人隐私，如截图中含有以下敏感信息，请马赛克处理。**
- 本站网址
- 本站节点的任何信息

### 问题描述：
十一假期后，每天无数次掉线上不了，使用体验十分不行，可以退款吗？

### 备注：
- [常见问题列表](https://github.com/cg3s/forum/wiki/)
- [已解决问题列表](https://github.com/cg3s/forum/issues?q=is%3Aissue+is%3Aclosed)
- 如想立即得到我们的回复，请在我们的工作时间内提交问题（工作日的10:00-17:00），大多数时候我们能保持快速响应，但不排除我们的工作人员在忙其他的事情，如果我们没有及时回应，请耐心等待。
- 如需上传截图，对敏感信息马赛克后拖拽或拷贝图片到本编辑器中即可。

**Comment by cg3s** [comment]
您账号多少，请提供微信二维码

**Comment by behonQ** [comment]
2498435934@qq.com
![8f7e6f1a76d505680233ab04063261c](https://user-images.githubusercontent.com/33080690/66795019-e3765900-ef35-11e9-872c-a766961f2604.jpg)

**Comment by behonQ** [comment]
是微信收款码吗？

**Comment by cg3s** [comment]
对的，退款会扣除您邀请人的返利金额以及平台的手续费用，请知晓。

**Comment by behonQ** [comment]
2498435934@qq.com
![TIM截图20191015102639](https://user-images.githubusercontent.com/33080690/66795167-5a135680-ef36-11e9-89e1-3b64f6fd417e.png)

**Comment by behonQ** [comment]
平台手续费是多少

**Comment by cg3s** [comment]
您的账户好像没什么可以退款的余额了，
您在8月6日充值70，使用了平台的返利购买了累计228元的服务，
首先平台返利作为福利是不能退款的，70元从8月6日到现在算2个月吧，按专业版季度费用60元算，您消费了40元，最后也就30元可退，这个30我们无所谓就全退给您吧。

**Comment by behonQ** [comment]
好

**Comment by behonQ** [comment]
本来用的好好的，现在掉线掉到影响工作了，实在没办法

**Comment by cg3s** [comment]
没事，国庆GFW发力，我们认为能提供服务就已经相当不错了（有其他平台全线挂掉的）

**Comment by cg3s** [comment]
已退款
