### ISSUE TITLE
节点不能用的，更新节点列表即可

### ISSUE THREAD

**Issue by cg3s** [cg3s/forum#185]
为解决节点负载过重导致频繁掉线的情况，我们已对节点进行重新分组，分组后部分用户必须更新节点列表才可正常使用，为此造成的不便敬请谅解。

更新节点列表之前请删除老的节点配置。

**ios更新节点列表方法：**
----
![image](https://user-images.githubusercontent.com/28707826/66882135-ca37e000-effb-11e9-998a-f82d9a863dea.png)
点击服务器订阅项，再点完成即可。如果此处更新不了节点列表，请重新设置订阅链接再更新节点。

**macOS更新节点列表方法：**
----
<img width="790" alt="Screen Shot 2019-10-16 at 9 35 29 AM" src="https://user-images.githubusercontent.com/28707826/66881254-e6864d80-eff8-11e9-89ea-4d55d1e7a764.png">
<img width="728" alt="image" src="https://user-images.githubusercontent.com/28707826/67257370-3a43db80-f4be-11e9-9636-511bda0a12a8.png">
<img width="788" alt="Screen Shot 2019-10-16 at 9 39 39 AM" src="https://user-images.githubusercontent.com/28707826/66881267-f1d97900-eff8-11e9-8413-57434b0caad6.png">

**windows更新节点列表方法：**
----
![image](https://user-images.githubusercontent.com/28707826/66881934-23534400-effb-11e9-947c-ff30c08fd2cf.png)

<img width="429" alt="image" src="https://user-images.githubusercontent.com/28707826/67257466-acb4bb80-f4be-11e9-8bb2-91344cca36a2.png">

![image](https://user-images.githubusercontent.com/28707826/66881980-4c73d480-effb-11e9-9748-8f69ac87f306.png)

注：删除节点，需保留至少一个节点

更新完成后，选择最新的可用节点使用。

**Comment by seradrin** [comment]
怎么删除老的例程配置？

**Comment by cg3s** [comment]
> 怎么删除老的例程配置？

看上面图片

**Comment by rcqcxy** [comment]
按照以上方法错操作以后上不了网了已经，不晓得咋个回事

**Comment by cg3s** [comment]
@rcqcxy 那就退出软件访问官网，按照官网里的教程重新走一遍

**Comment by rcqcxy** [comment]
还是没有成功，并且无法使用
------------------ 原始邮件 ------------------
发件人: "CGS小管家"<notifications@github.com>;
发送时间: 2019年10月16日(星期三) 下午4:51
收件人: "cg3s/forum"<forum@noreply.github.com>;
抄送: "小超超"<1605785546@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [cg3s/forum] 节点不能用的，更新节点列表即可 (#185)




@rcqcxy 那就退出软件访问官网，按照官网里的教程重新走一遍

**Comment by cg3s** [comment]
@rcqcxy 删除软件，重新配置一遍

**Comment by rcqcxy** [comment]
mac系统  我把软件删除了再重新走一遍试试呢




------------------ 原始邮件 ------------------
发件人: "CGS小管家"<notifications@github.com>;
发送时间: 2019年10月16日(星期三) 下午4:57
收件人: "cg3s/forum"<forum@noreply.github.com>;
抄送: "小超超"<1605785546@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [cg3s/forum] 节点不能用的，更新节点列表即可 (#185)




@rcqcxy 删除软件，重新配置一遍

**Comment by cg3s** [comment]
> mac系统 我把软件删除了再重新走一遍试试呢

你没选节点吧

**Comment by rcqcxy** [comment]
选了的的，但是用不了
------------------ 原始邮件 ------------------
发件人: "CGS小管家"<notifications@github.com>;
发送时间: 2019年10月16日(星期三) 下午5:03
收件人: "cg3s/forum"<forum@noreply.github.com>;
抄送: "小超超"<1605785546@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [cg3s/forum] 节点不能用的，更新节点列表即可 (#185)



 
mac系统 我把软件删除了再重新走一遍试试呢
  
你没选节点吧

**Comment by cg3s** [comment]
> 选了的的，但是用不了

请严格按照教程走一遍，不行请查看 https://github.com/cg3s/forum/wiki/常见问题列表#1-外网连不上了

**Comment by rcqcxy** [comment]
重新走了一遍可以了




------------------ 原始邮件 ------------------
发件人: "CGS小管家"<notifications@github.com>;
发送时间: 2019年10月16日(星期三) 下午5:09
收件人: "cg3s/forum"<forum@noreply.github.com>;
抄送: "小超超"<1605785546@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [cg3s/forum] 节点不能用的，更新节点列表即可 (#185)



 
选了的的，但是用不了
  
请严格按照教程走一遍，不行请查看 https://github.com/cg3s/forum/wiki/常见问题列表#1-外网连不上了

**Comment by cg3s** [comment]
> 重新走了一遍可以了

ok
