### ISSUE TITLE
iPhone XsMax 升级IOS 13.1.2 后无法使用

### ISSUE THREAD

**Issue by danXwang** [cg3s/forum#186]
## 提交问题请按照格式填写

- 账号:ninexxxxxyy@yahoo.com)

- 操作系统：iOS
- [X] 是否已更新节点列表 ```(是: 在[]内填 x, 否: 留空) ```

- [X] 是否已查看最新系统公告

- [X] 是否已查看常见问题列表

- [X] 是否已搜索已解决问题列表

**本问答为公开页面，为保护我们的服务安全和您的个人隐私，如截图中含有以下敏感信息，请马赛克处理。**
- 本站网址
- 本站节点的任何信息

### 问题描述：
iPhone XsMAX, iOS 13.1.2,按照新的公告更新了所有的站点，而且可以成功的ping 所有的站点，VPN可以链接成功，但是始终无法通过VPN上到youtube等网站。我同时拥有iPhone 7 plus， iOS是 12.3.1， 一台Mac，一台win laptop，还有一部华为 Mate 10pro，这四个都可以使用。对比iPhone 7，iPhone Xs Max所有的setting is identical。

其实从一开始我的iPhone Xs Max 就无法使用VPN，当时iOS就是13.x.x

### 备注：
- [常见问题列表](https://github.com/cg3s/forum/wiki/)
- [已解决问题列表](https://github.com/cg3s/forum/issues?q=is%3Aissue+is%3Aclosed)
- 如想立即得到我们的回复，请在我们的工作时间内提交问题（工作日的10:00-17:00）
- 如需上传截图，对敏感信息马赛克后拖拽或拷贝图片到本编辑器中即可。

**Comment by cg3s** [comment]
我们也拿设备升级了13.1.2 只是出现了订阅不刷新节点的问题，但软件使用时没问题的。

**Comment by cg3s** [comment]
我们测试过程中出现订阅连接下载的txt文件大小为0的情况,造成节点刷新不正常,然后我们重新设置订阅链接,就没问题了,具体原因还不清楚

您可以在ios客户端重新设置下订阅连接,或者到节点设置页面重置订阅连接后再设置.
