### ISSUE TITLE
SSR 设置开机启动 提示无法修改注册表

### ISSUE THREAD

**Issue by yutingdd** [cg3s/forum#187]
![IST{$~5~NVCI39(QD}CODWA](https://user-images.githubusercontent.com/52329255/67021695-9a3f2880-f132-11e9-82e1-06c3ce7128c7.png)

**Comment by yutingdd** [comment]
![%12`1XD6(3QQN}Q@BFCKBLL](https://user-images.githubusercontent.com/52329255/67022417-c7d8a180-f133-11e9-8db5-59b0a1298772.png)

**Comment by cg3s** [comment]
是否安装了金山毒霸?

如果是金山毒霸问题，进去设置中心->安全防护->信任设置里面，把shadowsocksr.exe添加上就可以了
