### ISSUE TITLE
没法用

### ISSUE THREAD

**Issue by juzi-eyr** [cg3s/forum#188]
## 提交问题请按照格式填写

- 账号：(后台可模糊查询，请打码处理，如12345678@qq.com可填写为123xxx78@qq.com)
131xxx73@qq.com
- 操作系统：[Windows|Mac|Linux|iOS|Android|路由器]
windows
- [] 是否已更新节点列表 ```(是: 在[]内填 x, 否: 留空) ```
是
- [] 是否已查看最新系统公告
是
- [] 是否已查看常见问题列表
是
- [] 是否已搜索已解决问题列表
是
**本问答为公开页面，为保护我们的服务安全和您的个人隐私，如截图中含有以下敏感信息，请马赛克处理。**
- 本站网址
- 本站节点的任何信息

### 问题描述：
ios端使用正常
win端按步骤删了旧的之后，重新按 使用 里的步骤改了ssr服务器订阅，然后用（不通过代理）更新完，那个列表里显示限速账号？然后就无法连p站。也没找到问限速的问题

### 备注：
- [常见问题列表](https://github.com/cg3s/forum/wiki/)
- [已解决问题列表](https://github.com/cg3s/forum/issues?q=is%3Aissue+is%3Aclosed)
- 如想立即得到我们的回复，请在我们的工作时间内提交问题（工作日的10:00-17:00）
- 如需上传截图，对敏感信息马赛克后拖拽或拷贝图片到本编辑器中即可。

**Comment by cg3s** [comment]
您账户是多少，节点列表不会有什么限速之类的东西。

**Comment by juzi-eyr** [comment]
1318672273@qq.com







------------------ 原始邮件 ------------------
发件人: "CGS小管家"<notifications@github.com>; 
发送时间: 2019年10月22日(星期二) 上午10:26
收件人: "cg3s/forum"<forum@noreply.github.com>; 
抄送: "名晴"<1318672273@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [cg3s/forum] 没法用 (#188)




您账户是多少，节点列表不会有什么限速之类的东西。

**Comment by cg3s** [comment]
账户没什么问题，您选了合适的节点？

**Comment by juzi-eyr** [comment]
那个节点里显示的都是什么限速账号，半限速账号。选哪个都无法上p站。我这边不知道怎么发图片

**Comment by cg3s** [comment]
如需上传截图，对敏感信息马赛克后拖拽或拷贝图片到本编辑器中即可。

**Comment by juzi-eyr** [comment]
![Snipaste_2019-10-22_10-27-19](https://user-images.githubusercontent.com/56854816/67256031-9a834f00-f4b7-11e9-832c-d9f4c627e7a4.png)

**Comment by cg3s** [comment]
这是根本就不是我们网站的东西，您正确设置了订阅链接么，请严格按照教程操作。

**Comment by juzi-eyr** [comment]
？我第一次没成功还重新下了一遍。然后按那个使用里的步骤做了一遍，就出现的是这个

**Comment by cg3s** [comment]
方便的话，您发个向日葵识别码过来吧，我们远程您看下

**Comment by juzi-eyr** [comment]
426 583 937
是这个嘛？
![Snipaste_2019-10-22_10-46-15](https://user-images.githubusercontent.com/56854816/67256375-3e212f00-f4b9-11e9-9e1f-aacc919224e5.png)

**Comment by juzi-eyr** [comment]
ok，好了谢谢

**Comment by cg3s** [comment]
订阅链接设置不正常，且没有正确更新节点列表。
