### ISSUE TITLE
参照本站的教程，Linux下还是不太会配置。

### ISSUE THREAD

**Issue by SimonHe96** [cg3s/forum#189]
- 账号： 
```1893xxxx659@163.com```

- 操作系统：[Linux Centos7.7] 

- [x] 是否已更新节点列表 

- [x] 是否已查看最新系统公告

- [x] 是否已查看常见问题列表

- [x] 是否已搜索已解决问题列表

### 问题描述：
你好，Linux下不太会配置，参照本站的[教程](https://cgsss.net/help/?/article/14)

**Comment by SimonHe96** [comment]
向日葵帐号：k672257326

**Comment by cg3s** [comment]
我们回头更新一篇centos教程吧，大体上和ubuntu是一样的

ps: 这个我们不会无偿提供技术支持，一般来说使用linux的用户，我们假设对方已经具备基本的系统设置能力。

**Comment by SimonHe96** [comment]
好的

**Comment by SimonHe96** [comment]
搞好了。教程里3.2章节，导入备份的链接失效了。
