### ISSUE TITLE
用电视盒子播放netflix显示使用代理，不是支持netflix的么？

### ISSUE THREAD

**Issue by lyrabird** [cg3s/forum#190]
用电视盒子播放netflix显示使用代理，不是支持netflix的么？

**Comment by cg3s** [comment]
请选择带S(流媒体)的节点

**Comment by lyrabird** [comment]
但是我选择了+S依然播放不了，只有+P的可以播放，但是+p只有一个节点，有时这个节点会连不上。

**Comment by cg3s** [comment]
这两天四中全会，节点会频繁波动，其他机场也是哀嚎一片。

**Comment by cg3s** [comment]
A6+P已经被和谐了，需要替换节点。

**Comment by lyrabird** [comment]
我比较疑惑的是，+S为什么在电视盒上不能使用



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: CGS小管家 <notifications@github.com&gt;
发送时间: 2019年10月30日 08:50
收件人: cg3s/forum <forum@noreply.github.com&gt;
抄送: lyrabird <icu007@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[cg3s/forum] 用电视盒子播放netflix显示使用代理，不是支持netflix的么？ (#190)




A6+P已经被和谐了，需要替换节点。

**Comment by cg3s** [comment]
香港A4+S 前两天换了节点,没有同步netflix解锁,但新加坡是ok的
