### ISSUE TITLE
为啥我申请的 福利 不给通过啊

### ISSUE THREAD

**Issue by yongqing-wei** [cg3s/forum#191]
为啥我申请的 福利 不给通过啊

### 提交前的必要步骤
```(是: 在[]内填 x, 否: 留空) ```

- [] 是否已更新节点列表 

- [] 是否已查看最新系统公告

- [] 是否已查看常见问题列表

- [] 是否已搜索已解决问题列表

**本问答为公开页面，为保护我们的服务安全和您的个人隐私，如截图中含有以下敏感信息，请马赛克处理。**
- 本站网址
- 本站节点的任何信息

### 问题描述：

为啥我申请的 福利 不给通过啊

### 备注：
- [常见问题列表](https://github.com/cg3s/forum/wiki/)
- [已解决问题列表](https://github.com/cg3s/forum/issues?q=is%3Aissue+is%3Aclosed)
- 如想立即得到我们的回复，请在我们的工作时间内提交问题（工作日的10:00-17:00），大多数时候我们能保持快速响应，但不排除我们的工作人员在忙其他的事情，如果我们没有及时回应，请耐心等待。
- 如需上传截图，对敏感信息马赛克后拖拽或拷贝图片到本编辑器中即可。

**Comment by cg3s** [comment]
盗版还有理由么?
![image](https://user-images.githubusercontent.com/28707826/67358972-91b47b00-f594-11e9-88a4-dc60694fc8e6.png)

附正版链接: https://www.unrealengine.com/marketplace/en-US/slug/modular-urban-city-asset-megapack

如果您申请购买的盗版资源的作者是我们平台的用户, 作为作者你作何感受, 同时如果淘宝商家也把自己的盗版商品拿来本站申请福利购买, 我们怎么避免?

**Comment by yongqing-wei** [comment]
666  说的对  我说怎么没成功
