### ISSUE TITLE
节点频繁断连

### ISSUE THREAD

**Issue by JeanLim** [cg3s/forum#192]
- 账号： 
```linzhe***69@gmail.com```

- 操作系统：[Windows] 

- [x] 是否已更新节点列表 

- [x] 是否已查看最新系统公告

- [x] 是否已查看常见问题列表

- [x] 是否已搜索已解决问题列表

 问题描述：这今天更新完节点后，开始出现使用某个节点正常链接后，大概1-5分钟以内该节点遍无法链接上youtube或者google，尝试切换其他节点后，同样在1-5分钟内该节点断连。最后又尝试了一下在节点A断连后，切换到节点B，再立刻切换为节点A后又能链接，但是一样是1-5分钟内断连。SSR软件也已经重新更新了，一样出现这个情况。

**Comment by cg3s** [comment]
谢谢反馈，我们正在测试

**Comment by cg3s** [comment]
测试香港A4 A9均无此现象

**Comment by JeanLim** [comment]
> 
> 
> windows下测试香港A4 A9均无此现象

试了下A4 和A9，又没问题了。。有点诡异。我后续在观察一下。。谢谢哈。

**Comment by cg3s** [comment]
不客气，是不是公司有迅雷下载之类的情况呢
