### ISSUE TITLE
使用问题

### ISSUE THREAD

**Issue by hiraeh** [cg3s/forum#196]
## 提交问题请按照格式填写

- 账号：1191****42@qq.com(后台可模糊查询，请打码处理，如12345678@qq.com可填写为123xxx78@qq.com)

- 操作系统：[Windows|Android|路由器]

- [x] 是否已更新节点列表 ```(是: 在[]内填 x, 否: 留空) ```

- [x] 是否已查看最新系统公告

- [x] 是否已查看常见问题列表

- [x] 是否已搜索已解决问题列表

**本问答为公开页面，为保护我们的服务安全和您的个人隐私，如截图中含有以下敏感信息，请马赛克处理。**
- 本站网址
- 本站节点的任何信息

### 备注：
- [常见问题列表](https://github.com/cg3s/forum/wiki/)
- [已解决问题列表](https://github.com/cg3s/forum/issues?q=is%3Aissue+is%3Aclosed)
- 如想立即得到我们的回复，请在我们的工作时间内提交问题（工作日的10:00-17:00）
- 如需上传截图，对敏感信息马赛克后拖拽或拷贝图片到本编辑器中即可。

**Comment by cg3s** [comment]
已重置，您上个月的流量是用得差不多了么

**Comment by hiraeh** [comment]
并没有，大概只用了不到200G，套餐是有500的，并且很疑惑的一点是，当时还剩300多，在我续费之后瞬间只有几个g左右，当时也还没到新套餐生效

**Comment by cg3s** [comment]
那就对了，因为您升级的套餐流量为200G，但您已经用超了，就自然没啥流量了

**Comment by hiraeh** [comment]
好吧，明白了，就是到生效时间流量没有重置有点奇怪，谢谢啊

**Comment by cg3s** [comment]
抱歉，那个流量重置日还有一点点问题，我们还没有完全修正，有时候会有跟实际重置时间会有半天的差距
我们近期再看看数据进行修复。

不客气的
