### ISSUE TITLE
使用无线网络不管是电脑还是手机都翻不了墙 能正常上国内网

### ISSUE THREAD

**Issue by 6yun** [cg3s/forum#197]
## 提交问题请按照格式填写
```因不严格按照格式填写，不严格按照教程操作导致的问题，可能不会得到我们及时的处理。```

- 账号： 11710xxx00@qq.com
```如12345678@qq.com可填写为123xxx78@qq.com```

- 操作系统：Windows
```保留一项即可```

### 提交前的必要步骤
```(是: 在[]内填 x, 否: 留空) ```

- [x] 是否已更新节点列表 

- [x] 是否已查看最新系统公告

- [x] 是否已查看常见问题列表

- [x] 是否已搜索已解决问题列表

**本问答为公开页面，为保护我们的服务安全和您的个人隐私，如截图中含有以下敏感信息，请马赛克处理。**
- 本站网址
- 本站节点的任何信息

### 问题描述：
使用无线网络不管是电脑还是手机都翻不了墙 能正常上国内网
软件新下的节点更新了  
网页显示无法访问此网站
请问是设置问题吗？请求帮助谢谢

### 备注：
- [常见问题列表](https://github.com/cg3s/forum/wiki/)
- [已解决问题列表](https://github.com/cg3s/forum/issues?q=is%3Aissue+is%3Aclosed)
- 如想立即得到我们的回复，请在我们的工作时间内提交问题（工作日的10:00-17:00），大多数时候我们能保持快速响应，但不排除我们的工作人员在忙其他的事情，如果我们没有及时回应，请耐心等待。
- 如需上传截图，对敏感信息马赛克后拖拽或拷贝图片到本编辑器中即可。

**Comment by cg3s** [comment]
所有节点都试了么

**Comment by cg3s** [comment]
这两天四中全会，节点会频繁波动，其他友商也是哀嚎一片。差不多每天要频繁挂一次节点。

**Comment by cg3s** [comment]
您可以发个向日葵识别码过来，方便的话我们远程您看看，目测可能您的使用姿势不对

**Comment by 6yun** [comment]
> 您可以发个向日葵识别码过来，方便的话我们远程您看看，目测可能您的使用姿势不对

请问向日葵识别码在哪？

**Comment by cg3s** [comment]
百度 向日葵远程
