### ISSUE TITLE
流量使用问题

### ISSUE THREAD

**Issue by ohyawen** [cg3s/forum#198]
- 账号：3295252X8@qq.com

- 操作系统：Windows

- [x] 是否已更新节点列表

- [x] 是否已查看最新系统公告

- [x] 是否已查看常见问题列表

- [x] 是否已搜索已解决问题列表

**本问答为公开页面，为保护我们的服务安全和您的个人隐私，如截图中含有以下敏感信息，请马赛克处理。**
- 本站网址
- 本站节点的任何信息

### 问题描述：

您好，前几天我将自己的套餐从 专业版 升级到 套装版，流量从200G升级到了500G。

但是在“流量使用情况”中显示，目前已使用14.6GB （94.6%）, 并只剩余几百兆。我的500G去哪里了？而且流量重置日一直在往后推，现在推到了11月24日。我只有靠流量兑换来使用。

请问我购买的流量都去哪了? 请帮忙解决，谢谢。  

### 备注：
- [常见问题列表](https://github.com/cg3s/forum/wiki/)
- [已解决问题列表](https://github.com/cg3s/forum/issues?q=is%3Aissue+is%3Aclosed)
- 如想立即得到我们的回复，请在我们的工作时间内提交问题（工作日的10:00-17:00）
- 如需上传截图，对敏感信息马赛克后拖拽或拷贝图片到本编辑器中即可。

**Comment by cg3s** [comment]
抱歉,  流量重置可能有点bug, 流量已调整

**Comment by ohyawen** [comment]
谢谢！

还想请问一下为什么Vimeo上的视频看不了呢？我换了两个浏览器都不行，页面出来了，就是视频不出来。但是在youtube上看视频就很轻松。

**Comment by ohyawen** [comment]
你好，向日葵识别码是：326 879 609

**Comment by ohyawen** [comment]
验证码：Dp3boo

**Comment by cg3s** [comment]
这个问题没必要远程,请用全局模式试试

**Comment by ohyawen** [comment]
我选择的就是global模式哦

**Comment by ohyawen** [comment]
Proxy rule 里我选择的是 bypass LAN, 不知道是不是全局？

**Comment by ohyawen** [comment]
谢谢，比刚才的情况好多了，有一些视频可以看，但有一些视频还是播放不了，感觉很随机。

**Comment by cg3s** [comment]
你开了节点负载均衡吧,关掉 选个适合的节点就好了

**Comment by cg3s** [comment]
另外 长期使用代理规则请选第二项, 临时可选全局,不然你的流量会分分钟用完

**Comment by ohyawen** [comment]
请问在哪里关节点负载均衡？英文是什么？（我的软件是英文版的....）

**Comment by ohyawen** [comment]
比如这个视频就播放不了：https://vimeo.com/361443943

**Comment by ohyawen** [comment]
这个视频有那么一下可以播放却没有画面

**Comment by ohyawen** [comment]
那您觉得还会有什么问题的可能性呀？我用两个浏览器都是这个情况，其他视频都是秒开，但就个别几个不行，很奇怪....

**Comment by cg3s** [comment]
1. 新建一个系统账户 切过去试试
2. 换电脑
3. 手机上试试, 如正常 则电脑有问题

**Comment by ohyawen** [comment]
好的！新建一个系统账户, 是指windows的系统user吗？

**Comment by cg3s** [comment]
对的
