### ISSUE TITLE
被vimeo,instagram屏蔽

### ISSUE THREAD

**Issue by bbrcnx** [cg3s/forum#199]
## 提交问题请按照格式填写
```因不严格按照格式填写，不严格按照教程操作导致的问题，可能不会得到我们及时的处理。```

- 账号： 
```bb***x@gmail.com```

- 操作系统：[Windows|Android|] 

### 提交前的必要步骤
```(是: 在[]内填 x, 否: 留空) ```

- [x] 是否已更新节点列表 

- [x] 是否已查看最新系统公告

- [x] 是否已查看常见问题列表

- [x] 是否已搜索已解决问题列表

**本问答为公开页面，为保护我们的服务安全和您的个人隐私，如截图中含有以下敏感信息，请马赛克处理。**
- 本站网址
- 本站节点的任何信息

### 问题描述：
被Instagram识别成机器人。vimeo也经常被屏蔽，负载均衡已经关了。看见别人也有这些情况有没有根本解决办法？

![image](https://user-images.githubusercontent.com/22326784/68011805-3e90a580-fcc3-11e9-8a1a-f39b7f17d08c.png)

### 备注：
- [常见问题列表](https://github.com/cg3s/forum/wiki/)
- [已解决问题列表](https://github.com/cg3s/forum/issues?q=is%3Aissue+is%3Aclosed)
- 如想立即得到我们的回复，请在我们的工作时间内提交问题（工作日的10:00-17:00），大多数时候我们能保持快速响应，但不排除我们的工作人员在忙其他的事情，如果我们没有及时回应，请耐心等待。
- 如需上传截图，对敏感信息马赛克后拖拽或拷贝图片到本编辑器中即可。

**Comment by cg3s** [comment]
<img width="1067" alt="image" src="https://user-images.githubusercontent.com/28707826/68015559-608f2580-fccd-11e9-9af7-0da466ee5521.png">
<img width="1067" alt="image" src="https://user-images.githubusercontent.com/28707826/68015590-6c7ae780-fccd-11e9-976f-9a6d5abb0587.png">
应该只是个别情况，我们也经常用vimeo的
