### ISSUE TITLE
为什么我用手机用的节点电脑加载很慢

### ISSUE THREAD

**Issue by 0GnoK** [cg3s/forum#20]
- 账户邮箱（必填）：1560xxx6202@163.com
```请马赛克处理，如123456789@qq.com改成12xxx789@qq.com``` 

- 操作系统：Windows|iOS

- [是] 是否已更新节点列表 

- [是] 是否已查看最新系统公告

- [是] 是否已查看常见问题列表

- [是] 是否已搜索已解决问题列表

### 问题描述：
问一下这俩天windows上不去pixiv了，所有节点都试了，youtobe没问题，ios没事，同一时间同一节点也不行，加载不出来图片是什么原因呢？有没有什么解决方法呀？

**Comment by cg3s** [comment]
代理规则没用完全识别到pixiv的域名，用全局模式就行，教程里有写，请看教程

**Comment by 0GnoK** [comment]
好的谢谢~

**Comment by cg3s** [comment]
不客气
