### ISSUE TITLE
服务器还没更新吗？最近这几天都用不了，想知道现在是什么情况。

### ISSUE THREAD

**Issue by smy2019** [cg3s/forum#200]
## 提交问题请按照格式填写
```因不严格按照格式填写，不严格按照教程操作导致的问题，可能不会得到我们及时的处理。```

- 账号： 
```如12345678@qq.com可填写为123xxx78@qq.com```

- 操作系统：[Windows|Mac|Linux|iOS|Android|路由器] 
```保留一项即可```

### 提交前的必要步骤
```(是: 在[]内填 x, 否: 留空) ```

- [] 是否已更新节点列表 

- [] 是否已查看最新系统公告

- [] 是否已查看常见问题列表

- [] 是否已搜索已解决问题列表

**本问答为公开页面，为保护我们的服务安全和您的个人隐私，如截图中含有以下敏感信息，请马赛克处理。**
- 本站网址
- 本站节点的任何信息

### 备注：
- [常见问题列表](https://github.com/cg3s/forum/wiki/)
- [已解决问题列表](https://github.com/cg3s/forum/issues?q=is%3Aissue+is%3Aclosed)
- 如想立即得到我们的回复，请在我们的工作时间内提交问题（工作日的10:00-17:00），大多数时候我们能保持快速响应，但不排除我们的工作人员在忙其他的事情，如果我们没有及时回应，请耐心等待。
- 如需上传截图，对敏感信息马赛克后拖拽或拷贝图片到本编辑器中即可。

**Comment by cg3s** [comment]
今天更新了日区节点，新加坡香港会在近几天完成全面更新升级，另外目前在线的新加坡香港都是能用的，从目前每天平台的流量使用情况看，大多数人都是正常的。

**Comment by smy2019** [comment]
那我这个怎么还是用不了，想请您帮我解决一下

**Comment by cg3s** [comment]
您发个向日葵识别码

**Comment by smy2019** [comment]
370508968

**Comment by cg3s** [comment]
你账户应该今天晚上会重置流量，到时候就能用了

**Comment by smy2019** [comment]
用积分兑换了 现在好了 哈哈哈哈

**Comment by smy2019** [comment]
没想到用完了

**Comment by cg3s** [comment]
👌
