### ISSUE TITLE
昨天续费了 流量没重置

### ISSUE THREAD

**Issue by Michiru-001** [cg3s/forum#201]
## 提交问题请按照格式填写

- 账号：275xxxx39@qq.com

- 操作系统：[Windows|Mac|Linux|iOS|Android|路由器]

- [x] 是否已更新节点列表 ```(是: 在[]内填 x, 否: 留空) ```

- [x] 是否已查看最新系统公告

- [x] 是否已查看常见问题列表

- [x] 是否已搜索已解决问题列表

**本问答为公开页面，为保护我们的服务安全和您的个人隐私，如截图中含有以下敏感信息，请马赛克处理。**
- 本站网址
- 本站节点的任何信息

### 问题描述：
昨天续费了 今天流量没重置 我原来那个旧了 就是你们之前公告取消那个昨天最后一天 然后 我去续费 那里没有续费按钮 要升级到了新那个 然后我升级之后 再续费了一个季度 今天应该按新的计算 但我在用户中心那里没有流量
![TIM图片20191104172154](https://user-images.githubusercontent.com/57345500/68107385-0ccc4880-ff28-11e9-8329-9085d59d7c8f.png)

### 备注：
- [常见问题列表](https://github.com/cg3s/forum/wiki/)
- [已解决问题列表](https://github.com/cg3s/forum/issues?q=is%3Aissue+is%3Aclosed)
- 如想立即得到我们的回复，请在我们的工作时间内提交问题（工作日的10:00-17:00）
- 如需上传截图，对敏感信息马赛克后拖拽或拷贝图片到本编辑器中即可。

**Comment by Michiru-001** [comment]
![TIM图片20191104172154](https://user-images.githubusercontent.com/57345500/68107299-b7903700-ff27-11e9-93a6-026d4406d671.png)

**Comment by cg3s** [comment]
已重置，不过后台记录11月3日您的账户已经重置过流量为500G

**Comment by cg3s** [comment]
知道原因了，续期的计算公式目前有点问题，我们将尽快修复，避免下次出现同样情况。
