### ISSUE TITLE
关于流媒体观看

### ISSUE THREAD

**Issue by AccJtsd** [cg3s/forum#202]
我在翻墙的时候,网飞一直提示串流错误,您似乎在使用解锁器,这个如何解决

**Comment by cg3s** [comment]
![image](https://user-images.githubusercontent.com/28707826/68117710-0c887900-ff39-11e9-8453-3d611963bc17.png)

**Comment by AccJtsd** [comment]
我按照上面用的S+节点,可是还是提示我使用解锁器(电脑客户端)

**Comment by cg3s** [comment]
请关掉节点负载均衡

**Comment by AccJtsd** [comment]
好的 已经解决 谢谢您~服务器负载均衡一般什么时候打开?

**Comment by cg3s** [comment]
负载均衡会根据设置的参数动态切换节点,造成ip变动, 自然你就不能一直保持使用+S节点,当您访问网络不需要固定ip的时候开启就行. 我们一般不开负载均衡, 负载均衡适合新手用户,对ip之类的没概念的人

**Comment by AccJtsd** [comment]
好的,这样我就知道了~谢谢您
