### ISSUE TITLE
账号等级已经过期是什么意思，11月2号在交费充值的是一年基础套餐

### ISSUE THREAD

**Issue by chenjl1** [cg3s/forum#203]
## 提交问题请按照格式填写
```因不严格按照格式填写，不严格按照教程操作导致的问题，可能不会得到我们及时的处理。```

- 账号： 
```如12345678@qq.com可填写为123xxx78@qq.com```

- 操作系统：[Windows|Mac|Linux|iOS|Android|路由器] 
```保留一项即可```

### 提交前的必要步骤
```(是: 在[]内填 x, 否: 留空) ```

- [] 是否已更新节点列表 

- [] 是否已查看最新系统公告

- [] 是否已查看常见问题列表

- [] 是否已搜索已解决问题列表

**本问答为公开页面，为保护我们的服务安全和您的个人隐私，如截图中含有以下敏感信息，请马赛克处理。**
- 本站网址
- 本站节点的任何信息

### 备注：
- [常见问题列表](https://github.com/cg3s/forum/wiki/常见问题列表)
- [已解决问题列表](https://github.com/cg3s/forum/issues?q=is%3Aissue+is%3Aclosed)
- 如想立即得到我们的回复，请在我们的工作时间内提交问题（工作日的10:00-17:00），大多数时候我们能保持快速响应，但不排除我们的工作人员在忙其他的事情，如果我们没有及时回应，请耐心等待。
- 如需上传截图，对敏感信息马赛克后拖拽或拷贝图片到本编辑器中即可。

**Comment by chenjl1** [comment]
账号等级已经过期是什么意思，11月2号在交费充值的是一年基础套餐

**Comment by cg3s** [comment]
账户多少

**Comment by chenjl1** [comment]
234417103@qq.com,请帮忙查看一下，谢谢

**Comment by cg3s** [comment]
你购买下套餐就行了, 你之前只是充了值,但没购买套餐.

**Comment by chenjl1** [comment]
之前购买，你们发到我邮箱的卡密，现在点充值，提示只充值码错误，是什么情况呢

**Comment by cg3s** [comment]
你直接去商店页面购买套餐就行了,卡密已经用过了,当然会错误了.



套餐购买流程
本站采用先充值后购买的方式，完成套餐购买需要如下三步：
购买卡密（第三方平台）
充值（使用第一步购买的卡密）
购买套餐 （商店页面）
