### ISSUE TITLE
写下您的问题概述

### ISSUE THREAD

**Issue by lsiiounm** [cg3s/forum#204]
## 提交问题请按照格式填写
```因不严格按照格式填写，不严格按照教程操作导致的问题，可能不会得到我们及时的处理。```

- 账号： 
```1036xxx290@qq.com```

- 操作系统：[Mac] 
```保留一项即可```

### 提交前的必要步骤
```(是: 在[]内填 x, 否: 留空) ```

- [x] 是否已更新节点列表 

- [x] 是否已查看最新系统公告

- [x] 是否已查看常见问题列表

- [x] 是否已搜索已解决问题列表

**本问答为公开页面，为保护我们的服务安全和您的个人隐私，如截图中含有以下敏感信息，请马赛克处理。**
- 本站网址
- 本站节点的任何信息

### 问题描述：
就是用不了外网，
端口换了一下再换回来的一瞬间可以用，用了几秒又不能用了，不知道为什么

### 备注：
- [常见问题列表](https://github.com/cg3s/forum/wiki/常见问题列表)
- [已解决问题列表](https://github.com/cg3s/forum/issues?q=is%3Aissue+is%3Aclosed)
- 如想立即得到我们的回复，请在我们的工作时间内提交问题（工作日的10:00-17:00），大多数时候我们能保持快速响应，但不排除我们的工作人员在忙其他的事情，如果我们没有及时回应，请耐心等待。
- 如需上传截图，对敏感信息马赛克后拖拽或拷贝图片到本编辑器中即可。

**Comment by cg3s** [comment]
换个浏览器试试，chrome的话进入访客模式看看

**Comment by lsiiounm** [comment]
试了，不行，这两天突然用不了了，之前都挺正常的


------------------ 原始邮件 ------------------
发件人: CGS小管家 <notifications@github.com&gt;
发送时间: 2019年11月14日 16:58
收件人: cg3s/forum <forum@noreply.github.com&gt;
抄送: lsiiounm <1036848290@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[cg3s/forum] 写下您的问题概述 (#204)




换个浏览器试试，chrome的话进入访客模式看看

**Comment by cg3s** [comment]
那您这两天电脑是否安装了什么东西

**Comment by cg3s** [comment]
您可以创建一个新的系统账户，切到新的系统账户里测试。

**Comment by lsiiounm** [comment]
这两天没装过东西呢


------------------ 原始邮件 ------------------
发件人: CGS小管家 <notifications@github.com&gt;
发送时间: 2019年11月14日 17:06
收件人: cg3s/forum <forum@noreply.github.com&gt;
抄送: lsiiounm <1036848290@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[cg3s/forum] 写下您的问题概述 (#204)




那您这两天电脑是否安装了什么东西

**Comment by cg3s** [comment]
<img width="668" alt="image" src="https://user-images.githubusercontent.com/28707826/68842694-c6ce6c00-0701-11ea-8942-10efd70cf132.png">
在这里建个新的系统账户试试吧。

**Comment by lsiiounm** [comment]
是不是你们vpn的问题呢，我和我同事都是买你们网站的，我和她都用不了


------------------ 原始邮件 ------------------
发件人: CGS小管家 <notifications@github.com&gt;
发送时间: 2019年11月14日 17:11
收件人: cg3s/forum <forum@noreply.github.com&gt;
抄送: lsiiounm <1036848290@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[cg3s/forum] 写下您的问题概述 (#204)





 在这里建个新的系统账户试试吧。

**Comment by cg3s** [comment]
我们的问题的话，这里就不会只是你一个人提问了。

**Comment by cg3s** [comment]
如果还不行，您发个向日葵识别码过来，方便的话，我们远程您看看

**Comment by lsiiounm** [comment]
你说的有道理，昨天晚上又能用了，不知道为什么，也什么都没去设置，不知道是不是公司的网络问题，总之麻烦了


------------------ 原始邮件 ------------------
发件人: CGS小管家 <notifications@github.com&gt;
发送时间: 2019年11月15日 10:26
收件人: cg3s/forum <forum@noreply.github.com&gt;
抄送: lsiiounm <1036848290@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[cg3s/forum] 写下您的问题概述 (#204)




如果还不行，您发个向日葵识别码过来，方便的话，我们远程您看看

**Comment by cg3s** [comment]
这种情况 请用手机4g网络测试，如果手机上正常，但电脑上不行，则肯定是电脑设置或者网络环境有问题

**Comment by lsiiounm** [comment]
好，谢谢～


------------------ 原始邮件 ------------------
发件人: CGS小管家 <notifications@github.com&gt;
发送时间: 2019年11月15日 11:16
收件人: cg3s/forum <forum@noreply.github.com&gt;
抄送: lsiiounm <1036848290@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[cg3s/forum] 写下您的问题概述 (#204)




这种情况 请用手机4g网络测试，如果手机上正常，但电脑上不行，则肯定是电脑设置或者网络环境有问题

**Comment by lsiiounm** [comment]
那个…又不能用了…这是为啥啊，就换了个端口换回来的一瞬间能用，手机上的也用不了，就晚上那会能用


------------------ 原始邮件 ------------------
发件人: CGS小管家 <notifications@github.com&gt;
发送时间: 2019年11月15日 11:16
收件人: cg3s/forum <forum@noreply.github.com&gt;
抄送: lsiiounm <1036848290@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[cg3s/forum] 写下您的问题概述 (#204)




这种情况 请用手机4g网络测试，如果手机上正常，但电脑上不行，则肯定是电脑设置或者网络环境有问题

**Comment by cg3s** [comment]
换端口？我们没有换端口这个操作。

**Comment by lsiiounm** [comment]
还有开机那一会也能用，但是其他同事在别的地方买的vpn都能用，就我另一个同事和我一样的，我们两个的vpn不能用


------------------ 原始邮件 ------------------
发件人: CGS小管家 <notifications@github.com&gt;
发送时间: 2019年11月15日 11:16
收件人: cg3s/forum <forum@noreply.github.com&gt;
抄送: lsiiounm <1036848290@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[cg3s/forum] 写下您的问题概述 (#204)




这种情况 请用手机4g网络测试，如果手机上正常，但电脑上不行，则肯定是电脑设置或者网络环境有问题

**Comment by lsiiounm** [comment]
节点


------------------ 原始邮件 ------------------
发件人: CGS小管家 <notifications@github.com&gt;
发送时间: 2019年11月15日 11:47
收件人: cg3s/forum <forum@noreply.github.com&gt;
抄送: lsiiounm <1036848290@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[cg3s/forum] 写下您的问题概述 (#204)




换端口？我们没有换端口这个操作。

**Comment by cg3s** [comment]
您发个向日葵识别码，我们远程您

**Comment by lsiiounm** [comment]
不是，就是换线，新加坡啊日本那些


------------------ 原始邮件 ------------------
发件人: CGS小管家 <notifications@github.com&gt;
发送时间: 2019年11月15日 11:47
收件人: cg3s/forum <forum@noreply.github.com&gt;
抄送: lsiiounm <1036848290@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[cg3s/forum] 写下您的问题概述 (#204)




换端口？我们没有换端口这个操作。

**Comment by cg3s** [comment]
您发个向日葵识别码，我们远程您

**Comment by lsiiounm** [comment]
577195343


------------------ 原始邮件 ------------------
发件人: CGS小管家 <notifications@github.com&gt;
发送时间: 2019年11月15日 12:23
收件人: cg3s/forum <forum@noreply.github.com&gt;
抄送: lsiiounm <1036848290@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[cg3s/forum] 写下您的问题概述 (#204)




您发个向日葵识别码，我们远程您

**Comment by cg3s** [comment]
切账户 远程会失效，还得你在test账户里登下向日葵

**Comment by lsiiounm** [comment]
ok，稍等


------------------ 原始邮件 ------------------
发件人: CGS小管家 <notifications@github.com&gt;
发送时间: 2019年11月15日 14:06
收件人: cg3s/forum <forum@noreply.github.com&gt;
抄送: lsiiounm <1036848290@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[cg3s/forum] 写下您的问题概述 (#204)

**Comment by cg3s** [comment]
ok了说一下

**Comment by lsiiounm** [comment]
我现在有工作要忙，晚些才远程可以不


------------------ 原始邮件 ------------------
发件人: CGS小管家 <notifications@github.com&gt;
发送时间: 2019年11月15日 14:12
收件人: cg3s/forum <forum@noreply.github.com&gt;
抄送: lsiiounm <1036848290@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[cg3s/forum] 写下您的问题概述 (#204)




ok了说一下

**Comment by cg3s** [comment]
ok, 正常情况下 test账户应该ok的，你可以自行测试

**Comment by lsiiounm** [comment]
好，我晚点测试了回复，谢谢哈，辛苦啦


------------------ 原始邮件 ------------------
发件人: CGS小管家 <notifications@github.com&gt;
发送时间: 2019年11月15日 14:21
收件人: cg3s/forum <forum@noreply.github.com&gt;
抄送: lsiiounm <1036848290@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[cg3s/forum] 写下您的问题概述 (#204)




ok, 正常情况下 test账户应该ok的，你可以自行测试

**Comment by cg3s** [comment]
我们给您用户调整下用户组吧，您会收到一封邮件，然后请更新节点列表。再试试是否ok.
更好用户组后，所有设备都需要重新设置节点。

**Comment by lsiiounm** [comment]
不可以呢，你现在方便远程我不呢


------------------ 原始邮件 ------------------
发件人: CGS小管家 <notifications@github.com&gt;
发送时间: 2019年11月15日 16:28
收件人: cg3s/forum <forum@noreply.github.com&gt;
抄送: lsiiounm <1036848290@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[cg3s/forum] 写下您的问题概述 (#204)




我们给您用户调整下用户组吧，您会收到一封邮件，然后请更新节点列表。再试试是否ok.
 更好用户组后，所有设备都需要重新设置节点。

**Comment by cg3s** [comment]
接一下向日葵

**Comment by cg3s** [comment]
你没选新的节点

**Comment by lsiiounm** [comment]
来，再来一次


------------------ 原始邮件 ------------------
发件人: CGS小管家 <notifications@github.com&gt;
发送时间: 2019年11月15日 16:56
收件人: cg3s/forum <forum@noreply.github.com&gt;
抄送: lsiiounm <1036848290@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[cg3s/forum] 写下您的问题概述 (#204)




你没选新的节点

**Comment by cg3s** [comment]
？ 不是好了么

**Comment by lsiiounm** [comment]
可以了！！！！！谢谢哇！！！！！


------------------ 原始邮件 ------------------
发件人: CGS小管家 <notifications@github.com&gt;
发送时间: 2019年11月15日 16:56
收件人: cg3s/forum <forum@noreply.github.com&gt;
抄送: lsiiounm <1036848290@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[cg3s/forum] 写下您的问题概述 (#204)




你没选新的节点

**Comment by lsiiounm** [comment]
对对对，谢谢了哈


------------------ 原始邮件 ------------------
发件人: CGS小管家 <notifications@github.com&gt;
发送时间: 2019年11月15日 17:02
收件人: cg3s/forum <forum@noreply.github.com&gt;
抄送: lsiiounm <1036848290@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[cg3s/forum] 写下您的问题概述 (#204)




？ 不是好了么

**Comment by lsiiounm** [comment]
又不行了😭


------------------ 原始邮件 ------------------
发件人: CGS小管家 <notifications@github.com&gt;
发送时间: 2019年11月15日 17:02
收件人: cg3s/forum <forum@noreply.github.com&gt;
抄送: lsiiounm <1036848290@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[cg3s/forum] 写下您的问题概述 (#204)




？ 不是好了么

**Comment by cg3s** [comment]
请详细查看 常见问题列表, 同样的问题我们不会再重复远程.

**Comment by lsiiounm** [comment]
问题是同样的问题没解决啊



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "CGS小管家"<notifications@github.com&gt;; 
发送时间: 2019年11月15日(星期五) 晚上6:24
收件人: "cg3s/forum"<forum@noreply.github.com&gt;; 
抄送: "罗思敏"<1036848290@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [cg3s/forum] 写下您的问题概述 (#204)




请详细查看 常见问题列表, 同样的问题我们不会再重复远程.

**Comment by lsiiounm** [comment]
我现在在家的电脑也上不了






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"CGS小管家"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月15日(星期五) 晚上6:24
收件人:&nbsp;"cg3s/forum"<forum@noreply.github.com&gt;;
抄送:&nbsp;"罗思敏"<1036848290@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [cg3s/forum] 写下您的问题概述 (#204)




请详细查看 常见问题列表, 同样的问题我们不会再重复远程.

**Comment by lsiiounm** [comment]
已解决，谢谢
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"CGS小管家"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月15日(星期五) 晚上6:24
收件人:&nbsp;"cg3s/forum"<forum@noreply.github.com&gt;;
抄送:&nbsp;"罗思敏"<1036848290@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [cg3s/forum] 写下您的问题概述 (#204)




请详细查看 常见问题列表, 同样的问题我们不会再重复远程.

**Comment by lsiiounm** [comment]
又用不了了，大兄弟，官网都上不了


------------------ 原始邮件 ------------------
发件人: CGS小管家 <notifications@github.com&gt;
发送时间: 2019年11月15日 18:24
收件人: cg3s/forum <forum@noreply.github.com&gt;
抄送: lsiiounm <1036848290@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[cg3s/forum] 写下您的问题概述 (#204)




请详细查看 常见问题列表, 同样的问题我们不会再重复远程.

**Comment by cg3s** [comment]
麻烦你多试下

**Comment by cg3s** [comment]
https://github.com/cg3s/forum/wiki/常见问题列表#2-官网访问不了
请细看常见问题列表第二项

**Comment by lsiiounm** [comment]
行


------------------ 原始邮件 ------------------
发件人: CGS小管家 <notifications@github.com&gt;
发送时间: 2019年11月20日 11:00
收件人: cg3s/forum <forum@noreply.github.com&gt;
抄送: lsiiounm <1036848290@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[cg3s/forum] 写下您的问题概述 (#204)




https://github.com/cg3s/forum/wiki/常见问题列表#2-官网访问不了
 请细看常见问题列表第二项
