### ISSUE TITLE
突然有一天启用小飞机后打开youtube很慢，而且有的网站打开很慢，有时甚至打不开

### ISSUE THREAD

**Issue by albert413** [cg3s/forum#205]
- 账号： 
chxxxbo@126.com

- 操作系统：Windows10

### 提交前的必要步骤
```(是: 在[]内填 x, 否: 留空) ```

- [x] 是否已更新节点列表 

- [x] 是否已查看最新系统公告

- [x] 是否已查看常见问题列表

- [x] 是否已搜索已解决问题列表

### 备注：
- [常见问题列表](https://github.com/cg3s/forum/wiki/常见问题列表)
- [已解决问题列表](https://github.com/cg3s/forum/issues?q=is%3Aissue+is%3Aclosed)
- 如想立即得到我们的回复，请在我们的工作时间内提交问题（工作日的10:00-17:00），大多数时候我们能保持快速响应，但不排除我们的工作人员在忙其他的事情，如果我们没有及时回应，请耐心等待。
- 如需上传截图，对敏感信息马赛克后拖拽或拷贝图片到本编辑器中即可。

**Comment by cg3s** [comment]
发个向日葵识别码过来,我们远程看看呢
目测跟我们关系不大.

**Comment by albert413** [comment]
teamviewer吗

**Comment by cg3s** [comment]
向日葵

**Comment by albert413** [comment]
960714365

**Comment by cg3s** [comment]
远程关掉负载均衡,并启用chrome访客模式访问,无异常

**Comment by albert413** [comment]
感谢，问题已解决
