### ISSUE TITLE
最近翻墙总是经常断然后就无法连接外网的情况

### ISSUE THREAD

**Issue by EricCenVFX** [cg3s/forum#208]
最近翻墙总是经常断然后就无法连接外网的情况，要换一个节点，然后又可以使用几分钟，然后又无法上完这样循环的情况，请问如何解决？

**Comment by cg3s** [comment]
邮箱多少, 什么平台, 是否使用节点负载均衡,没有用的话,是用的哪个节点?

**Comment by EricCenVFX** [comment]
哦，不好意思，格式我没细看，我下次会注意一下的
邮箱是 2372305043@qq.com
window10 平台
节点负载均衡 这个我勾选了
节点平时用开是香港A4那个
我现在的问题是，经常卡断，然后切换一下节点，再更新订阅服务器一下，就可以用几分钟，然后突然又卡断，这样的情况

**Comment by EricCenVFX** [comment]
方便加一下QQ聊吗

**Comment by cg3s** [comment]
怀疑可能是对方所在地区的网络环境 对443端口有干扰行为，导致A组节点使用不畅，切换到B组后表现正常。

如其他用户使用A组节点出现同样情况，可让我们后台更好节点组别。
