### ISSUE TITLE
关于2021.01.30调价表意见收集

### ISSUE THREAD

**Issue by cg3s** [cg3s/forum#21]
调价详情请见系统公告

此次征询日期截止到2021年3月1日，我们将于2021年3月1日确定是否按新的定价执行

**Comment by ypypjay** [comment]
个人觉得与其抬高价格不如减少流量，200g以现在cgray的专业版的速度来说用完还是挺难的

**Comment by cg3s** [comment]
@ypypjay 减少流量就跟旗舰版的差距太大了，比如150G反而梯度更不线性了，我们想流量价格的梯度尽量是45度爬坡，而不是J字曲线

**Comment by Saberjsd** [comment]
已包年订阅的部分不受影响吧？还有新用户有没有优惠卷？

**Comment by cg3s** [comment]
@Saberjsd 已订阅的过期后会按新的价格计算，新用户可通过邀请后被邀人的订阅金额获取返利。

**Comment by Saberjsd** [comment]
> @Saberjsd 已订阅的过期后会按新的价格计算，新用户可通过邀请后被邀人的订阅金额获取返利。

邀请返利是可提现的嘛？还是只能用于订阅？

**Comment by cg3s** [comment]
@Saberjsd 请看 文档/常见问题列表
