### ISSUE TITLE
从下午开始，无法使用，已经按照之前说的方式操作了，但是五个账号都无法使用

### ISSUE THREAD

**Issue by EricCenVFX** [cg3s/forum#213]
## 提交问题请按照格式填写

- 账号：237xxxx043@qq.com

- 操作系统：Window10

- [x] 是否已更新节点列表 ```(是: 在[]内填 x, 否: 留空) ```

- [x] 是否已查看最新系统公告

- [x] 是否已查看常见问题列表

- [x] 是否已搜索已解决问题列表

**本问答为公开页面，为保护我们的服务安全和您的个人隐私，如截图中含有以下敏感信息，请马赛克处理。**
- 本站网址
- 本站节点的任何信息

### 问题描述：
从下午开始，无法使用，已经按照之前说的方式操作了，但是五个账号都无法使用

### 备注：
- [常见问题列表](https://github.com/cg3s/forum/wiki/)
- [已解决问题列表](https://github.com/cg3s/forum/issues?q=is%3Aissue+is%3Aclosed)
- 如想立即得到我们的回复，请在我们的工作时间内提交问题（工作日的10:00-17:00）
- 如需上传截图，对敏感信息马赛克后拖拽或拷贝图片到本编辑器中即可。

**Comment by cg3s** [comment]
#214

**Comment by cg3s** [comment]
墙发力,我们将对日本节点进行维护

**Comment by EricCenVFX** [comment]
你好，你说的#214我打开没有东西的，然后所有节点我都试过了，但是还是不行，请问这个情况要持续到什么时候，我现在有哪些方法可以使用得到F. Q

**Comment by cg3s** [comment]
看公告，现在是gfw发力，今天和谐了一堆，明天还未知，目前我们已经更新维护了日区节点，其他节点全挂。

**Comment by cg3s** [comment]
请关注这个贴 https://github.com/cg3s/forum/issues/215
