### ISSUE TITLE
写下您的问题概述

### ISSUE THREAD

**Issue by CareyYang** [cg3s/forum#218]
- 操作系统：Android 华为9.1EMUI系统

- 问题描述：
我用我的华为P10手机使用浏览器访问YouTube，页面能够正常访问但是所有视频都不能够观看，试了好几个视频都这样，如下截图：
![image](https://user-images.githubusercontent.com/19970476/69509952-e40f0000-0f75-11ea-992f-632ae5927019.png)
请问是我哪里操作不对吗？用的是新加坡B3+S节点，切换其他节点也不行。

**Comment by cg3s** [comment]
感觉可能跟浏览器有关，能装chrome浏览器么，或者firefox

**Comment by cg3s** [comment]
你可以谷歌下这个问题，
https://www.google.com/search?newwindow=1&safe=active&sxsrf=ACYBGNSNgN2eY9UlAtIJKSy1spdZZ3MFGQ%3A1574654978238&ei=AlTbXZCaDqSF4-EPms6lyAE&q=youtube+an+error+occurred.+Please+try+again+later&oq=youtube+an+error+occurred.+Please+try+again+later&gs_l=psy-ab.3..35i39j0i7i30l9.3460.4364..4510...0.2..0.256.1310.0j6j2......0....1..gws-wiz.......0i71.oSLGpx-92vQ&ved=0ahUKEwiQo_z0voTmAhWkwjgGHRpnCRkQ4dUDCAo&uact=5
