### ISSUE TITLE
iOS 端刷新节点列表后，也只有一个节点的问题

### ISSUE THREAD

**Issue by hrnun** [cg3s/forum#221]
## 提交问题请按照格式填写

- 账号：hrn***6@126.com

- 操作系统：iOS

- [x] 是否已更新节点列表 ```(是: 在[]内填 x, 否: 留空) ```

- [x] 是否已查看最新系统公告

- [x] 是否已查看常见问题列表

- [x] 是否已搜索已解决问题列表

**本问答为公开页面，为保护我们的服务安全和您的个人隐私，如截图中含有以下敏感信息，请马赛克处理。**
- 本站网址
- 本站节点的任何信息

### 问题描述：
手机（iphone 7p）的节点列表，刷新与重置后，都只有一个节点，请问是怎么回事呢？
mac 端一切正常。

### 备注：
- [常见问题列表](https://github.com/cg3s/forum/wiki/)
- [已解决问题列表](https://github.com/cg3s/forum/issues?q=is%3Aissue+is%3Aclosed)
- 如想立即得到我们的回复，请在我们的工作时间内提交问题（工作日的10:00-17:00）
- 如需上传截图，对敏感信息马赛克后拖拽或拷贝图片到本编辑器中即可。

**Comment by cg3s** [comment]
4G测试无此情况，你用4G网络试下吧

**Comment by hrnun** [comment]
你好，用了4g 重新进入服务器订阅-点完成，出来还是只有截图中的一个节点 T T

**Comment by cg3s** [comment]
我们在 节点设置/订阅链接和节点密码 处新增了一个备用订阅地址
该地址ip在香港, 更新节点的速度会比.net的快, 您试试备用订阅链接看看呢
我们测试没问题

**Comment by hrnun** [comment]
新增了备用订阅链接，
用4G 和 wifi 状态下分别刷新过节点了，
但就很奇怪还是只显示一个 T  T 哭了……
![WechatIMG402](https://user-images.githubusercontent.com/52479830/69916719-988ab380-1499-11ea-931f-93ef8b02b199.jpeg)

如果换另外app 安装试试看 会有用吗？

**Comment by hrnun** [comment]
新增了备用订阅链接，
用4G 和 wifi 状态下分别刷新过节点了，
但就很奇怪还是只显示一个 T T 哭了……
![WechatIMG402](https://user-images.githubusercontent.com/52479830/69916737-bd7f2680-1499-11ea-92aa-af6143427c40.jpeg)


如果换另外app 安装试试看 会有用吗？

**Comment by hrnun** [comment]
![image](https://user-images.githubusercontent.com/52479830/69916854-ea800900-149a-11ea-9ef7-f41bc0e1c1f2.png)

**Comment by cg3s** [comment]
我们用你的订阅链接测试 节点都能正常刷新，你要不然卸载软件 重装一下吧 装shadowrocket或者Quantumult都可以

**Comment by hrnun** [comment]
恩好的 我再试试！谢谢啦。

**Comment by cg3s** [comment]
不客气
