### ISSUE TITLE
写下您的问题概述

### ISSUE THREAD

**Issue by daniel0805** [cg3s/forum#224]
## 提交问题请按照格式填写
```因不严格按照格式填写，不严格按照教程操作导致的问题，可能不会得到我们及时的处理。```

- 账号： 
113xxx010@qq.com

- 操作系统：[Windows|

### 提交前的必要步骤
```(是: 在[]内填 x, 否: 留空) ```

- [x] 是否已更新节点列表 

- [x] 是否已查看最新系统公告

- [x] 是否已查看常见问题列表

- [x] 是否已搜索已解决问题列表

**本问答为公开页面，为保护我们的服务安全和您的个人隐私，如截图中含有以下敏感信息，请马赛克处理。**
- 本站网址
- 本站节点的任何信息

### 问题描述：
我从cgs下载的小火箭，好几次都被avast杀毒软件删除，说受到感染了，威胁名称是“IDP.Generic”，但我从其他地方下载小火箭又添加不了订阅列表，而且我相信你们的下载途径应该不会刻意绑定病毒，所以比较苦恼。

### 备注：
- [常见问题列表](https://github.com/cg3s/forum/wiki/常见问题列表)
- [已解决问题列表](https://github.com/cg3s/forum/issues?q=is%3Aissue+is%3Aclosed)
- 如想立即得到我们的回复，请在我们的工作时间内提交问题（工作日的10:00-17:00），大多数时候我们能保持快速响应，但不排除我们的工作人员在忙其他的事情，如果我们没有及时回应，请耐心等待。
- 如需上传截图，对敏感信息马赛克后拖拽或拷贝图片到本编辑器中即可。

**Comment by cg3s** [comment]
您更新病毒库了么

**Comment by daniel0805** [comment]
更新了 最新的

**Comment by daniel0805** [comment]
为什么会这样呢？让我用的有点不放心，或者能给我一个官方下载链接吗？

**Comment by cg3s** [comment]
我们还在安装这个杀毒软件，一直装不上，这个之前没人提过这个问题，我们查一下，ss的仓库也有人提相似问题
https://github.com/shadowsocks/shadowsocks-windows/issues/1778

**Comment by cg3s** [comment]
开源软件不存在病毒问题的，网站里的软件我们自己都用了几年了

**Comment by daniel0805** [comment]
那我选择信任吧，avast这个杀毒软件应该挺多人用的吧，我也不知道为什么每次都提醒我被感染了

**Comment by cg3s** [comment]
我们装上这个软件了试试，不知道，我们windows就系统默认的防火墙，已经很多年不装杀毒软件了。
反正我们运营这几年还第一次用户出现杀毒软件报毒的情况。

**Comment by cg3s** [comment]
这杀毒软件安装蛋疼，我们用离线包安装几个小时都装不上

**Comment by cg3s** [comment]
这是什么垃圾杀毒软件啊，安装一直卡着
![image](https://user-images.githubusercontent.com/28707826/70628703-9841a380-1c63-11ea-8580-faac918b57cb.png)
关键是第一次安装成功了，但软件找不到启动的地方
软件目录完全没有这个exe
![image](https://user-images.githubusercontent.com/28707826/70628760-b60f0880-1c63-11ea-84b9-90b3275c1bd8.png)
![image](https://user-images.githubusercontent.com/28707826/70628771-bad3bc80-1c63-11ea-9ac2-1a5646e22277.png)

查了下这个软件
https://www.hostloc.com/thread-581251-1-1.html?d=1
软件强制使用其自身的dns，这太不友好了

以上为吐槽

您要是坚持用这个杀毒软件，我们可以给您按照剩余时间退款。

**Comment by cg3s** [comment]
以后谁用avast的话，我们建议使用系统自带的mse防火墙，或者对中国用户更友好的eset 小红伞。

**Comment by cg3s** [comment]
![image](https://user-images.githubusercontent.com/28707826/70631558-4c452d80-1c68-11ea-8569-c605deae5bac.png)
用eset对ssr-win文件夹进行病毒检查，并未出现任何报毒的情况
目测avast报毒是没什么权威性的，用户如果出现杀毒软件报毒的情况，可将文件夹加入白名单。

**Comment by cg3s** [comment]
由于avast被gfw和谐，造成国内无法测试，我们专门开通新加坡地区的windows服务器系统安装avast商业版进行测试，如下图
![image](https://user-images.githubusercontent.com/28707826/70644546-2e82c300-1c7e-11ea-9074-92a3a1e4e374.png)
![image](https://user-images.githubusercontent.com/28707826/70644674-71dd3180-1c7e-11ea-87cf-c65a238147a7.png)
![image](https://user-images.githubusercontent.com/28707826/70644691-799cd600-1c7e-11ea-8884-909fa8ca8818.png)
并未出现报毒的情况

**Comment by cg3s** [comment]
由于avast内置了vpn功能，造成官网被gfw和谐，从而导致国内安装各种受阻，我们建议国内用户使用其他杀软

**Comment by daniel0805** [comment]
好的 谢谢你们耐心解答

**Comment by cg3s** [comment]
不客气
