### ISSUE TITLE
iso下载shadowrocket时，显示appca账户已锁定，怎么解？

### ISSUE THREAD

**Issue by 55208980zwy** [cg3s/forum#225]
## 提交问题请按照格式填写

- 账号：5520XXXXZWY

- 操作系统：iOS

- [X] 是否已更新节点列表 ```(是: 在[]内填 x, 否: 留空) ```

- [X] 是否已查看最新系统公告

- [X] 是否已查看常见问题列表

- [X] 是否已搜索已解决问题列表

**本问答为公开页面，为保护我们的服务安全和您的个人隐私，如截图中含有以下敏感信息，请马赛克处理。**
- 本站网址
- 本站节点的任何信息

### 备注：
- [常见问题列表](https://github.com/cg3s/forum/wiki/)
- [已解决问题列表](https://github.com/cg3s/forum/issues?q=is%3Aissue+is%3Aclosed)
- 如想立即得到我们的回复，请在我们的工作时间内提交问题（工作日的10:00-17:00）
- 如需上传截图，对敏感信息马赛克后拖拽或拷贝图片到本编辑器中即可。

**Comment by cg3s** [comment]
之前邮件关了提示忘记重开了，导致没及时接收到提示邮件，我们马上解锁就行了

**Comment by 55208980zwy** [comment]
好的～谢谢！没想到这么快就回复了！😊



发自我的iPad


------------------ 原始邮件 ------------------
发件人: CGS小管家 <notifications@github.com&gt;
发送时间: 2019年12月12日 18:30
收件人: cg3s/forum <forum@noreply.github.com&gt;
抄送: 55208980zwy <55208980@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[cg3s/forum] iso下载shadowrocket时，显示appca账户已锁定，怎么解？ (#225)




之前邮件关了提示忘记重开了，导致没及时接收到提示邮件，我们马上解锁就行了

**Comment by cg3s** [comment]
<img width="528" alt="image" src="https://user-images.githubusercontent.com/28707826/70704854-ce3b6200-1d0d-11ea-812c-d66989b5049d.png">
已解锁

**Comment by cg3s** [comment]
另外我们不是提供了两个账号么，如果其中一个被锁了，可以再试下另一个

**Comment by 55208980zwy** [comment]
好的，已经成功进去啦～～谢谢！

**Comment by cg3s** [comment]
不客气
