### ISSUE TITLE
苹果手机登录ins app会显示网路连接错误

### ISSUE THREAD

**Issue by 55208980zwy** [cg3s/forum#227]
## 提交问题请按照格式填写

- 账号：(后台可模糊查询，请打码处理，如12345678@qq.com可填写为123xxx78@qq.com)

- 操作系统：[Windows|Mac|Linux|iOS|Android|路由器]

- [X] 是否已更新节点列表 ```(是: 在[]内填 x, 否: 留空) ```

- [X] 是否已查看最新系统公告

- [X] 是否已查看常见问题列表

- [X] 是否已搜索已解决问题列表

**本问答为公开页面，为保护我们的服务安全和您的个人隐私，如截图中含有以下敏感信息，请马赛克处理。**
- 本站网址
- 本站节点的任何信息

### 问题描述：在手机上登陆ins的app时会出现下图

![54991577369966_ pic_hd](https://user-images.githubusercontent.com/58810249/71479059-d6c38a80-282d-11ea-9804-4769aae40b23.jpg)

但是用safari浏览器登录ins是OK的，facebook用app登录也都没有问题～
请问这个怎么解决？谢谢！

### 备注：
- [常见问题列表](https://github.com/cg3s/forum/wiki/)
- [已解决问题列表](https://github.com/cg3s/forum/issues?q=is%3Aissue+is%3Aclosed)
- 如想立即得到我们的回复，请在我们的工作时间内提交问题（工作日的10:00-17:00）
- 如需上传截图，对敏感信息马赛克后拖拽或拷贝图片到本编辑器中即可。

**Comment by cg3s** [comment]
抱歉，最近没注意到问答区导致没有及时回复，
我们安装登录没这个问题
