### ISSUE TITLE
Mac版本过低无法安装vpn软件，请问有旧版的软件可以吗？

### ISSUE THREAD

**Issue by EricCenVFX** [cg3s/forum#228]
## 提交问题请按照格式填写

- 账号：237230xxx43@qq.com)

- 操作系统：Mac 10.8.5

- [] 是否已更新节点列表 ```(是: 在[]内填 x, 否: 留空) ```

- [x] 是否已查看最新系统公告

- [x] 是否已查看常见问题列表

- [x] 是否已搜索已解决问题列表

**本问答为公开页面，为保护我们的服务安全和您的个人隐私，如截图中含有以下敏感信息，请马赛克处理。**
- 本站网址
- 本站节点的任何信息

### 备注：
- [常见问题列表](https://github.com/cg3s/forum/wiki/)
- [已解决问题列表](https://github.com/cg3s/forum/issues?q=is%3Aissue+is%3Aclosed)
- 如想立即得到我们的回复，请在我们的工作时间内提交问题（工作日的10:00-17:00）
- 如需上传截图，对敏感信息马赛克后拖拽或拷贝图片到本编辑器中即可。

**Comment by cg3s** [comment]
没有旧版本，最旧的也应该不兼容10.8了，10.8都2012年的了，好奇现在用10.8很多软件都不兼容了吧

**Comment by EricCenVFX** [comment]
因为我朋友这边的剪辑软件有时候项目要匹配一定要用finalcutpro 7 ，为了项目有一部电脑必须这个Mac 版本的，所以是没办法吗？刚刚才让他买了个年会员，好尴尬😳

**Comment by cg3s** [comment]
需要他用10.8的这台电脑自己编译了 
项目地址：https://github.com/cg3s/ShadowsocksX-NG

**Comment by cg3s** [comment]
我们在虚拟机里装上10.8系统测试看看是否能正常编译

**Comment by EricCenVFX** [comment]
我这边不会编译抱歉，谢谢你！如果可以我今晚就可以给我朋友试试！谢谢！

**Comment by cg3s** [comment]
编译没这么快，需要安装依赖环境，我们先测试测试吧，不保证一定ok

**Comment by EricCenVFX** [comment]
好的，那请问大概需要多久呢？我可以留在公司等帮我朋友电脑装，今晚可以吗

**Comment by cg3s** [comment]
今晚肯定不行的

**Comment by EricCenVFX** [comment]
好吧o(╥﹏╥)o

**Comment by cg3s** [comment]
我们分别用virtualBox VmWare安装Mac OS X 10.8.5操作系统，均无法安装，我们无法编译适合该系统版本的软件
建议您采取以下两种方式自行解决：
1. https://github.com/cg3s/ShadowsocksX-NG 下载master分支源码使用mac10.8.5的系统进行编译
2. 在路由器中安装支持ssr的固件（教程页面有参考链接，如遇到具体问题请自行搜索，路由器我们不提供详细指导）
3. 使用前置代理，请自行必应搜索 ssr前置代理
4. 科学上网时换其他电脑

如以上均不可行，我们可提供退款服务，退款会扣除卡密平台的手续费用（4%)
