### ISSUE TITLE
更新SSR服务器订阅（不通过代理）无法正确获得列表

### ISSUE THREAD

**Issue by hcy19940819** [cg3s/forum#230]
## 提交问题请按照格式填写

- 账号：hcy199*****

- 操作系统：[Windows]

- [否] 是否已更新节点列表 ```(是: 在[]内填 x, 否: 留空) ```

- [是] 是否已查看最新系统公告

- [是] 是否已查看常见问题列表

- [是] 是否已搜索已解决问题列表

**本问答为公开页面，为保护我们的服务安全和您的个人隐私，如截图中含有以下敏感信息，请马赛克处理。**
- 本站网址
- 本站节点的任何信息

### 问题描述：
依循官网操作简介在公司使用是，无法通过更新SSR服务器订阅（不通过代理）无法正确获得列表。
在家使用时，点击更新ssr服务器则会弹出window提示，之后正常使用，在公司采用相同流程则无window提示，且无法正常连接使用
参考已解决问题中【如何正确的更新节点列表】方法 重装软件和删除服务器列表等方法无效

### 备注：
- [常见问题列表](https://github.com/cg3s/forum/wiki/)
- [已解决问题列表](https://github.com/cg3s/forum/issues?q=is%3Aissue+is%3Aclosed)
- 如想立即得到我们的回复，请在我们的工作时间内提交问题（工作日的10:00-17:00）
- 如需上传截图，对敏感信息马赛克后拖拽或拷贝图片到本编辑器中即可。

**Comment by cg3s** [comment]
您可以试试节点设置页面里订阅链接和节点密码里的备用订阅链接
