### ISSUE TITLE
mac重装系统后再次安装软件连不上外网

### ISSUE THREAD

**Issue by handsomematerchen** [cg3s/forum#232]
## 提交问题请按照格式填写

- 账号：8238***24@qq.com
- 操作系统：Mac

- [x] 是否已更新节点列表 ```(是: 在[]内填 x, 否: 留空) ```

- [x] 是否已查看最新系统公告

- [x] 是否已查看常见问题列表

- [x] 是否已搜索已解决问题列表

**本问答为公开页面，为保护我们的服务安全和您的个人隐私，如截图中含有以下敏感信息，请马赛克处理。**
- 本站网址
- 本站节点的任何信息

### 问题描述：
mac在重新安装软件后没有办法连上外网，手机pad和win都可以正常连

### 备注：
- [常见问题列表](https://github.com/cg3s/forum/wiki/)
- [已解决问题列表](https://github.com/cg3s/forum/issues?q=is%3Aissue+is%3Aclosed)
- 如想立即得到我们的回复，请在我们的工作时间内提交问题（工作日的10:00-17:00）
- 如需上传截图，对敏感信息马赛克后拖拽或拷贝图片到本编辑器中即可。

**Comment by jeanim** [comment]
您应该没有正确设置，请严格按照教程走一遍呢，如果实在不行，请发送向日葵远程软件的机器识别码，我们远程您看看

**Comment by cg3s** [comment]
您应该没有正确设置，请严格按照教程走一遍呢，如果实在不行，请发送向日葵远程软件的机器识别码，我们远程您看看

**Comment by handsomematerchen** [comment]
350 152 918

**Comment by cg3s** [comment]
连不上

**Comment by cg3s** [comment]
mac账户问题，切换账户后正常，需用户自行查询资料解决，或切换到正常的账户使用
