### ISSUE TITLE
更新节点、重装后依然无法连接

### ISSUE THREAD

**Issue by WIllZ11** [cg3s/forum#233]
## 提交问题请按照格式填写
```因不严格按照格式填写，不严格按照教程操作导致的问题，可能不会得到我们及时的处理。```

- 账户昵称： Cat_11

- 操作系统：[Windows] 
```保留一项即可```

### 提交前的必要步骤
```(是: 在[]内填 x, 否: 留空) ```

- [x] 是否已更新节点列表 

- [x] 是否已查看最新系统公告

- [x] 是否已查看常见问题列表

- [x] 是否已搜索已解决问题列表

**本问答为公开页面，为保护我们的服务安全和您的个人隐私，如截图中含有以下敏感信息，请马赛克处理。**
- 本站网址
- 本站节点的任何信息

### 问题描述：
Hi， 你好， 我1月29日早上的时候还在使用， 下午的时候已经无法连接， 但是当时因为手机还可以使用我就没有在意， 直到今天早上也就是刚才， 我发现手机也无法使用了， 我查阅了主站上的端口， 发现所有端口都可以使用， 然后我根据问题列表里的提示检查了所有项目， 最后试着删除了本地的PAC， 重新来一次， 依然是无法使用， 包括手机也是， 和我一起入坑的小伙伴也有挂了的， 还麻烦解决一下， 谢谢~。

### 备注：
- [常见问题列表](https://github.com/cg3s/forum/wiki/常见问题列表)
- [已解决问题列表](https://github.com/cg3s/forum/issues?q=is%3Aissue+is%3Aclosed)
- 如想立即得到我们的回复，请在我们的工作时间内提交问题（工作日的10:00-17:00），大多数时候我们能保持快速响应，但不排除我们的工作人员在忙其他的事情，如果我们没有及时回应，请耐心等待。
- 如需上传截图，对敏感信息马赛克后拖拽或拷贝图片到本编辑器中即可。

**Comment by cg3s** [comment]
您的流量用完了

**Comment by WIllZ11** [comment]
> 您账户当前周期内的流量用完了，请查看流量使用情况
> ![image](https://user-images.githubusercontent.com/28707826/73513455-817c2980-4428-11ea-8a35-a28964b2c1ce.png)
> 在下一个流量重置日之前，您可以补给或积分兑换流量，或者在商店页面购买流量包，或者通过升级套餐扩充流量。

不好意思 全都看了一遍就是没看到那个， 麻烦了 [捂脸]
