### ISSUE TITLE
打开软件后电脑网络代理自动打开 

### ISSUE THREAD

**Issue by 6yun** [cg3s/forum#234]
## 提交问题请按照格式填写

- 账号：117xxx00@qq.com

- 操作系统：[Windows|Mac|Linux|iOS|Android|路由器]

- [x] 是否已更新节点列表 ```(是: 在[]内填 x, 否: 留空) ```

- [x] 是否已查看最新系统公告

- [x] 是否已查看常见问题列表

- [x] 是否已搜索已解决问题列表

**本问答为公开页面，为保护我们的服务安全和您的个人隐私，如截图中含有以下敏感信息，请马赛克处理。**
- 本站网址
- 本站节点的任何信息

### 问题描述：
打开软件后电脑的网络代理自动打开了 
每次都要手动关闭才能上网
请问如何设置打开软件不自动打开代理？谢谢

![Snipaste_2020-02-01_11-30-38](https://user-images.githubusercontent.com/57143285/73586327-90c1ac80-44e6-11ea-8562-17f86465c5af.jpg)

**Comment by jeanim** [comment]
什么系统？

**Comment by cg3s** [comment]
什么系统

**Comment by 6yun** [comment]
> 什么系统

WIN10

**Comment by 6yun** [comment]
> 正常情况下开启代理也是能上网的，
> 在节点可用的情况下开机后代理自动开启，内网外网都能正常连接

我的不行 必须得关闭代理才能上网

**Comment by cg3s** [comment]
那你的设置有问题
请检查如下配置：
代理模式：全局
代理规则：绕过大陆和局域网

确保所选的节点可用（如勾选节点负载均衡可不用管）

**Comment by 6yun** [comment]
我的是这么设置的 

> 那你的设置有问题
> 请检查如下配置：
> 代理模式：全局
> 代理规则：绕过大陆和局域网
> 
> 确保所选的节点可用（如勾选节点负载均衡可不用管）

我的确实是这么设置的

**Comment by cg3s** [comment]
您可以发个向日葵远程软件的识别码，方便的话，我们远程您看看

**Comment by cg3s** [comment]
请问如何设置打开软件不自动打开代理？
这个需要在你退出软件之前将代理模式设置为直连（即关闭软件代理）

**Comment by 6yun** [comment]
> 您可以发个向日葵远程软件的识别码，方便的话，我们远程您看看

820 616 228

**Comment by cg3s** [comment]
用户可能没有及时更新节点
