### ISSUE TITLE
订阅成功，节点正常，插件均关闭，还是不能访问

### ISSUE THREAD

**Issue by amo666** [cg3s/forum#235]
## 订阅成功，节点正常，插件均关闭，还是不能访问****

- 账户昵称： amo666

- 操作系统：Mac

### 提交前的必要步骤
```(是: 在[]内填 x, 否: 留空) ```

- [] 是否已更新节点列表 

- [] 是否已查看最新系统公告

- [] 是否已查看常见问题列表

- [] 是否已搜索已解决问题列表

**本问答为公开页面，为保护我们的服务安全和您的个人隐私，如截图中含有以下敏感信息，请马赛克处理。**
- 本站网址
- 本站节点的任何信息

### 问题描述：
手动订阅成功，日本A3端口正常，但就是不能访问youtube等外网

### 备注：
- [常见问题列表](https://github.com/cg3s/forum/wiki/常见问题列表)
- [已解决问题列表](https://github.com/cg3s/forum/issues?q=is%3Aissue+is%3Aclosed)
- 如想立即得到我们的回复，请在我们的工作时间内提交问题（工作日的10:00-17:00），大多数时候我们能保持快速响应，但不排除我们的工作人员在忙其他的事情，如果我们没有及时回应，请耐心等待。
- 如需上传截图，对敏感信息马赛克后拖拽或拷贝图片到本编辑器中即可。

**Comment by cg3s** [comment]
查不到这个账户昵称

**Comment by cg3s** [comment]
请按 [常见问题-外网连不上了？](https://github.com/cg3s/forum/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E5%88%97%E8%A1%A8#1-%E5%A4%96%E7%BD%91%E8%BF%9E%E4%B8%8D%E4%B8%8A%E4%BA%86)进行检查
