### ISSUE TITLE
疫情期间我们将为身在湖北的朋友免费升级/续费专业版套餐

### ISSUE THREAD

**Issue by cg3s** [cg3s/forum#236]
国内疫情基本得到控制，本活动结束

如果您身在湖北，请先查看以下规则，符合用户资格后，可在此提交邮箱信息，疫情期间我们将为您免费升级/续期专业版套餐

| 参数 | 详情 |
|---|---|
|  减免规则 | 免费升级/续期专业版月会员  |
| 账户要求1  | **账户到期日在4月1日之前** |
| 账户要求2 | **2020年1月1日至2月25日期内在湖北境内有登录记录** |
| 账户要求3 | **2020年1月1日至今在湖北境内有节点使用记录**，如2020年2月25日前注册及登录记录一直为湖北境内，则此项可省略 |
| 提交方式  | 提交账户邮箱  |
| 身份验证 | 身在湖北即可，不要求户籍在湖北 |
| **特别注意** | **我们会在后期不断审查账户的使用情况，如出现虚假瞒报将不作任何解释禁用账户** |

备注：到期日超过的请等待4月份的规则更新，4月1日如疫情还未得到有效控制，我们将再次续期月会员，依此类推。

由于服务的特殊性，我们不要求提供身份及电话号码的真实信息
为避免薅羊毛行为，我们会根据您的账户记录判断数据的真实性

同时也欢迎在问答区讨论一切和疫情相关的话题

本规则会根据情况不断调整，请符合规则后再提交信息。

武汉加油！

**Comment by hiraeh** [comment]
hiraeth

**Comment by cg3s** [comment]
@hiraeh 已为您账户续期季度专业版套餐

**Comment by YANG617** [comment]
YANG

**Comment by YANG617** [comment]
谢谢

**Comment by cg3s** [comment]
@YANG617 有挺多用户都是这个昵称，您在提供下邮箱吧

**Comment by li-tings** [comment]
beakons  783964970@qq.com
谢谢

**Comment by cg3s** [comment]
@li-tings 抱歉，账户到期日不符合规则要求

**Comment by jianguolong** [comment]
Black-小黑屋

**Comment by jianguolong** [comment]
Black-小黑屋

**Comment by animaseed** [comment]
animaseed  wangqiseed@qq.com
非常感谢

**Comment by cg3s** [comment]
@animaseed 账户有效期不在3月1日之前，暂时不符合免费续期资格

**Comment by jianguolong** [comment]
jianguolong@@outlook.com

**Comment by jianguolong** [comment]
ljghxx@qq.com

**Comment by animaseed** [comment]
@cg3s 明白了，还是谢谢你们，你们棒棒的

**Comment by cg3s** [comment]
@jianguolong 已升级续期

**Comment by jianguolong** [comment]
> @jianguolong 已升级续期

感谢感谢！棒棒的！

**Comment by asker8023** [comment]
39250699@qq.com

**Comment by cg3s** [comment]
@asker8023 不符合“账户要求2”条件

**Comment by asker8023** [comment]
> @asker8023 不符合“账户要求2”条件

不会吧，我一直在湖北啊

**Comment by cg3s** [comment]
@asker8023 请查看三项账户要求

**Comment by asker8023** [comment]
> @asker8023 请查看三项账户要求

那也是不满足条件1，2怎么会不满足

**Comment by cg3s** [comment]
最近一次湖北登录记录是在5个月前，用代理登录的我们无法作为监测标准

**Comment by asker8023** [comment]
> 最近一次湖北登录记录是在5个月前（不在2020年1月1日之后），用代理登录的我们无法作为判断依据

好吧   也没啥     就是问问       
只是我是每天都自启动小飞机

**Comment by cg3s** [comment]
@asker8023 如果一直在湖北，您可以关注这个issue参与下个月的免费升级续期服务，我们每月一续

**Comment by neihuang** [comment]
389788594@qq.com  非常感谢你们～🙏

**Comment by cg3s** [comment]
@neihuang 我们正要给你免费续期一个月呢，但你自己续费了？

**Comment by gct6872662** [comment]
您好，想问下 ，这个VPN怎么开启游戏模式，会和游戏加速器一个效果么 。我是WIN10系统

**Comment by asker8023** [comment]
湖北黄冈地区移动无法正常使用，全部节点都没校，完整拷贝其它人的文件都没法解决。尤其手机端。脸书都不能上，谷歌也是。

**Comment by cg3s** [comment]
@gct6872662 @asker8023 与本主题无关的话题请单独提交issue

**Comment by neihuang** [comment]
> @neihuang 我们正要给你免费续期一个月呢，但你自己续期了？

是的-，-因为急着用。所以我不满足。。这个条件了吗

**Comment by neihuang** [comment]
> @cg3s 因为着急用，所以自己又续费了

**Comment by ALIEZISTRUE** [comment]
ALIEZISTRUE 635791672@qq.com
非常感谢xD

**Comment by cg3s** [comment]
@ALIEZISTRUE 已续期

**Comment by ALIEZISTRUE** [comment]
> 
> 
> @ALIEZISTRUE 已续期

谢谢xDDDD
