### ISSUE TITLE
请问为什么我继费后，就不能用了，之前一直在用的？

### ISSUE THREAD

**Issue by Justin0345** [cg3s/forum#237]
## 提交问题请按照格式填写
```因不严格按照格式填写，不严格按照教程操作导致的问题，可能不会得到我们及时的处理。```

- 账户昵称： 

- 操作系统：[Windows|Mac|Linux|iOS|Android|路由器] 
```保留一项即可```

### 提交前的必要步骤
```(是: 在[]内填 x, 否: 留空) ```

- [] 是否已更新节点列表 

- [] 是否已查看最新系统公告

- [] 是否已查看常见问题列表

- [] 是否已搜索已解决问题列表

**本问答为公开页面，为保护我们的服务安全和您的个人隐私，如截图中含有以下敏感信息，请马赛克处理。**
- 本站网址
- 本站节点的任何信息

### 备注：
- [常见问题列表](https://github.com/cg3s/forum/wiki/常见问题列表)
- [已解决问题列表](https://github.com/cg3s/forum/issues?q=is%3Aissue+is%3Aclosed)
- 如想立即得到我们的回复，请在我们的工作时间内提交问题（工作日的10:00-17:00），大多数时候我们能保持快速响应，但不排除我们的工作人员在忙其他的事情，如果我们没有及时回应，请耐心等待。
- 如需上传截图，对敏感信息马赛克后拖拽或拷贝图片到本编辑器中即可。

**Comment by cg3s** [comment]
账户昵称是什么

**Comment by Justin0345** [comment]
> 账户昵称是什么，估计是你账户流量在续费之前已经用完了，请补给或兑换下流量，或者购买流量包或者升级下套餐扩充下流量

  simon034516@163.com       JustinLin，对的我是用完才续费的，我已经购买完成了，网站都可以看到我使用到3月了，现在我应该怎么操作？

**Comment by cg3s** [comment]
哦，你的账户流量正常的，理论上能正常使用才对的

**Comment by cg3s** [comment]
你是什么系统

**Comment by Justin0345** [comment]
> 你是什么系统

android 和window10，都不行

**Comment by cg3s** [comment]
你上次正常使用是什么适合呢，17天前我们发的配置更新公告看了么

**Comment by Justin0345** [comment]
没有看，请问现在怎么配置？

**Comment by cg3s** [comment]
请看公告

**Comment by Justin0345** [comment]
我这里打开小飞机就显示订阅失败

**Comment by Justin0345** [comment]
已经删除节点，请更新，但显示订阅失败

**Comment by cg3s** [comment]
请按照教程操作

**Comment by Justin0345** [comment]
是哪一个，请发给我可以吗？谢谢

**Comment by Justin0345** [comment]
哦，可以啦，请问安卓的怎么操作？

**Comment by cg3s** [comment]
请看教程

**Comment by Justin0345** [comment]
之前使用你这个方法可以，现在再使就不行，请问一下，我是缺什么操作了吗？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"notifications"<notifications@github.com&gt;;
发送时间:&nbsp;2019年2月14日(星期四) 上午10:34
收件人:&nbsp;"cg3s/forum"<forum@noreply.github.com&gt;;
抄送:&nbsp;"Justin lin"<351316217@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [cg3s/forum] 请指教 (#103)




在CMD窗口输入如下指令设置代理：
set http_proxy=socks5://127.0.0.1:1080 set https_proxy=socks5://127.0.0.1:1080 set ftp_proxy=socks5://127.0.0.1:1080 
详细教程：https://segmentfault.com/a/1190000013587465

—
You are receiving this because you authored the thread.
Reply to this email directly,&nbsp;view it on GitHub, or&nbsp;mute the thread.





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"notifications"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月10日(星期一) 中午12:54
收件人:&nbsp;"cg3s/forum"<forum@noreply.github.com&gt;;
抄送:&nbsp;"Justin lin"<351316217@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [cg3s/forum] 请问为什么我继费后，就不能用了，之前一直在用的？ (#237)




Closed #237.

**Comment by cg3s** [comment]
我们更新了安卓的使用教程，你现在按新的教程操作试试，操作前可以把以前的节点全部删掉，或者干脆重装下app，重新走下流程，以后都按订阅来更新节点了。

**Comment by Justin0345** [comment]
我想安装CodeWorks for Android，安装error了，之前你教过我用
set http_proxy=socks5://127.0.0.1:1080
set https_proxy=socks5://127.0.0.1:1080
set ftp_proxy=socks5://127.0.0.1:1080
```
详细教程：https://segmentfault.com/a/1190000013587465&nbsp;;


但现在不行，我想问问，应该怎么搞




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"notifications"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月12日(星期三) 晚上6:59
收件人:&nbsp;"cg3s/forum"<forum@noreply.github.com&gt;;
抄送:&nbsp;"Justin lin"<351316217@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [cg3s/forum] 请问为什么我继费后，就不能用了，之前一直在用的？ (#237)




我们更新了安卓的使用教程，你现在按新的教程操作试试，操作前可以把以前的节点全部删掉，或者干脆重装下app，重新走下流程，以后都按订阅来更新节点了。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by cg3s** [comment]
这个命令是控制台用的
wiki里有原文：https://github.com/cg3s/forum/wiki/%E5%BC%80%E5%8F%91%E8%80%85%E4%BB%AC%E7%9A%84%E4%BB%A3%E7%90%86%E8%AE%BE%E7%BD%AE

软件里设置代理你google下吧

**Comment by Justin0345** [comment]
你好，为什么我现在电脑的小飞机订阅失败，手机上是可以的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"notifications"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月12日(星期三) 晚上7:09
收件人:&nbsp;"cg3s/forum"<forum@noreply.github.com&gt;;
抄送:&nbsp;"Justin lin"<351316217@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [cg3s/forum] 请问为什么我继费后，就不能用了，之前一直在用的？ (#237)




这个命令是控制台用的
 wiki里有原文：https://github.com/cg3s/forum/wiki/%E5%BC%80%E5%8F%91%E8%80%85%E4%BB%AC%E7%9A%84%E4%BB%A3%E7%90%86%E8%AE%BE%E7%BD%AE
 
软件里设置代理你google下吧

**Comment by cg3s** [comment]
@Justin0345 电脑上 .com的网站能访问么

**Comment by Justin0345** [comment]
百度可以上，Cgsss.net上不了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"notifications"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月6日(星期三) 上午9:35
收件人:&nbsp;"cg3s/forum"<forum@noreply.github.com&gt;;
抄送:&nbsp;"Justin lin"<351316217@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [cg3s/forum] 请问为什么我继费后，就不能用了，之前一直在用的？ (#237)





 
@Justin0345 电脑上 .com的网站能访问么

**Comment by cg3s** [comment]
您用手机4G登录我们网站联系我们在线客服把，这里不要暴露我们域名，这个issue我们会删除处理
