### ISSUE TITLE
更新订阅失败，想访问cgsss.net看下公告，发现cgsss.net打不开，其他网站正常。

### ISSUE THREAD

**Issue by SimonHe96** [cg3s/forum#239]
- 账号：189XXXX95659.163.com

- 操作系统：Windows

- [] 是否已更新节点列表 

- [] 是否已查看最新系统公告

- [x] 是否已查看常见问题列表

- [x] 是否已搜索已解决问题列表

### 问题描述：
更新订阅失败，想访问cgsss.net看下公告，发现cgsss.net打不开，其他网站正常。
请求协助，谢谢。

**Comment by cg3s** [comment]
网站一切正常，请自行检查网络环境或用手机4G访问，本issue验证违反问答区要求，再出现此问题，我们将对账户封禁。
