### ISSUE TITLE
广州联通部分时段ping得通，但连接后实际上翻不了

### ISSUE THREAD

**Issue by limgyang** [cg3s/forum#241]
**因本问答区会被搜索引擎索引，我们禁止在问答区暴露本站域名及节点信息，一旦出现，我们将立即删除您发起的提问**

## 提交问题请按照格式填写
```因不严格按照格式填写，不严格按照教程操作导致的问题，可能不会得到我们及时的处理。```

- 账户昵称： monkeylim

- 操作系统：[iOS] 
```保留一项即可```

### 提交前的必要步骤
```(是: 在[]内填 x, 否: 留空) ```

- [X] 是否已更新节点列表 

- [X] 是否已查看最新系统公告

- [X] 是否已查看常见问题列表

- [X] 是否已搜索已解决问题列表

**本问答为公开页面，为保护我们的服务安全和您的个人隐私，文字与截图中禁止出现以下信息，文字请用其他词汇代替，图片请马赛克处理。**
- 本站网址
- 本站节点的任何信息

### 问题描述：
路由器在电信网络，可正常使用
iOS在中国联通网络，节点列表已更新（删除重新添加），ping得通，但是打开连接后，无法翻墙，网站上始终只看到一个在线（在线设备1/3）
以上现象看情况，时不时会出现
所在地点 广州市番禺区

### 备注：
- [常见问题列表](https://github.com/cg3s/forum/wiki/常见问题列表)
- [已解决问题列表](https://github.com/cg3s/forum/issues?q=is%3Aissue+is%3Aclosed)
- 如想立即得到我们的回复，请在我们的工作时间内提交问题（工作日的10:00-17:00），大多数时候我们能保持快速响应，但不排除我们的工作人员在忙其他的事情，如果我们没有及时回应，请耐心等待。
- 如需上传截图，对敏感信息马赛克后拖拽或拷贝图片到本编辑器中即可。

**Comment by cg3s** [comment]
您用的shadowrocket是2.1.48版本么

**Comment by limgyang** [comment]
2.1.34（836）

**Comment by cg3s** [comment]
先更新一下软件试试呢，老版本之前有用户反映节点更新会有问题

**Comment by limgyang** [comment]
No longer available. The developer has removed this app from the App store
你们的账号，以及我的美区 皆是

**Comment by cg3s** [comment]
我们测试安装app一切正常。

**Comment by limgyang** [comment]
APP 我已有，就是update的时候这样提示，我是需要删了重装吗？

**Comment by cg3s** [comment]
update app需要保证用的apple id一致

**Comment by limgyang** [comment]
我删掉重装试试

**Comment by limgyang** [comment]
删掉重装，可以了，谢谢

**Comment by cg3s** [comment]
ok，不客气
