### ISSUE TITLE
注册时，显示邮箱验证码不对

### ISSUE THREAD

**Issue by hcy19940819** [cg3s/forum#242]
- 账户昵称： hcy1xxx0819@xx.com

- 操作系统：[Windows] 
```保留一项即可```

### 提交前的必要步骤
```(是: 在[]内填 x, 否: 留空) ```

- [是] 是否已更新节点列表 

- [是] 是否已查看最新系统公告

- [是] 是否已查看常见问题列表

- [是] 是否已搜索已解决问题列表

**本问答为公开页面，为保护我们的服务安全和您的个人隐私，文字与截图中禁止出现以下信息，文字请用其他词汇代替，图片请马赛克处理。**
- 本站网址
- 本站节点的任何信息

### 问题描述：
邀请朋友注册，多次尝试提示邮件验证码不对，核对多次发现是对的

### 备注：
- [常见问题列表](https://github.com/cg3s/forum/wiki/常见问题列表)
- [已解决问题列表](https://github.com/cg3s/forum/issues?q=is%3Aissue+is%3Aclosed)
- 如想立即得到我们的回复，请在我们的工作时间内提交问题（工作日的10:00-17:00），大多数时候我们能保持快速响应，但不排除我们的工作人员在忙其他的事情，如果我们没有及时回应，请耐心等待。
- 如需上传截图，对敏感信息马赛克后拖拽或拷贝图片到本编辑器中即可。

**Comment by cg3s** [comment]
你朋友注册时填的邮箱是什么呢？

**Comment by hcy19940819** [comment]
用的QQ邮箱 yy377105436@qq.com
可以接受到验证码 但输入提示不对

发自我的iPhone

**Comment by cg3s** [comment]
我看这个邮箱已经注册了，应该问题解决了吧
