### ISSUE TITLE
VIMEO访问速度慢

### ISSUE THREAD

**Issue by limgyang** [cg3s/forum#243]
## 提交问题请按照格式填写

- 账号：(后台可模糊查询，请打码处理，如12345678@qq.com可填写为123xxx78@qq.com)

- 操作系统：[iOS|路由器]

- [X] 是否已更新节点列表 ```(是: 在[]内填 x, 否: 留空) ```

- [X] 是否已查看最新系统公告

- [X] 是否已查看常见问题列表

- [X] 是否已搜索已解决问题列表

**本问答为公开页面，为保护我们的服务安全和您的个人隐私，如截图中含有以下敏感信息，请马赛克处理。**
- 本站网址
- 本站节点的任何信息

### 问题描述：

香港和新加坡多个节点，ping VIMEO大概110-130ms，但打开速度非常慢，路由器WIFI下，视频只能播240P，iOS可以720P，youtube/facebook速度正常，是否有什么方案解决。
Github是否能打开，这个看天，时不时打不开，已加入强制SS名单

### 备注：
- [常见问题列表](https://github.com/cg3s/forum/wiki/)
- [已解决问题列表](https://github.com/cg3s/forum/issues?q=is%3Aissue+is%3Aclosed)
- 如想立即得到我们的回复，请在我们的工作时间内提交问题（工作日的10:00-17:00）
- 如需上传截图，对敏感信息马赛克后拖拽或拷贝图片到本编辑器中即可。

**Comment by cg3s** [comment]
路由器的话你要把vimeo的cdn加到规则里，确保访问vimeo所有资源都走了代理，或者在非路由器模式下开全局访问vimeo测试

**Comment by limgyang** [comment]
我目前在路由开的模式是gfwlist模式，黑白名单里是有vimeo的强制走代理的，是否意味着我对gfwlist模式的理解有错，实际上gfwlist只走gfwlist，我的黑白名单不会生效？如果是这样的话，是我的理解问题，我去改下模式，谢谢

**Comment by cg3s** [comment]
https://github.com/gfwlist/gfwlist/wiki/Custom-Rules 请看这里最下面一条，
因为vimeocdn.com没有被墙，需要手动将下面这行加入gfwlist规则

||vimeocdn.com

**Comment by cg3s** [comment]
常见问题列表已更新本问题解决方法
[#20-youtube facebook访问视频都很快，唯独vimeo视频加载很慢](https://github.com/cg3s/forum/wiki/常见问题列表#20-youtube-facebook访问视频都很快唯独vimeo视频加载很慢)
