### ISSUE TITLE
湖北黄冈地区，手机节点无法更新。全部节点无法使用，PC端可正常更新节点连接。脸书谷歌无法打开。艺术类网站A站打开缓慢，希望能检查下。

### ISSUE THREAD

**Issue by asker8023** [cg3s/forum#244]
## 提交问题请按照格式填写

- 账号：39250699@qq.com

- 操作系统：Windows10

- x 是否已更新节点列表

-x 是否已查看最新系统公告

- x 是否已查看常见问题列表

- x是否已搜索已解决问题列表

**本问答为公开页面，为保护我们的服务安全和您的个人隐私，如截图中含有以下敏感信息，请马赛克处理。**
- 本站网址
- 本站节点的任何信息

### 备注：
- [常见问题列表](https://github.com/cg3s/forum/wiki/)
- [已解决问题列表](https://github.com/cg3s/forum/issues?q=is%3Aissue+is%3Aclosed)
- 如想立即得到我们的回复，请在我们的工作时间内提交问题（工作日的10:00-17:00）
- 如需上传截图，对敏感信息马赛克后拖拽或拷贝图片到本编辑器中即可。

**Comment by cg3s** [comment]
重复问题
请看 https://github.com/cg3s/forum/issues/241

**Comment by asker8023** [comment]
问题是，现在打开谷歌也有问题。脸书。PC端很慢

**Comment by cg3s** [comment]
目前节点服务器一切正常，您可以删掉软件文件夹按教程重新走一遍

**Comment by asker8023** [comment]
我重新下载过客户端了，也按流程再次编辑了服务器更新了列表问题依旧，脸书和谷歌开不了，A站打开缓慢。换了其它梯子脸书和谷歌是可以打开的。希望能查看下是否线路有问题。基本的操作我确认是没什么问题的。

**Comment by asker8023** [comment]
A站可以很快打开了。谷歌脸书依旧

**Comment by cg3s** [comment]
你发个向日葵识别码，我们远程您看看吧

**Comment by asker8023** [comment]
981030193

**Comment by cg3s** [comment]
建议更换宽带运营商，移动fq的国际出口太小，拥堵严重
如果坚持用移动的话，也可以选择费用比较昂贵支持iplc的vpn服务商,但我们不建议，因为多余的vpn费用换个运营商更划算。

**Comment by asker8023** [comment]
好的  感谢

**Comment by cg3s** [comment]
不客气

**Comment by nyjjky** [comment]
移动宽带无法打开网站主页，手机网络倒是可以打开

**Comment by cg3s** [comment]
@nyjjky 家用移动不适合翻墙，要么换网要么换更贵的平台（支持专线的）
