### ISSUE TITLE
请赶快解禁

### ISSUE THREAD

**Issue by lyrabird** [cg3s/forum#246]
## 提交问题请按照格式填写

- 账号：(icu007@qq.com)

- 操作系统：[Windows|路由器]

没有乱用啊，就是昨晚通宵看netflix，难得一天放假，赶快解禁吧，我今天要追剧。
还有就是能不能搞个好些的问答区，这问答区太难用了。

**Comment by cg3s** [comment]
我们暂时无法知晓您的账户的具体使用情况，但后台有太多连接数据，导致节点频繁掉线，这还是第一次出现此类情况，不知道是不是您的账户有被盗用的情况

我们可以先给您账户解禁，然后重置节点密码和订阅链接，重置后您需要重新更新节点信息

如果重置后情况依然如此，并且没有其他办法禁止此类情况，我们只能永久禁用您的账户并给您按剩余时间做退款处理。

问答区我们应该不会更换，问答区我们也用了几年了，已经解决了很多用户的问题。

**Comment by cg3s** [comment]
已解禁并重置节点密码和订阅链接，请更新节点信息后再使用。

**Comment by lyrabird** [comment]
那是从几点到几点出现这问题？都老客户了，不要动不动说禁用退款，怎么查出问题你可以教我啊。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: CGS小管家 <notifications@github.com&gt;
发送时间: 2020年2月23日 12:29
收件人: cg3s/forum <forum@noreply.github.com&gt;
抄送: lyrabird <icu007@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[cg3s/forum] 请赶快解禁 (#246)




我们暂时无法知晓您的账户的具体使用情况，但后台有太多连接数据，导致节点频繁掉线，这还是第一次出现此类情况，不知道是不是您的账户有被盗用的情况
 
我们可以先给您账户解禁，然后重置节点密码和订阅链接，重置后您需要重新更新节点信息
 
如果重置后情况依然如此，并且没有其他办法禁止此类情况，我们只能永久禁用您的账户并给您按剩余时间做退款处理。
 
问答区我们应该不会更换，问答区我们也用了几年了，已经解决了很多用户的问题。

**Comment by lyrabird** [comment]
那是几点到几点出现问题，都是那么多年的老客户，不要动不动说要退款，你可以教我怎么查出问题，是路由器端还是终端，还是太多终端使用。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: CGS小管家 <notifications@github.com&gt;
发送时间: 2020年2月23日 12:29
收件人: cg3s/forum <forum@noreply.github.com&gt;
抄送: lyrabird <icu007@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[cg3s/forum] 请赶快解禁 (#246)




我们暂时无法知晓您的账户的具体使用情况，但后台有太多连接数据，导致节点频繁掉线，这还是第一次出现此类情况，不知道是不是您的账户有被盗用的情况

我们可以先给您账户解禁，然后重置节点密码和订阅链接，重置后您需要重新更新节点信息

如果重置后情况依然如此，并且没有其他办法禁止此类情况，我们只能永久禁用您的账户并给您按剩余时间做退款处理。

问答区我们应该不会更换，问答区我们也用了几年了，已经解决了很多用户的问题。

**Comment by cg3s** [comment]
我们已经对您账户的节点密码和订阅链接做了重置处理，主要为了防止账户被他人盗用的情况
您可以更新下节点信息使用看看

> 都是那么多年的老客户，不要动不动说要退款
只是如果这个情况得不到解决的话，我们只能这样操作，没有其他恶意禁用的意思

您现在就登录网站后重新拷贝设置下订阅链接，看看重置后问题是否依旧，如果还是如此，我们再看实际什么情况。

**Comment by cg3s** [comment]
您可以在账户的流量记录看到大概从今天早上8点开始，有很多新加坡A3节点的流量记录，从那个时间开始，新加坡A3节点就频繁掉线，然后我们禁用您的账户后，节点就正常

**Comment by cg3s** [comment]
造成节点频繁掉线的ip地址在 中国广东广州海珠区珠江商业大厦

**Comment by cg3s** [comment]
香港A2也出现因你的账户造成的掉线情况，我们已对你的这个ip进行禁用，如其他节点也出现此情况，将全线屏蔽该ip，请知晓
屏蔽的IP: 113.xx.129.39

**Comment by lyrabird** [comment]
今天公司这里也是每个节点只能用十来分钟就连不上，不知道什么问题。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "CGS小管家"<notifications@github.com&gt;; 
发送时间: 2020年2月23日(星期天) 晚上9:38
收件人: "cg3s/forum"<forum@noreply.github.com&gt;; 
抄送: "空子"<icu007@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [cg3s/forum] 请赶快解禁 (#246)




香港A2也出现因你的账户造成的掉线情况，我们已对你的这个ip进行禁用，如其他节点也出现此情况，将全线屏蔽该ip，请知晓
 屏蔽的IP: 113.xx.129.39
 
&mdash;

**Comment by cg3s** [comment]
你们是这个ip么，113.xx.129.39

**Comment by lyrabird** [comment]
这个ip就是我们公司的，但是凌晨不会有人上啊。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "CGS小管家"<notifications@github.com&gt;; 
发送时间: 2020年2月23日(星期天) 晚上9:38
收件人: "cg3s/forum"<forum@noreply.github.com&gt;; 
抄送: "空子"<icu007@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [cg3s/forum] 请赶快解禁 (#246)




香港A2也出现因你的账户造成的掉线情况，我们已对你的这个ip进行禁用，如其他节点也出现此情况，将全线屏蔽该ip，请知晓
 屏蔽的IP: 113.xx.129.39
 
&mdash;

**Comment by cg3s** [comment]
不是凌晨，就是这会，因为这会我们才全线屏蔽这个ip的

**Comment by lyrabird** [comment]
我刚才连了韩国1，你看看，也是连上一会儿就不行。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "CGS小管家"<notifications@github.com&gt;; 
发送时间: 2020年2月24日(星期一) 下午2:27
收件人: "cg3s/forum"<forum@noreply.github.com&gt;; 
抄送: "空子"<icu007@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [cg3s/forum] 请赶快解禁 (#246)




不是凌晨，就是这会，因为这会我们才全线屏蔽这个ip的
 
&mdash;

**Comment by cg3s** [comment]
我们不知道这个ip下的设备后台有什么软件，只要这个ip一连节点，就跟节点建立上万个连接，不论哪个节点，都被爆，我们只能全部节点屏蔽这个ip

**Comment by cg3s** [comment]
不用看，我们人工屏蔽的

**Comment by lyrabird** [comment]
这就是我们公司的ip




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "CGS小管家"<notifications@github.com&gt;; 
发送时间: 2020年2月24日(星期一) 下午2:26
收件人: "cg3s/forum"<forum@noreply.github.com&gt;; 
抄送: "空子"<icu007@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [cg3s/forum] 请赶快解禁 (#246)




你们是这个ip么，113.xx.129.39
 
&mdash;

**Comment by lyrabird** [comment]
我先关掉路由器端，用shadow软件翻试试？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "CGS小管家"<notifications@github.com&gt;; 
发送时间: 2020年2月24日(星期一) 下午2:30
收件人: "cg3s/forum"<forum@noreply.github.com&gt;; 
抄送: "空子"<icu007@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [cg3s/forum] 请赶快解禁 (#246)




不用看，我们人工屏蔽的
 
&mdash;

**Comment by cg3s** [comment]
可以，我们暂时给你公司的ip开放一个洛杉矶A4节点，其他节点暂不开放

**Comment by lyrabird** [comment]
我现在先让他们用软件，你那边看看连接情况。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "CGS小管家"<notifications@github.com&gt;; 
发送时间: 2020年2月24日(星期一) 下午2:47
收件人: "cg3s/forum"<forum@noreply.github.com&gt;; 
抄送: "空子"<icu007@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [cg3s/forum] 请赶快解禁 (#246)




可以，我们暂时给你公司的ip开放一个洛杉矶A4节点，其他节点暂不开放
 
&mdash;

**Comment by lyrabird** [comment]
软件翻墙也不行？是其他ip吗？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: CGS小管家 <notifications@github.com&gt;
发送时间: 2020年2月24日 14:47
收件人: cg3s/forum <forum@noreply.github.com&gt;
抄送: lyrabird <icu007@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[cg3s/forum] 请赶快解禁 (#246)




可以，我们暂时给你公司的ip开放一个洛杉矶A4节点，其他节点暂不开放

**Comment by cg3s** [comment]
113.1xx.115.25，这个ip，还是和以前一样的情况，这个会影响其他用户，我们只能禁用处理了。我们也不知道您账户为何最近两天频繁出现这种情况，以前从没出现过。

**Comment by lyrabird** [comment]
我查下这ip



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: CGS小管家 <notifications@github.com&gt;
发送时间: 2020年2月25日 00:09
收件人: cg3s/forum <forum@noreply.github.com&gt;
抄送: lyrabird <icu007@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[cg3s/forum] 请赶快解禁 (#246)




113.1xx.115.25，这个ip，还是和以前一样的情况，这个会影响其他用户，我们只能禁用处理了。我们也不知道您账户为何最近两天频繁出现这种情况，以前从没出现过。

**Comment by lyrabird** [comment]
刚查了，公司的ip自己变了，然后网管之前用路由器测试洛杉矶4，把科学开关打开了。现在把路由器端关了，我让他们用软件翻。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: CGS小管家 <notifications@github.com&gt;
发送时间: 2020年2月25日 00:09
收件人: cg3s/forum <forum@noreply.github.com&gt;
抄送: lyrabird <icu007@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[cg3s/forum] 请赶快解禁 (#246)




113.1xx.115.25，这个ip，还是和以前一样的情况，这个会影响其他用户，我们只能禁用处理了。我们也不知道您账户为何最近两天频繁出现这种情况，以前从没出现过。

**Comment by lyrabird** [comment]
今晚我们用软件没有出问题吧。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: CGS小管家 <notifications@github.com&gt;
发送时间: 2020年2月25日 00:09
收件人: cg3s/forum <forum@noreply.github.com&gt;
抄送: lyrabird <icu007@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[cg3s/forum] 请赶快解禁 (#246)




113.1xx.115.25，这个ip，还是和以前一样的情况，这个会影响其他用户，我们只能禁用处理了。我们也不知道您账户为何最近两天频繁出现这种情况，以前从没出现过。

**Comment by cg3s** [comment]
我们无法判断你的设备是用的软件还是路由器，只能判断ip，但由于您的ip发生变更，我们再次屏蔽ip就没太大意义。

**Comment by lyrabird** [comment]
行吧，如果找不到问题，那就停用吧，看怎么个退款法。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "CGS小管家"<notifications@github.com&gt;; 
发送时间: 2020年2月25日(星期二) 凌晨0:47
收件人: "cg3s/forum"<forum@noreply.github.com&gt;; 
抄送: "空子"<icu007@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [cg3s/forum] 请赶快解禁 (#246)




我们无法判断你的设备是用的软件还是路由器，只能判断ip，但由于您的ip发生变更，我们再次屏蔽ip就没太大意义。
 
&mdash;

**Comment by cg3s** [comment]
剩余可用天数： 138 天 （2月24日-7月11日）
当前周期套餐：企业版半年183天，购买价格1056元
应退金额：138/183*1056 = 797元，算800元吧

退款发送一个微信收款码即可

**Comment by lyrabird** [comment]
发自我的iPhone


------------------ 原始邮件 ------------------
发件人: CGS小管家 <notifications@github.com&gt;
发送时间: 2020年2月26日 20:53
收件人: cg3s/forum <forum@noreply.github.com&gt;
抄送: lyrabird <icu007@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[cg3s/forum] 请赶快解禁 (#246)




剩余可用天数： 138 天 （2月24日-7月11日）
当前周期套餐：企业版半年183天，购买价格1056元
应退金额：138/183*1056 = 797元，算800元吧

退款发送一个微信收款码即可

**Comment by cg3s** [comment]
问答区不能通过邮件发送图片，您可将微信收款码发送到admin@cgsss.net

**Comment by cg3s** [comment]
已退款并解除账户禁用

此情况为首次出现，为了避免以后再次出现，我们已下架企业版套餐，路由器下如果设备数太多，我们不能排除有什么设备后台装了什么乱七八糟的软件导致连接数暴增，相对而言我们更愿意服务家用路由。

**Comment by lyrabird** [comment]
好的，谢谢🙏



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: CGS小管家 <notifications@github.com&gt;
发送时间: 2020年2月27日 18:21
收件人: cg3s/forum <forum@noreply.github.com&gt;
抄送: lyrabird <icu007@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[cg3s/forum] 请赶快解禁 (#246)




已退款并解除账户禁用

此情况为首次出现，为了避免以后再次出现，我们已下架企业版套餐，路由器下如果设备数太多，我们不能排除有什么设备后台装了什么乱七八糟的软件导致连接数暴增，相对而言我们更愿意服务家用路由。

**Comment by cg3s** [comment]
不客气
