### ISSUE TITLE
手动更新订阅失败

### ISSUE THREAD

**Issue by JiaoBoLin** [cg3s/forum#247]
- 账户昵称： A_Better

- 操作系统：[Windows|

- [x] 是否已更新节点列表 

- [x] 是否已查看最新系统公告

- [x] 是否已查看常见问题列表

- [x] 是否已搜索已解决问题列表

### 问题描述：
手动更新订阅失败 也重置订阅链接 重新尝试也失败 订阅地址对的粘贴到浏览器可以生成txt文档
软件文件夹也删除重新下载过 都更新订阅失败 检查账户流量完全够用

**Comment by cg3s** [comment]
你先扫描一个节点进去，然后走代理更新吧

**Comment by cg3s** [comment]
如果方面的话，可以留下向日葵远程识别码，我们远程看看你的电脑设置才知道具体原因，远程预约个时间

**Comment by neihuang** [comment]
> 如果方面的话，可以留下向日葵远程识别码，我们远程看看你的电脑设置才知道具体原因，需要远程请预约个时间

能帮我也解决一下吗。。我也出现了一模一样的问题

**Comment by cg3s** [comment]
@neihuang 识别码多少

**Comment by JiaoBoLin** [comment]
已经解决 网络和共享中心里面的dns不知道怎么填上数值了 恢复默认就能正常更新订阅了 谢谢

**Comment by cg3s** [comment]
👌，不客气
