### ISSUE TITLE
手动更新订阅失败

### ISSUE THREAD

**Issue by neihuang** [cg3s/forum#248]
- 账户昵称： 3897xx594@qq.com

- 操作系统：[Mac] 

- [x] 是否已更新节点列表 

- [x] 是否已查看最新系统公告

- [x] 是否已查看常见问题列表

- [x] 是否已搜索已解决问题列表

问题描述：前天用的还是好的，从昨天开始就打不开了。已试过重置订阅链接、更换不同的服务器版本、软件文件夹也删除重新下载过，都更新订阅失败。检查账户流量完全够用。

**Comment by cg3s** [comment]
发下向日葵识别码

**Comment by cg3s** [comment]
可以参考下这里 https://github.com/cg3s/forum/issues/247

**Comment by neihuang** [comment]
> @cg3s 识别码：722124809

**Comment by cg3s** [comment]
和楼上的问题一样，dns问题，不过他的是设置了出问题，你的是没设置出问题

**Comment by neihuang** [comment]
> 和楼上的问题一样，dns问题，不过他的是设置了出问题，你的是没设置出问题

非常感谢！我是电脑小白。。真的超感谢你！！🙏🙏🙏🙏

**Comment by cg3s** [comment]
不客气
