### ISSUE TITLE
ios端订阅更新后没有节点,安装的已经是最新版本

### ISSUE THREAD

**Issue by lalaku01** [cg3s/forum#250]
**因本问答区会被搜索引擎索引，我们禁止在问答区暴露本站域名及节点信息，一旦出现，我们将立即删除您发起的提问**

## 提交问题请按照格式填写
```因不严格按照格式填写，不严格按照教程操作导致的问题，可能不会得到我们及时的处理。```

- 账户昵称： lalaku

- 操作系统：|iOS|
```保留一项即可```

### 提交前的必要步骤
```(是: 在[]内填 x, 否: 留空) ```

- [x] 是否已更新节点列表 

- [x] 是否已查看最新系统公告

- [x] 是否已查看常见问题列表

- [x] 是否已搜索已解决问题列表

**本问答为公开页面，为保护我们的服务安全和您的个人隐私，文字与截图中禁止出现以下信息，文字请用其他词汇代替，图片请马赛克处理。**
- 本站网址
- 本站节点的任何信息

### 问题描述：

ios端订阅更新后没有节点,安装的已经是最新版本(2.1.48)

### 备注：
- [常见问题列表](https://github.com/cg3s/forum/wiki/常见问题列表)
- [已解决问题列表](https://github.com/cg3s/forum/issues?q=is%3Aissue+is%3Aclosed)
- 如想立即得到我们的回复，请在我们的工作时间内提交问题（工作日的10:00-17:00），大多数时候我们能保持快速响应，但不排除我们的工作人员在忙其他的事情，如果我们没有及时回应，请耐心等待。
- 如需上传截图，对敏感信息马赛克后拖拽或拷贝图片到本编辑器中即可。

**Comment by cg3s** [comment]
我们测试无此问题

**Comment by cg3s** [comment]
你可以将订阅链接复制到手机safari浏览器中访问，看看是否会出现一大段代码

**Comment by lalaku01** [comment]
> 我们测试无此问题
> 
> We tested negative for that

显示这样：
![微信图片_20200229174635](https://user-images.githubusercontent.com/25317766/75605187-88778400-5b1b-11ea-8ecc-3f2cb7a89a55.jpg)

**Comment by cg3s** [comment]
你说的是哪个软件 shadowricket还是Quantumult

**Comment by lalaku01** [comment]
两个软件都不行，shadowricket直接没有任何节点，Quantumult显示上图，我的订阅链接用手机safari浏览器打不开

**Comment by cg3s** [comment]
代理都关了么，我们两个软件测试都没问题

**Comment by cg3s** [comment]
请先确保订阅链接在浏览器里能正常打开，如果订阅链接打不开，那你手机的网络设置有问题

**Comment by lalaku01** [comment]
订阅链接在Wifi和4G状态下都打不开，手机网络可以正常上网

**Comment by cg3s** [comment]
.com的网页都打不开？这个域名没有被墙的，你可以在电脑上关闭代理后访问.com, 应该能正常打开的，能打开网站 订阅链接就应该是能直接访问的

**Comment by cg3s** [comment]
另外备用订阅链接也试下，能否正常打开

**Comment by lalaku01** [comment]
订阅链接和备用订阅都是一样的地址吗？复制出来两个地址都一样

**Comment by cg3s** [comment]
不一样

**Comment by lalaku01** [comment]
我的账户备用订阅和订阅链接都一样，哪里出错了？

**Comment by cg3s** [comment]
不可能一样，请确定复制的订阅链接正确

**Comment by lalaku01** [comment]
网站页面复制有问题，试了很多遍，复制出的都一样

**Comment by cg3s** [comment]
不可能一样

**Comment by lalaku01** [comment]
算了，只用电脑端的吧，手机端不可用

**Comment by cg3s** [comment]
你这个只是个人情况，我们测试ok，其他人也没出现这个问题。请确保订阅链接复制正确

**Comment by cg3s** [comment]
或者你手机录个屏发到 admin@本站域名 这个邮箱，我们看下是不是你操作问题
