### ISSUE TITLE
路由器不可以

### ISSUE THREAD

**Issue by tomyhong** [cg3s/forum#252]
## 提交问题请按照格式填写

- 账号：gong****20@hotmail.com
- 操作系统：[路由器]

- [x] 是否已更新节点列表 

- [x] 是否已查看最新系统公告

- [x] 是否已查看常见问题列表

- [x] 是否已搜索已解决问题列表

**本问答为公开页面，为保护我们的服务安全和您的个人隐私，如截图中含有以下敏感信息，请马赛克处理。**
- 本站网址
- 本站节点的任何信息

### 问题描述：
小米mesh路由器不可以访问。4G就正常的。请问如何解决。

**Comment by cg3s** [comment]
与我们无关的网络环境问题请自行解决

**Comment by tomyhong** [comment]
是需要设置路由器设置还是换一个路由器。能不能帮忙确认这一点。

**Comment by cg3s** [comment]
您的具体问题是路由器里翻墙，还是wifi状态下不能使用？如果是wifi状态，那不能使用的设备又是什么系统？

**Comment by tomyhong** [comment]
wifi状态下手机就不可以

**Comment by cg3s** [comment]
你路由器是网络是正常的么，这个我们无法判断你路由器具体情况，需要你自己查找问题原因

**Comment by cg3s** [comment]
另外你手机是什么系统，请详细说明

**Comment by tomyhong** [comment]
手机是ios，苹果x。版本是最新的。不开v的情况下能正常访问国内网站。开了访问不了。在4g状态下开启v可以访问

**Comment by cg3s** [comment]
软件装的shadowrocket还是quan

**Comment by tomyhong** [comment]
shadowrocket

**Comment by tomyhong** [comment]
had这个

**Comment by cg3s** [comment]
shadowrocket的全局路由是选的”配置“么
电脑上试了么，是否正常？

**Comment by cg3s** [comment]
- 首先检测同wifi状态下电脑端是否正常，如正常则手机app设置有问题
- 如电脑端也无法访问外网，请检查dns设置，可将dns设置为1.1.1.1和8.8.8.8，dns设置请百度

**Comment by tomyhong** [comment]
嗯 移动的。。电脑也不行。 我家里的移动送的路由器电脑没问题。
好的收到。谢谢。非常感谢

**Comment by cg3s** [comment]
也就是其他路由器正常唯独小米这个不行咯，那很大可能性是dns设置不合理，设置的dns服务器解析不到国外的ip
