### ISSUE TITLE
账户锁定，无法下载

### ISSUE THREAD

**Issue by julie901017** [cg3s/forum#254]
- 账户昵称： julie901017

- 操作系统：iOS

- [×] 是否已更新节点列表 

- [×] 是否已查看最新系统公告

- [×] 是否已查看常见问题列表

- [×] 是否已搜索已解决问题列表

### 问题描述：
账户1和账户2都被锁定，无法下载ios客户端

**Comment by cg3s** [comment]
均已解锁

**Comment by julie901017** [comment]
> 均已解锁
just test, still locked, it's said need to be verify the account

**Comment by julie901017** [comment]
> 均已解锁

你好 刚测试过了，两个账户，还是被锁定，要求验证账户，请问如何验证

**Comment by cg3s** [comment]
稍等，我们正在解锁

**Comment by julie901017** [comment]
> 稍等，我们正在解锁

好的 谢谢 解锁后请告知 我第一时间使用 以防再次被锁

**Comment by cg3s** [comment]
均已解锁

**Comment by julie901017** [comment]
> 均已解锁

已登录成功，谢谢
