### ISSUE TITLE
在此简单描述您的问题（问答区禁止出现本站域名及节点信息，违反立删）

### ISSUE THREAD

**Issue by daya0413** [cg3s/forum#255]
- 账户昵称： 时崎狂三
- 操作系统：Windows10

```(是: 在[]内填 x, 否: 留空) ```

- [是] 是否已更新节点列表 

- [是] 是否已查看最新系统公告

- [是] 是否已查看常见问题列表

- [是] 是否已搜索已解决问题列表

**本问答为公开页面，为保护我们的服务安全和您的个人隐私，文字与截图中禁止出现以下信息，文字请用其他词汇代替，图片请马赛克处理。**
- 本站网址
- 本站节点的任何信息

### 问题描述：
如题 关于站内屏蔽黄色相关传播渠道等
提出以下问题
                1.站内所说的黄色传播相关渠道是指那些渠道？
延伸提问 2.传播渠道包括某些r18网站吗？（例如pornhub 和国内一些会员制福利资源网）
延伸提问 3.如果只是普通网站但包含r18内容又会如何？（例如推特 pixiv）
                4.网站后续会开放v2ray线路吗？
                5.网站对于我们这些使用梯子只是为了浏览色情网站的人看法和后续处理是怎样的？

ps.我是之前提问 pornhub可以正常打开却无法播放视频的那位  在我寻找众多方法无果之后尝试换了另一个平台的梯子 结果却可以正常播放 且同时我关闭了那个梯子打开贵站的梯子之后却立马无限缓冲 与此同时  我之前提到的也是使用贵站梯子的朋友 至今无法加载播放pornhub站内视频 

### 备注：
- [常见问题列表](https://github.com/cg3s/forum/wiki/常见问题列表)
- [已解决问题列表](https://github.com/cg3s/forum/issues?q=is%3Aissue+is%3Aclosed)
- 如想立即得到我们的回复，请在我们的工作时间内提交问题（工作日的10:00-17:00），大多数时候我们能保持快速响应，但不排除我们的工作人员在忙其他的事情，如果我们没有及时回应，请耐心等待。
- 如需上传截图，对敏感信息马赛克后拖拽或拷贝图片到本编辑器中即可。

**Comment by cg3s** [comment]
1: 具体可以查看审查规则列表，我们会间断性的更新 “屏蔽XXX网站" 的规则
2: 这个我们做不到完全的屏蔽，只是起到一个排查的效果
3: 普通网站不会屏蔽
4: v2ray还在研究，主要需要接口的二次开发（目前虽然有直接可用的方案，但不开源且会暴露域名信息我们觉得不安全）
5: 如果用梯子只是浏览xxx类网站的话，我们的确不太欢迎，因为我们后期的一切服务都是围绕CG行业展开（比如现在的福利中心/众筹项购买），后续我们不会强制处理，只会间断性的屏蔽一些xxx类网站，长期如此，只看xxx类的用户应该自然会放弃使用我们的服务了。

如果您需要长期稳定的访问pornhub的话，我们不是您的最佳选择，然后关于pornhub的播放问题，在我们这不是一个必须解决的问题，虽然我们的确不太知道具体原因，但既然你再次强调，从技术层面来说，我们会着手解决此类问题（只是我们测试的时候没有复现此情况，这对我们解决此情况是个问题）。

然后在这里也补充下我们屏蔽XXX类网站的根本原因：
在我们看来长期浏览xxx类网站的用户相对来说比较杂（各个行业各种行为习惯我们均无法了解），这就会造成用户在邀请用户的时候很容易将我们的网站分享到一些公开的场合，并且由于一些色情服务从业者（特别是粉丝数比较大的大V）本来受关注度就比较高，如果不注意的分享了我们的平台相关的信息，就很容易对我们产生安全方面的困扰。但CG行业就简单很多，而且服务CG行业也简单很多。

**Comment by daya0413** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"CGS小管家"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月3日(星期二) 晚上9:00
收件人:&nbsp;"cg3s/forum"<forum@noreply.github.com&gt;;
抄送:&nbsp;"♚丫丫♚"<1428225891@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [cg3s/forum] 在此简单描述您的问题（问答区禁止出现本站域名及节点信息，违反立删） (#255)




1: 具体可以查看审查规则列表，我们会间断性的更新 “屏蔽XXX网站" 的规则
 2: 这个我们做不到完全的屏蔽，只是起到一个排查的效果
 3: 普通网站不会屏蔽
 4: v2ray还在研究，主要需要接口的二次开发（目前虽然有直接可用的方案，但不开源且会暴露域名信息我们觉得不安全）
 5: 如果用梯子只是浏览xxx类网站的话，我们的确不太欢迎，因为我们后期的一切服务都是围绕CG行业展开（比如现在的福利中心/众筹项购买），后续我们不会强制处理，只会间断性的屏蔽一些xxx类网站，长期如此，只看xxx类的用户应该自然会放弃使用我们的服务了。
 
如果您需要长期稳定的访问pornhub的话，我们不是您的最佳选择，然后关于pornhub的播放问题，在我们这不是一个必须解决的问题，虽然我们的确不太知道具体原因，但既然你再次强调，从技术层面来说，我们会着手解决此类问题（只是我们测试的时候没有复现此情况，这对我们解决此情况是个问题）。
 
然后在这里也补充下我们屏蔽XXX类网站的根本原因：
 在我们看来长期浏览xxx类网站的用户相对来说比较杂（各个行业各种行为习惯我们均无法了解），这就会造成用户在邀请用户的时候很容易将我们的网站分享到一些公开的场合，并且由于一些色情服务从业者（特别是粉丝数比较大的大V）本来受关注度就比较高，如果不注意的分享了我们的平台相关的信息，就很容易对我们产生安全方面的困扰。但CG行业就简单很多，而且服务CG行业也简单很多。
 
感谢您的解惑 谢谢

**Comment by cg3s** [comment]
不客气
