### ISSUE TITLE
求助！充值后卡密找不到了。。。

### ISSUE THREAD

**Issue by Morning397** [cg3s/forum#256]
- 账号：627****08@qq.com

- 账户昵称： Morning397

- 操作系统：Android

- [x] 是否已更新节点列表 

- [x] 是否已查看最新系统公告

- [x] 是否已查看常见问题列表

- [x] 是否已搜索已解决问题列表

### 问题描述：
求助！充值后手贱关闭了页面，现找不到卡密无法充值了。。。

**Comment by cg3s** [comment]
联系方式填的啥？我的钱包页面有找回卡密功能
