### ISSUE TITLE
手机流量可以更新订阅翻墙，WIFI就是不行

### ISSUE THREAD

**Issue by BuluSir** [cg3s/forum#258]
**因本问答区会被搜索引擎索引，我们禁止在问答区暴露本站域名及节点信息，一旦出现，我们将立即删除您发起的提问**

## 提交问题请按照格式填写
```因不严格按照格式填写，不严格按照教程操作导致的问题，可能不会得到我们及时的处理。```

- 账户昵称： 10xxx29152@qq.com

- 操作系统：[Windows] 
```保留一项即可```

### 提交前的必要步骤
```(是: 在[]内填 x, 否: 留空) ```

- [x] 是否已更新节点列表 

- [x] 是否已查看最新系统公告

- [x] 是否已查看常见问题列表

- [x] 是否已搜索已解决问题列表

**本问答为公开页面，为保护我们的服务安全和您的个人隐私，文字与截图中禁止出现以下信息，文字请用其他词汇代替，图片请马赛克处理。**
- 本站网址
- 本站节点的任何信息

### 问题描述：

上个星期某天突然就发现电脑无法更新订阅了，WIFI也不行，但用流量可以，就是相对以前慢了些。订阅地址用手机更新过也不行。全局，直连也没戏。 昨天，我连上隔壁的WIFI居然可以连接，连的也有点慢。我看了电脑的DNS都是默认的。

### 备注：
- [常见问题列表](https://github.com/cg3s/forum/wiki/常见问题列表)
- [已解决问题列表](https://github.com/cg3s/forum/issues?q=is%3Aissue+is%3Aclosed)
- 如想立即得到我们的回复，请在我们的工作时间内提交问题（工作日的10:00-17:00），大多数时候我们能保持快速响应，但不排除我们的工作人员在忙其他的事情，如果我们没有及时回应，请耐心等待。
- 如需上传截图，对敏感信息马赛克后拖拽或拷贝图片到本编辑器中即可。

**Comment by BuluSir** [comment]
我的也是小米路由器，有点慌。

**Comment by cg3s** [comment]
改下dns试试，参考常见问题列表21项
另外家用移动就是墙中墙，长期使用的话建议换网

**Comment by BuluSir** [comment]
好的 我试试




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "CGS小管家"<notifications@github.com&gt;; 
发送时间: 2020年3月4日(星期三) 上午10:56
收件人: "cg3s/forum"<forum@noreply.github.com&gt;; 
抄送: "1056629152"<1056629152@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [cg3s/forum] 手机流量可以更新订阅翻墙，WIFI就是不行 (#258)




改下dns试试，参考常见问题列表21项
另外家用移动就是墙中墙，长期使用的话建议换网

**Comment by BuluSir** [comment]
可以了，dns改了114.114.114.114
谢谢了

**Comment by cg3s** [comment]
ok,不客气
