### ISSUE TITLE
微软应用商店无法打开，(ps.可以连上google)

### ISSUE THREAD

**Issue by seejudge** [cg3s/forum#265]
Windows10 微软应用商店无法打开，可以连上google, youtube，
1.查询了这个问题，在不关闭小飞机的情况下，试了很多方法都不行
2.关闭小飞机，可以打开微软应用商店
是否有办法在开代理的情况下，用微软的服务？？

![image](https://user-images.githubusercontent.com/50795880/76947182-34083d00-6940-11ea-93e0-7ec0ba951ad1.png)
![image](https://user-images.githubusercontent.com/50795880/76951287-674dca80-6946-11ea-848a-0a5bae74371a.png)

**Comment by cg3s** [comment]
https://www.thewindowsclub.com/setup-proxy-metro-application-windows-8
你是谷歌英文查的么
