### ISSUE TITLE
关于福利中心的申购福利问题

### ISSUE THREAD

**Issue by daya0413** [cg3s/forum#266]
## 提交问题请按照格式填写

- 账号：2732xxx163@qq.com
- 操作系统：[Windows]

- [x] 是否已更新节点列表
- [x] 是否已查看最新系统公告
- [x] 是否已查看常见问题列表
- [x] 是否已搜索已解决问题列表

## 问题描述：
如题

1. 本人严格意义上来说并不算cg从业者 福利申购是否只能申请cg行业相关福利？
2. 如果只能申请cg行业相关福利 我是否能申请网站会员之类的福利？例如pixiv高级会员亦或者artstation中的学习参考图片
3. 如果并不只是cg行业相关福利 请问贵站把标准定义在哪里 因为我看到还有人申请了c语言众筹 通过了 我在猜测 贵站的福利申请标准是否宽松 是仅仅包括计算机行业还是有关于学习方面都可以？亦或者更加宽松 任何网站vip，任何可购买物品都可以

备注：我是之前询问pornhub无法播放的那位用户 最近经过我的多次尝试 pornhub问题已经基本解决了 没有什么特别的方法 当初一直提示视频无法播放 各种方法试了很多次都无法改善 但是我近期发现pornhub视频无法播放的次数明显少多了基本不会出现了  即使出现后透过刷新 或者清理后台重启浏览器就可以解决了 个人不是很清楚网络节点代理方面的事情  之前换了个梯子之后确实这种情况没有了  不过问题应该解决了  只不过我联系不上我的那位朋友不清楚他那边能不能正常使用pornhub

**Comment by cg3s** [comment]
1. 仅涵盖CG相关
2. 会员账户这种不考虑，会增加我们后期在账户管理方面的工作量，artstation完全属于CG行业
3. C语言的学习属于CG行业范畴，CG行业就是建立在计算机和图形学基础之上的，相关科普请维基百科，其他方面的福利对我们来说意义不大，暂时不会考虑，因为我们只想围绕CG展开服务。

**Comment by cg3s** [comment]
ps: C语言那套教学是csdn上的，下载csdn的视频超级费神，之后我们不会考虑csdn的福利申请了

**Comment by daya0413** [comment]
好的感谢您的解惑



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "CGS小管家"<notifications@github.com&gt;; 
发送时间: 2020年3月19日(星期四) 晚上11:49
收件人: "cg3s/forum"<forum@noreply.github.com&gt;; 
抄送: "&amp;#x265A;丫丫&amp;#x265A;"<1428225891@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [cg3s/forum] 关于福利中心的申购福利问题 (#266)





  
仅涵盖CG相关
 
会员账户这种不考虑，会增加我们后期在账户管理方面的工作量，artstation完全属于CG行业
 
C语言的学习属于CG行业范畴，CG行业就是建立在计算机和图形学基础之上的，相关科普请维基百科，其他方面的福利对我们来说意义不大，暂时不会考虑，因为我们只想围绕CG展开服务。

**Comment by cg3s** [comment]
不客气
