### ISSUE TITLE
appleid还是被锁状态！什么时候可以用？

### ISSUE THREAD

**Issue by sworduc** [cg3s/forum#267]
**因本问答区会被搜索引擎索引，我们禁止在问答区暴露本站域名及节点信息，一旦出现，我们将立即删除您发起的提问**

## 提交问题请按照格式填写
```因不严格按照格式填写，不严格按照教程操作导致的问题，可能不会得到我们及时的处理。```

- 账户昵称： sworduc

- 操作系统：iOS
```保留一项即可```

### 提交前的必要步骤
```(是: 在[]内填 x, 否: 留空) ```

- [×] 是否已更新节点列表 

- [×] 是否已查看最新系统公告

- [×] 是否已查看常见问题列表

- [×] 是否已搜索已解决问题列表

**本问答为公开页面，为保护我们的服务安全和您的个人隐私，文字与截图中禁止出现以下信息，文字请用其他词汇代替，图片请马赛克处理。**
- 本站网址
- 本站节点的任何信息

### 问题描述：
网站appleid被锁，啥时候解锁？

### 备注：
- [常见问题列表](https://github.com/cg3s/forum/wiki/常见问题列表)
- [已解决问题列表](https://github.com/cg3s/forum/issues?q=is%3Aissue+is%3Aclosed)
- 如想立即得到我们的回复，请在我们的工作时间内提交问题（工作日的10:00-17:00），大多数时候我们能保持快速响应，但不排除我们的工作人员在忙其他的事情，如果我们没有及时回应，请耐心等待。
- 如需上传截图，对敏感信息马赛克后拖拽或拷贝图片到本编辑器中即可。

**Comment by cg3s** [comment]
今天账户频繁被锁，我们有点烦了所以没及时解锁

您可以自行注册购买或者谷歌相关代购
比如这里 https://zahuo.info/product/33.html

**Comment by sworduc** [comment]
有你们能提供id下最好！能解锁么！

**Comment by cg3s** [comment]
已解锁

**Comment by sworduc** [comment]
搞定 谢谢！

**Comment by cg3s** [comment]
不客气

**Comment by sworduc** [comment]
对了 建个TG群啊

**Comment by cg3s** [comment]
很早以前建过，觉得意义不大

**Comment by sworduc** [comment]
最大的用处是，当用户有问题的时候群友可以协助解决
这样就减轻了你们的服务负担
也提升了服务体验

**Comment by cg3s** [comment]
电报群会产生很多无意义的闲聊，我们希望大家不要把关注点放在我们平台，最好忘记我们的存在。

电报群有以下我们觉得不适合作为客服支持的地方：
1. 大多数都是无意义的闲聊
2. 遇到的问题大多数都可以在常见问题列表里找到，一人提问多人应答，也浪费大家的时间
3. 电报其他群频道有很多杂乱的信息，容易让部分用户迷失
4. 电报需要翻墙，并不能覆盖我们所有用户，比如安卓用户安装就会比较麻烦
5. 我们不建议用实名制手机号注册电报，但大部分用户估计搞不定google voice

**Comment by sworduc** [comment]
考虑全面！期待在线客服！

**Comment by cg3s** [comment]
在线客服不是时刻开启，一般只在必须刷新节点列表或墙发力导致服务集体下线时开启，因为很多时候的问题都是用户啥都没看就来提问，完全没有意义，我们希望引导用户通过问答区的常见问题列表和已解决问题列表自行解决。
