### ISSUE TITLE
客户端配置

### ISSUE THREAD

**Issue by sworduc** [cg3s/forum#268]
## 提交问题请按照格式填写

- 账号：50****0@QQ.com
- 操作系统：[Windows|

- [×] 是否已更新节点列表 ```(是: 在[]内填 x, 否: 留空) ```

- [×] 是否已查看最新系统公告

- [×] 是否已查看常见问题列表

- [×] 是否已搜索已解决问题列表

**本问答为公开页面，为保护我们的服务安全和您的个人隐私，如截图中含有以下敏感信息，请马赛克处理。**
- 本站网址
- 本站节点的任何信息

### 问题描述：
看了常见问题：当前网络环境，SS及SSR该怎么配置协议混淆才是最佳？
请问这些都是你们服务端设置好的吧！
用SSR订阅后客户端不需要设置对不？

### 备注：
- [常见问题列表](https://github.com/cg3s/forum/wiki/)
- [已解决问题列表](https://github.com/cg3s/forum/issues?q=is%3Aissue+is%3Aclosed)
- 如想立即得到我们的回复，请在我们的工作时间内提交问题（工作日的10:00-17:00）
- 如需上传截图，对敏感信息马赛克后拖拽或拷贝图片到本编辑器中即可。

**Comment by cg3s** [comment]
用户不用管，这个我们存档用的，用户有兴趣看着玩就行。
