### ISSUE TITLE
账户已续订，却显示账户仍然到期。

### ISSUE THREAD

**Issue by ohyawen** [cg3s/forum#270]
## 提交问题请按照格式填写

- 账号：32xxx248@qq.com

- 操作系统：Windows

### 问题描述：

账户已续订：

专业版v2 - 月 | xx.00 元 | 续订 | 2020-03-27 23:00 | 2020-01-25 23:21 | 在 2020-04-27 23:00:05 续费 | 自动重置

但主页还是显示到期，无法使用，请尽快解决，谢谢！

**Comment by jeanim** [comment]
您好，可能是因为您之前的套装版续订没有取消，然后又续订了个专业版，但这个中间应该有个降级操作才对，表现为自动脚本的bug，我们会尽快查证修复。
我们已取消您前面两个共计62元的订单，并将余额重新恢复到账户，同时为了保障您的账户使用，已为您订购专业版v2-月套餐，当前账号余额59.44元，同时为了因本bug为您造成的困扰，我们会赠送一枚23元的卡密发到您的邮箱，为您造成的不便敬请谅解。

**Comment by cg3s** [comment]
您好，可能是因为您之前的套装版续订没有取消，然后又续订了个专业版，但这个中间应该有个降级操作才对，表现为自动脚本的bug，我们会尽快查证修复。
我们已取消您前面两个共计62元的订单，并将余额重新恢复到账户，同时为了保障您的账户使用，已为您订购专业版v2-月套餐，当前账号余额59.44元，同时为了因本bug为您造成的困扰，我们会赠送一枚23元的卡密发到您的邮箱，为您造成的不便敬请谅解。
