### ISSUE TITLE
为什么小飞机需要十分钟重启一次，不然就连不上wai 网？

### ISSUE THREAD

**Issue by cansey** [cg3s/forum#271]
## 提交问题请按照格式填写

- 账号：(后台可模糊查询，请打码处理，如12345678@qq.com可填写为123xxx78@qq.com)

- 操作系统：[Windows|Mac|Linux|iOS|Android|路由器]

- [] 是否已更新节点列表 ```(是: 在[]内填 x, 否: 留空) ```

- [] 是否已查看最新系统公告

- [] 是否已查看常见问题列表

- [] 是否已搜索已解决问题列表

**本问答为公开页面，为保护我们的服务安全和您的个人隐私，如截图中含有以下敏感信息，请马赛克处理。**
- 本站网址
- 本站节点的任何信息

### 备注：
- [常见问题列表](https://github.com/cg3s/forum/wiki/)
- [已解决问题列表](https://github.com/cg3s/forum/issues?q=is%3Aissue+is%3Aclosed)
- 如想立即得到我们的回复，请在我们的工作时间内提交问题（工作日的10:00-17:00）
- 如需上传截图，对敏感信息马赛克后拖拽或拷贝图片到本编辑器中即可。

**Comment by cg3s** [comment]
请按格式填写

**Comment by cansey** [comment]
账号：321***97@qq.com
操作系统：Windows10
[] 是否已更新节点列表  x

[] 是否已查看最新系统公告  x

[] 是否已查看常见问题列表  x

[] 是否已搜索已解决问题列表  
为什么小飞机需要十分钟重启一次，不然就连不上wai 网？

**Comment by cg3s** [comment]
您是访问的什么网站呢？我们用A组节点测试youtube并未出现此现象，另外您也可以在手机上测试是否有断链的情况，如果没有，则可能您window10的网络设置可能有异常。

可以参考 https://github.com/cg3s/forum/issues/258 这里改下dns设置看看

**Comment by cansey** [comment]
是打开谷歌网站就不行，我过个十几分钟，打开谷歌就连不上了，我需要把小飞机在点开就可以连上了。

**Comment by cg3s** [comment]
1. 修改dns
2. 新建个系统账户切换过去测试下
3. 我们给您账户换组一下，看看其他组节点是否依然如此，如需换组，请在此确认

**Comment by cansey** [comment]
需要换组，确认

**Comment by cg3s** [comment]
已切换到B组，换组后请更新节点列表（需删除以前的节点），换组并不一定能解决问题，只是测试下效果。

**Comment by cansey** [comment]
请问如果换组？更新节点列表就是更新SSR服务器订阅是吗？

**Comment by cg3s** [comment]
恩，就跟平时更新节点列表一样
