### ISSUE TITLE
关闭代理以后我自己的网页打不开QQ啥的都能用

### ISSUE THREAD

**Issue by yongqing-wei** [cg3s/forum#272]
关闭代理以后我自己的网页打不开QQ啥的都能用。有没有好的处理办法，我之前都是用腾讯管家修复一下网络 但是现在不行了。关闭代理修复也修复不了了。请大神帮忙解决，我现在只能开着咱们的代理才能打开网页！！

**Comment by cg3s** [comment]
请按格式填写

**Comment by yongqing-wei** [comment]
账号：317***75@qq.com
操作系统：Windows10
[] 是否已更新节点列表 x

[] 是否已查看最新系统公告 x

[] 是否已查看常见问题列表 x

[] 是否已搜索已解决问题列表
关闭代理以后我自己的网页打不开QQ啥的都能用。有没有好的处理办法，我之前都是用腾讯管家修复一下网络 但是现在不行了。关闭代理修复也修复不了了。请大神帮忙解决，我现在只能开着咱们的代理才能打开网页！！

**Comment by cg3s** [comment]
您装下向日葵远程软件，发下识别码，我们远程您看看

**Comment by yongqing-wei** [comment]
目前好了，我重启了然后DNS改成自动了。 以前我是修复一下就好的。下次在遇到我再来找你吧。

**Comment by cg3s** [comment]
好的
