### ISSUE TITLE
不管更新订阅是否成功，都无法连接上外网

### ISSUE THREAD

**Issue by thor-shuang** [cg3s/forum#273]
## 提交问题请按照格式填写

- 账号：207569XX26@qq.com)

- 操作系统：Windows

- [是] 是否已更新节点列表 (是

- [是] 是否已查看最新系统公告

- [是] 是否已查看常见问题列表

- [是] 是否已搜索已解决问题列表

### 问题描述：
更新服务器地址有时成功有时失败，但是都上不了外网。
而且直接从官网上复制的订阅地址，在浏览器中打开也连不上，也没有下载text
尝试了直连和PAC和全局模式，但是都连不上。
没有显示端口被占用，也没有装杀毒软件。

### 备注：
- [常见问题列表](https://github.com/cg3s/forum/wiki/)
- [已解决问题列表](https://github.com/cg3s/forum/issues?q=is%3Aissue+is%3Aclosed)
- 如想立即得到我们的回复，请在我们的工作时间内提交问题（工作日的10:00-17:00）
- 如需上传截图，对敏感信息马赛克后拖拽或拷贝图片到本编辑器中即可。

**Comment by cg3s** [comment]
代理规则设置错误，改为绕过局域网和大陆即可。
