### ISSUE TITLE
网速太慢了！！节点很多都是failed！！

### ISSUE THREAD

**Issue by Cocokathy** [cg3s/forum#274]
## 网速太慢了！！节点很多都是failed！！

- 账号：148xxx560@qq.com

- 操作系统：Mac

- [x] 是否已更新节点列表 ```(是: 在[]内填 x, 否: 留空) ```

- [x] 是否已查看最新系统公告

- [x] 是否已查看常见问题列表

- [x] 是否已搜索已解决问题列表

**本问答为公开页面，为保护我们的服务安全和您的个人隐私，如截图中含有以下敏感信息，请马赛克处理。**
- 本站网址
- 本站节点的任何信息

### 问题描述：
网速太慢了，更新完节点（删除节点，手动更新订阅）后测速，很多都是failed，选取了1.5的香港节点，测速显示的是88ms 但加载图片类网页非常慢，打开Gmail网页邮箱也很慢，上个月有段时间，大概月底，打开YouTube也很卡，看360画质的视频，缓存10分钟，畅看1分钟。。。 如果网络一直都这么慢，真不知道要不要继续订购了

### 备注：
- [常见问题列表](https://github.com/cg3s/forum/wiki/)
- [已解决问题列表](https://github.com/cg3s/forum/issues?q=is%3Aissue+is%3Aclosed)
- 如想立即得到我们的回复，请在我们的工作时间内提交问题（工作日的10:00-17:00）
- 如需上传截图，对敏感信息马赛克后拖拽或拷贝图片到本编辑器中即可。

**Comment by cg3s** [comment]
我们看您是在新疆而且还是移动，翻墙肯定体验不佳，建议您换电信或者换平台（我们可给您退款）
