### ISSUE TITLE
如何进行全局代理

### ISSUE THREAD

**Issue by RootGame** [cg3s/forum#276]
**因本问答区会被搜索引擎索引，我们禁止在问答区暴露本站域名及节点信息，一旦出现，我们将立即删除您发起的提问**

## 提交问题请按照格式填写
```因不严格按照格式填写，不严格按照教程操作导致的问题，可能不会得到我们及时的处理。```

- 账户邮箱： ```752020XXX@qq.com```

- 操作系统：Windows

### 提交前的必要步骤

- [x] 已更新节点列表 

- [x] 已查看最新系统公告

- [x] 已查看常见问题列表

- [x] 已搜索已解决问题列表

### 问题描述：
我使用了PAC 以及 全局代理，发现不管如何都会对国内IP和国外IP进行一次判断，然后决定是否走SSR；

我下载了proxifier，配置了全局代理，并且CMD里面ping www.google.com 可以得到正确响应；但是我打开百度，搜索ip，ip显示依旧是国内的IP；

我想整个PC端所有走代理，请问怎么解决？应该选取SSR什么选项啊

![QQ截图20200410150242](https://user-images.githubusercontent.com/4942508/78970755-a7b2f980-7b3c-11ea-9b26-8a8cd36c583a.png)
![QQ截图20200410150256](https://user-images.githubusercontent.com/4942508/78970762-a97cbd00-7b3c-11ea-8541-2f765c106548.png)
![QQ截图20200410150308](https://user-images.githubusercontent.com/4942508/78970764-aa155380-7b3c-11ea-8f93-fadb749793ac.png)
![QQ截图20200410150340](https://user-images.githubusercontent.com/4942508/78970765-aaadea00-7b3c-11ea-8327-78a51b51d794.png)
不知道为什么图片无法预览

**Comment by cg3s** [comment]
请按照格式填写

**Comment by cg3s** [comment]
代理规则改为全局就行了
