### ISSUE TITLE
未知原因，账号被封

### ISSUE THREAD

**Issue by zhangjian0731** [cg3s/forum#277]
- 账户邮箱： 
 46139***5@qq.com
- 操作系统：iOS

**Comment by cg3s** [comment]
从您账户的登录记录和ip在线记录来看，我们怀疑您的账号有异地分享使用的情况，所以禁用处理。

**Comment by cg3s** [comment]
-- | -- | -- | --
说来有点可笑 | 北京市朝阳区联通 | 2020-04-16 00:17:36 | 成功
说来有点可笑 | 上海市电信 | 2020-03-19 21:47:04 | 成功
说来有点可笑 | 北京市朝阳区联通 | 2020-03-07 15:41:00 | 成功
说来有点可笑 | 上海市移动 | 2020-02-27 00:35:38 | 成功
说来有点可笑 | 上海市电信 | 2020-02-24 15:34:59 | 成功
**说来有点可笑 | 上海市电信 | 2020-02-21 18:50:36 | 成功**
**说来有点可笑 | 北京市联通 | 2020-02-21 00:50:19 | 成功**
说来有点可笑 | 上海市移动 | 2020-02-19 16:53:30 | 成功
**说来有点可笑 | 上海市移动 | 2020-02-19 16:53:24 | 失败**
**说来有点可笑 | 北京市联通 | 2020-02-19 16:36:56 | 成功**
**说来有点可笑 | 北京市联通 | 2020-02-19 16:30:20 | 成功**
**说来有点可笑 | 上海市电信 | 2020-02-18 15:29:19 | 成功**
**说来有点可笑 | 北京市联通 | 2020-02-18 10:46:40 | 成功**
**说来有点可笑 | 上海市移动 | 2020-02-18 10:26:35 | 成功**
**说来有点可笑 | 上海市移动 | 2020-02-17 12:23:19 | 成功**
**说来有点可笑 | 北京市联通 | 2020-02-17 11:23:28 | 成功**
说来有点可笑 | 安徽省宿州市电信 | 2020-01-28 00:32:50 | 成功
**说来有点可笑 | 北京市电信 | 2019-12-23 13:30:01 | 成功**
**说来有点可笑 | 上海市电信 | 2019-12-23 10:24:03 | 成功**
说来有点可笑 | 安徽省淮南市电信 | 2019-12-21 14:58:44 | 成功
说来有点可笑 | 安徽省淮南市电信 | 2019-12-20 20:56:11 | 成功
说来有点可笑 | 上海市杨浦区电信 | 2019-11-25 15:57:20 | 成功
说来有点可笑 | 北京市联通 | 2019-09-29 14:38:30 | 成功
说来有点可笑 | 上海市移动 | 2019-09-17 20:00:54 | 成功
说来有点可笑 | 北京市联通 | 2019-09-13 08:05:08 | 成功
说来有点可笑 | 安徽省淮南市电信 | 2019-09-12 19:53:24 | 成功
说来有点可笑 | 北京市联通 | 2019-09-11 22:46:07 | 成功
说来有点可笑 | 北京市联通 | 2019-07-20 12:15:46 | 成功
说来有点可笑 | 上海市杨浦区电信 | 2019-07-08 10:02:07 | 成功
说来有点可笑 | 上海市徐汇区电信 | 2019-06-05 10:23:55 | 成功
说来有点可笑 | 上海市电信 | 2019-05-29 10:09:41 | 成功
说来有点可笑 | 上海市电信 | 2019-04-08 17:00:09 | 成功
说来有点可笑 | 北京市联通 | 2019-03-13 00:26:28 | 成功
说来有点可笑 | 浙江省电信 | 2019-02-03 19:44:33 | 失败
说来有点可笑 | 浙江省电信 | 2019-02-03 19:44:16 | 失败
说来有点可笑 | 浙江省杭州市电信 | 2019-01-01 02:01:20 | 成功
说来有点可笑 | 浙江省杭州市电信 | 2018-12-29 12:30:26 | 成功
说来有点可笑 | 北京市鹏博士宽带 | 2018-12-26 12:40:50 | 成功
说来有点可笑 | 浙江省杭州市电信 | 2018-12-19 20:18:58 | 成功
说来有点可笑 | 北京市联通 | 2018-12-13 00:15:47 | 成功
说来有点可笑 | 浙江省杭州市电信 | 2018-12-08 12:10:05 | 成功
说来有点可笑 | 北京市鹏博士宽带 | 2018-11-20 13:12:06 | 成功
说来有点可笑 | 浙江省杭州市电信 | 2018-11-06 20:30:56 | 成功
说来有点可笑 | 浙江省杭州市电信 | 2018-10-27 19:28:04 | 成功
说来有点可笑 | 浙江省电信 | 2018-10-20 17:43:13 | 成功
说来有点可笑 | 浙江省杭州市电信 | 2018-10-14 18:40:04 | 成功
说来有点可笑 | 浙江省杭州市电信 | 2018-10-11 10:24:25 | 成功
说来有点可笑 | 北京市鹏博士宽带 | 2018-09-26 09:47:31 | 成功
说来有点可笑 | 北京市联通 | 2018-09-25 22:42:27 | 成功
说来有点可笑 | 北京市联通 | 2018-09-23 15:37:54 | 成功
说来有点可笑 | 北京市联通 | 2018-09-11 00:01:36 | 成功
说来有点可笑 | 浙江省杭州市电信 | 2018-08-20 11:28:23 | 成功
说来有点可笑 | 安徽省淮南市电信 | 2018-07-29 12:51:35 | 成功
说来有点可笑 | 北京市联通 | 2018-07-28 13:47:10 | 成功
说来有点可笑 | 北京市联通 | 2018-07-26 21:36:20 | 成功
说来有点可笑 | 安徽省安庆市电信 | 2018-07-25 13:05:22 | 成功
说来有点可笑 | 浙江省杭州市电信 | 2018-06-14 13:39:13 | 成功
说来有点可笑 | 广东省深圳市移动 | 2018-06-09 08:44:33 | 成功
说来有点可笑 | 广东省深圳市移动 | 2018-05-09 21:12:08 | 成功
说来有点可笑 | 浙江省杭州市电信 | 2018-04-16 21:40:23 | 成功
说来有点可笑 | 北京市联通 | 2018-04-16 21:32:14 | 成功
说来有点可笑 | 北京市联通 | 2018-03-11 14:13:23 | 成功
说来有点可笑 | 安徽省安庆市电信 | 2018-02-19 21:45:14 | 成功
说来有点可笑 | 北京市朝阳区联通 | 2017-12-14 21:12:48 | 成功
说来有点可笑 | 北京市联通 | 2017-12-12 19:53:53 | 成功
说来有点可笑 | 北京市光环新网 | 2017-11-15 14:14:30 | 成功
说来有点可笑 | 河北省廊坊市联通 | 2017-10-11 21:47:55 | 成功
说来有点可笑 | 江西省南昌市电信 | 2017-10-04 13:39:56 | 成功
说来有点可笑 | 北京市光环新网 | 2017-10-01 15:28:52 | 成功
说来有点可笑 | 河北省廊坊市联通 | 2017-09-30 22:47:23 | 成功
说来有点可笑 | 河北省廊坊市联通 | 2017-09-30 22:44:08 | 成功
说来有点可笑 | 河北省廊坊市联通 | 2017-09-06 22:20:16 | 成功
说来有点可笑 | 安徽省马鞍山市电信 | 2017-09-05 23:28:52 | 成功
说来有点可笑 | 河北省廊坊市联通 | 2017-08-27 10:16:36 | 成功
**说来有点可笑 | 河北省廊坊市联通 | 2017-08-20 23:29:55 | 成功**
**说来有点可笑 | 安徽省安庆市电信 | 2017-08-20 23:28:34 | 成功**
**说来有点可笑 | 广东省东莞市电信 | 2017-08-20 23:26:30 | 成功**
**说来有点可笑 | 河北省廊坊市联通 | 2017-08-20 23:24:59 | 成功**
说来有点可笑 | 广东省广州市移动 | 2017-08-16 13:12:13 | 成功
**说来有点可笑 | 广东省广州市移动 | 2017-08-06 23:55:28 | 成功**
**说来有点可笑 | 河北省廊坊市联通 | 2017-08-06 23:38:57 | 成功**
说来有点可笑 | 河北省廊坊市联通 | 2017-08-05 23:30:25 | 成功
说来有点可笑 | 河北省廊坊市联通 | 2017-08-05 23:11:04 | 成功
说来有点可笑 | 北京市263网络通信股份有限公司 | 2017-08-05 12:27:39 | 成功
说来有点可笑 | 北京市光环新网 | 2017-08-04 12:58:42 | 成功
说来有点可笑 | 北京市光环新网 | 2017-07-27 12:53:19 | 成功
说来有点可笑 | 北京市263网络通信股份有限公司 | 2017-07-27 12:29:23 | 成功
说来有点可笑 | 河北省廊坊市联通 | 2017-07-23 12:19:25 | 成功
说来有点可笑 | 河北省廊坊市联通 | 2017-07-23 12:19:14 | 失败
说来有点可笑 | 河北省廊坊市联通 | 2017-07-23 10:34:51 | 成功
说来有点可笑 | 北京市263网络通信股份有限公司 | 2017-07-20 09:40:46 | 成功
说来有点可笑 | 安徽省合肥市电信 | 2017-07-19 23:00:34 | 成功
说来有点可笑 | 河北省廊坊市联通 | 2017-07-01 18:13:31 | 成功
说来有点可笑 | 河北省廊坊市联通 | 2017-06-13 21:23:47 | 成功
说来有点可笑 | 河北省廊坊市联通 | 2017-05-29 10:07:21 | 成功
说来有点可笑 | 北京市光环新网 | 2017-05-23 15:28:40 | 成功
说来有点可笑 | 内蒙古呼伦贝尔市联通 | 2017-05-11 21:25:13 | 成功
说来有点可笑 | 安徽省阜阳市界首市电信 | 2017-04-29 08:45:47 | 成功
说来有点可笑 | 北京市电信 | 2017-04-27 11:45:07 | 成功
说来有点可笑 | 北京市光环新网 | 2017-04-27 10:54:23 | 成功
说来有点可笑 | 安徽省阜阳市界首市电信 | 2017-04-27 10:34:59 | 成功
说来有点可笑 | 广东省佛山市电信 | 2017-04-27 10:34:50 | 成功
说来有点可笑 | 北京市电信 | 2017-04-26 13:55:52 | 成功
说来有点可笑 | 内蒙古呼伦贝尔市联通 | 2017-04-25 21:35:28 | 成功
说来有点可笑 | 内蒙古呼伦贝尔市联通 | 2017-04-12 20:35:47 | 成功
说来有点可笑 | 湖南省湘潭市联通 | 2017-03-29 22:37:45 | 成功
说来有点可笑 | 内蒙古赤峰市电信 | 2017-02-27 12:22:03 | 成功
说来有点可笑 | 内蒙古赤峰市电信 | 2017-02-26 22:17:22 | 成功

以上加粗部分表现为异地同时登录，此情况我们大概率判断为有分享账号嫌疑

**Comment by zhangjian0731** [comment]
我手机是南方电信卡，我在北京工作，这两年我还经常换租房子，换公司，ip变动难免多。我知道ip跳动多，但至于为什么地址变动多变动这么大，我真不太懂。。之前以为账号被盗还问过客服过。我就经常更换密码。我是老用户了，当然知道使用规则。。能尽快帮我解封吗？

**Comment by cg3s** [comment]
| | | |
|---|---|---|
|223.214.215.75 | 安徽省池州市电信 | 1小时前|
|221.218.178.23 | 北京市朝阳区联通 | 10小时前|
这是您最近两次的登录记录，也表现为异常

账户已解封

您关注下您账户的登录ip和在线ip情况，并用 https://www.ipip.net/ip.html 进行ip查询

**Comment by cg3s** [comment]
| | | | | |
|---|---|---|---|---|---|
|说来有点可笑 | 223.214.215.75 | 安徽省池州市电信 | 2020-04-16 08:20:11 | Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.3319.102 Safari/537.36|
|说来有点可笑 | 221.218.178.23 | 北京市朝阳区联通 | 2020-04-15 23:33:28 | Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.3319.102 Safari/537.36|
|说来有点可笑 | 183.162.19.73 | 安徽省合肥市电信 | 2020-04-15 07:59:14 | Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.3319.102 Safari/537.36|

还有这个订阅记录也表现为异常

**Comment by cg3s** [comment]
感谢您一直以来的支持！

之前我们一般检测到频繁跳ip的情况一般移动用户多点，暂未发现电信也会有此类情况，因为电信的ip相对都比较固定的，很少出现跳ip情况。

如果是因为电信卡频繁跳ip，我们将用电信卡进行测试，但是为了杜绝分享账户的行为，我们也必须采取一定的措施，为您造成的不便敬请谅解。

**Comment by zhangjian0731** [comment]
我这张手机卡，自打使用以来就一直有跳ip的情况，具体的我也不太懂。之前就因为跳ip被封过一次。谢谢帮我解封。

**Comment by cg3s** [comment]
我们再观察观察。
