### ISSUE TITLE
商品售价是否能考虑学生优惠？

### ISSUE THREAD

**Issue by xiaolong7508** [cg3s/forum#278]
## 提交问题请按照格式填写

- 账号：(后台可模糊查询，请打码处理，如12345678@qq.com可填写为123xxx78@qq.com)

- 操作系统：[Windows|Mac|Linux|iOS|Android|路由器]

- [] 是否已更新节点列表 ```(是: 在[]内填 x, 否: 留空) ```

- [] 是否已查看最新系统公告

- [] 是否已查看常见问题列表

- [] 是否已搜索已解决问题列表

**本问答为公开页面，为保护我们的服务安全和您的个人隐私，如截图中含有以下敏感信息，请马赛克处理。**
- 本站网址
- 本站节点的任何信息

### 问题描述：

为什么套餐价格现在涨这么多？ 能不能考虑一下学生党的承受能力啊！

### 备注：
- [常见问题列表](https://github.com/cg3s/forum/wiki/)
- [已解决问题列表](https://github.com/cg3s/forum/issues?q=is%3Aissue+is%3Aclosed)
- 如想立即得到我们的回复，请在我们的工作时间内提交问题（工作日的10:00-17:00）
- 如需上传截图，对敏感信息马赛克后拖拽或拷贝图片到本编辑器中即可。

**Comment by cg3s** [comment]
我们考虑过为学生减免，但因为敏感因素不太好让学生来上传真实数据。如果您觉得贵我们可以临时开放轻量版让您购买，轻量版流量每月25G，年付96元

**Comment by cg3s** [comment]
至于涨价的原因，请看我们3月2日的公告，然后您也可以对比下其他平台，我们的定价我们自认为是合理的，尤其是长期稳定不跑路的情况下。

然后其实您也可以用积分发起众筹，通过积分换购福利（比如买套教程之类的），或者邀请他人，一般都能轻松抵消订阅费用的。

在我们看来这是划算的，我们也很愿意为用户提供CG类的福利兑换。

**Comment by eetommy** [comment]
请问最高一档多少钱呀

> 至于涨价的原因，请看我们3月2日的公告，然后您也可以对比下其他平台，我们的定价我们自认为是合理的，尤其是长期稳定不跑路的情况下。
> 
> 然后其实您也可以用积分发起众筹，通过积分换购福利（比如买套教程之类的），或者邀请他人获得返利，一般都能轻松抵消订阅费用的，在我们看来对于用户这是划算的，我们也很愿意为用户提供CG类的福利兑换。
> 
> 尤其是您也可以将获得的返利转账给他人，然后通过他人付款给您，从而达到提现的效果的。

**Comment by cg3s** [comment]
@eetommy 您是我们用户么？

**Comment by eetommy** [comment]
您好，目前还不是，请问怎么样成为用户？谢谢。

2020年5月11日(月) 21:24 CGS小管家 <notifications@github.com>:

**Comment by xiaolong7508** [comment]
必须是你们用户啊


















在 2020-05-11 21:24:32，"CGS小管家" <notifications@github.com> 写道：

@eetommy 您是我们用户么？
