### ISSUE TITLE
为什么我续费完节点都用不了。

### ISSUE THREAD

**Issue by A771279176** [cg3s/forum#28]
我昨天续费完，然后今天更新节点，还是翻不了墙

**Comment by cg3s** [comment]
账户多少？

**Comment by A771279176** [comment]
> 账户多少？
> 提交订单后点了结账么，更新之前先把代理关一下，然后再重新开代理

**Comment by A771279176** [comment]
付账了的。账号是 771279176@qq.com 我试了好久，还是不能上网

**Comment by cg3s** [comment]
@A771279176 最简单粗暴的方式就删掉软件重新按教程走一遍
