### ISSUE TITLE
账号突然被封了，还有9个月

### ISSUE THREAD

**Issue by lkw019** [cg3s/forum#280]
## 提交问题请按照格式填写

- 账号：30148xxx78@qq.com

- 操作系统：[Windows|Mac|Linux|iOS|Android|路由器]

- [] 是否已更新节点列表 ```(是: 在[]内填 x, 否: 留空) ```

- [] 是否已查看最新系统公告

- [] 是否已查看常见问题列表

- [] 是否已搜索已解决问题列表

**本问答为公开页面，为保护我们的服务安全和您的个人隐私，如截图中含有以下敏感信息，请马赛克处理。**
- 本站网址
- 本站节点的任何信息

### 问题描述：

大哥，怎么封我账号了，啥意思，不带这样的吧

### 备注：
- [常见问题列表](https://github.com/cg3s/forum/wiki/)
- [已解决问题列表](https://github.com/cg3s/forum/issues?q=is%3Aissue+is%3Aclosed)
- 如想立即得到我们的回复，请在我们的工作时间内提交问题（工作日的10:00-17:00）
- 如需上传截图，对敏感信息马赛克后拖拽或拷贝图片到本编辑器中即可。

**Comment by cg3s** [comment]
系统有发禁用提示邮件，里面有详细解释，请检查下您的邮箱

**Comment by lkw019** [comment]
> 请看邮件内容

30148xxx78@qq.com  这个邮件吗，
