### ISSUE TITLE
关于近期平台调整

### ISSUE THREAD

**Issue by cg3s** [cg3s/forum#281]
2020-04-23 20:52: 这两天可能是我们成立以来应急维护工作量最大的一次。我们其实是在全新开发v2ray方案的，但墙发力来得太快，进度暂时赶不上，所以逼着我们研究最快的方案了，也算件好事，deadline就是生产力。

新平台只是临时救急，不一定会替换现在的平台。

我们目前正开发部署v2ray到现在的平台，开发完成即可无缝衔接。

**Comment by Cocokathy** [comment]
您好 现在平台调整期 所以不能使用小飞机了么？

**Comment by cg3s** [comment]
ssr其实早就不安全了，v2ray会安全很多，主要完全模拟了https流量，基本上得放弃ssr了。
后面会着重提供v2ray和trojan的服务。

**Comment by xtvjxk123456** [comment]
没看到什么公共账户啊

**Comment by cg3s** [comment]
@xtvjxk123456 因为要鉴权，放到了appleid的账户4里

**Comment by huraylu** [comment]
现在WIN7 SSR用不了？

**Comment by cg3s** [comment]
@huraylu ssr我们目前暂停维护（精力不足），您可以用新平台的服务。

**Comment by huraylu** [comment]
> @huraylu ssr我们目前暂停维护（精力不足），您可以用新平台的服务。

那ssr还有使用期限怎么处理？另外新平台邮箱注册无法收到验证码？QQ的

**Comment by Fanwen-J** [comment]
你好，可以具体说一下邮箱密码放到哪里了吗，没懂账户4在哪里，没有找到

**Comment by cg3s** [comment]
@huraylu 目前新平台只是临时过渡，因为ssr我们维护不过来，用v2ray可缓解一下
原来的平台不一定会弃用，我们在考虑在现有平台支持v2ray，只是需要点时间。新平台你们只管拿我们提供的账户用就行，现有平台也不需要管，反正保证用户正常使用性质也一样。只是应急。
新平台很多东西还没完全好，注册进来数据会乱，所以暂不开放，我希望能尽量减少用户麻烦。

**Comment by cg3s** [comment]
@Fanwen-J 在教程 iOS里的  “B. 使用本站Apple ID免费下载” 里

**Comment by huraylu** [comment]
明白了，谢谢你的解答。

**Comment by Fanwen-J** [comment]
> @ Fanwen-J在教程iOS里的 使用本站Apple ID免费下载”里

好的好的 感谢

**Comment by kissinger31** [comment]
临时的节点是要用v2ray程序吗？复制链接节点以后要怎么操作。

**Comment by cg3s** [comment]
@kissinger31 您可以百度下软件名，会有很多详细图文教程。

**Comment by kissinger31** [comment]
谢谢，已解决

**Comment by yzwCode** [comment]
> 你好，可以具体说一下邮箱密码放到哪里了吗，没懂账户4在哪里，没有找到

就在ios教程页面的第二个选项卡中，你把第一个折叠起来就更清晰看到了

**Comment by hrnun** [comment]
请问是否临时线路不太稳定？
刚才还可以（北京时间23:00左右），但现在23:30显示线路失败。
请看图～
<img width="183" alt="截屏2020-04-23 下午11 29 55" src="https://user-images.githubusercontent.com/52479830/80118093-86c9ba00-85ba-11ea-9cc3-59fbfa0a6726.png">

以及配置这里的选择为CGRAY对吗？
<img width="392" alt="截屏2020-04-23 下午11 31 30" src="https://user-images.githubusercontent.com/52479830/80118240-b7a9ef00-85ba-11ea-8a3e-cdefc82ad54c.png">

感谢解答！

**Comment by cg3s** [comment]
v2ray全部掉线了，应该是共享账户人数太多，导致集体掉线了

我们已对ssr全部修改端口，需要再次刷新列表

同时我们将两边进行维护，争取错开墙的时间差

**Comment by cg3s** [comment]
@hrnun 

v2ray全部掉线了，应该是共享账户人数太多，导致集体掉线了

我们已对ssr全部修改端口，需要再次刷新列表

同时我们将两边进行维护，争取错开墙的时间差

**Comment by Cocokathy** [comment]
> 您说的小飞机其实用ssr更准确，目前ssr其实不安全了，v2ray会安全很多，主要完全模拟了https流量，基本上得放弃ssr了。
> 后面我们会着重提供v2ray和trojan的服务。

我了解了一下v2ray 确实是比ssr/ss 有很大的优势，那我们需要再购买vps吗？

**Comment by cg3s** [comment]
vps? 您是说vpn吧，用户在cgs上的数据我们后期会自动同步，目前衔接功能还没做好，所以需要手动过渡。在cgs的所有权限都会同步到cgr上，后期我们想把cgr的功能无缝导入到cgs里，这样用户不用关心cgr，目前只是只是只是过渡。

**Comment by cg3s** [comment]
v2ray/trojan最大的优势就是真实模拟tls握手协议，墙要发力很难对https tls协议进行识别，即使能识别也会造成网络瘫痪。当然这需要将v2ray/trojan运用得好才行，配置不当也会出问题。

**Comment by Cocokathy** [comment]
> vps? 您是说vpn吧，用户在cgs上的数据我们后期会自动同步，目前衔接功能还没做好，所以需要手动过渡。在cgs的所有权限都会同步到cgr上，后期我们想把cgr的功能无缝导入到cgs里，这样用户不用关心cgr，目前只是只是只是过渡。

<img width="824" alt="屏幕快照 2020-04-24 上午11 35 44" src="https://user-images.githubusercontent.com/43667841/80172530-cecef800-861f-11ea-9a0e-d543b5e4d570.png">

过渡的话 那我明白啦，最好是不要操作太复杂。因为我看网上说使用v2ray 比较复杂，还需要自己搭建虚拟机服务器，所以就比较担心

**Comment by cg3s** [comment]
@Cocokathy 您看的是搭机场的教程，不是使用机场的教程，搭建机场是我们干的事

**Comment by Cocokathy** [comment]
懂啦懂啦，辛苦你们啦啦啦啦

**Comment by xtvjxk123456** [comment]
已注册 1

**Comment by jx-94** [comment]
IOS端下载用的ID好像被锁了
