### ISSUE TITLE
我都没有使用，360也关闭了，为何还说我违规50次，每天晚上10点邮件说我被封禁。

### ISSUE THREAD

**Issue by asker8023** [cg3s/forum#282]
我不知道是什么程序引起的，麻烦后台看下。我没有开飞机。360还监测到我违规，这是为什么、

**Comment by cg3s** [comment]
一般来说是后台有360的软件在跟360官网通信，然后走了代理，或者你用了360的浏览器，访问外网过程中就会有360通信记录，因为这两天墙发力，我们也就是临时做一下检测处理，一般一年也就几次。

ps: 用360产品的我们一般都劝退，用户觉得被禁很烦的，可以发下微信收款码，我们退款。
