### ISSUE TITLE
现在新平台无法看视频？

### ISSUE THREAD

**Issue by yzwCode** [cg3s/forum#283]
**因本问答区会被搜索引擎索引，我们禁止在问答区暴露本站域名及节点信息，一旦出现，我们将立即删除您发起的提问**

## 提交问题请按照格式填写
```因不严格按照格式填写，不严格按照教程操作导致的问题，可能不会得到我们及时的处理。```

- 账户邮箱： 
```请马赛克处理，如123456@qq.com改成12xxx56@qq.com，我们可模糊查询```

- 操作系统：[Windows|Mac|Linux|iOS|Android|路由器] 
```保留一项即可```

### 提交前的必要步骤
```(是: 在[]内填 x, 否: 留空) ```

- [] 是否已更新节点列表 

- [] 是否已查看最新系统公告

- [] 是否已查看常见问题列表

- [] 是否已搜索已解决问题列表

**本问答为公开页面，为保护我们的服务安全和您的个人隐私，文字与截图中禁止出现以下信息，文字请用其他词汇代替，图片请马赛克处理。**
- 本站网址
- 本站节点的任何信息

### 备注：
- [常见问题列表](https://github.com/cg3s/forum/wiki/常见问题列表)
- [已解决问题列表](https://github.com/cg3s/forum/issues?q=is%3Aissue+is%3Aclosed)
- 如想立即得到我们的回复，请在我们的工作时间内提交问题（工作日的10:00-17:00），大多数时候我们能保持快速响应，但不排除我们的工作人员在忙其他的事情，如果我们没有及时回应，请耐心等待。
- 如需上传截图，对敏感信息马赛克后拖拽或拷贝图片到本编辑器中即可。

**Comment by cg3s** [comment]
什么视频？youtube？是现有平台还是新平台

**Comment by yzwCode** [comment]
> 什么视频？youtube？是现有平台还是新平台

新平台，youtube看视频，会告诉我未知的流量，然后通过谷歌的人机认证就可以了。现在问题解决了，另外什么时候我们能像旧平台一样愉快的使用梯子

**Comment by cg3s** [comment]
人机验证以前也会出现

墙发力的时候基本都会比较难过，撑过这段时间就好了，反正每次我们也都抗过来了，这次我们重点部署v2ray方案，采用两套系统，目前正在做无缝切换的功能，从而避免用户麻烦。
