### ISSUE TITLE
怎么这么恼火，更新后还看不到一个节点！

### ISSUE THREAD

**Issue by ohyawen** [cg3s/forum#289]
## 提交问题请按照格式填写

- 账号：329xxx248@qq.com

- 操作系统：Windows

- [x] 是否已更新节点列表

- [x] 是否已查看最新系统公告

您好，在网站上看到你们说回复正常了。第一，你们的网站真是超级慢，等一个界面要好几分钟。

第二，重新复制了订阅链接，更新了节点，结果节点选项里只有‘剩余流量’‘过期时间’。

究竟是怎么回事？

谢谢！

**Comment by ohyawen** [comment]
用v2ray也不行，几个新加坡节点全是红色，没有一个可行的办法，工作邮件无法回复。请问怎么解决？？？

**Comment by cg3s** [comment]
一般按教程重新走一遍就行

**Comment by cg3s** [comment]
cgr我们正在更换服务器，目前因为延迟比较高，所以更新订阅需要多试几次。

**Comment by cg3s** [comment]
红色就是可用的，只要不是灰色就行，v2ray的延迟会比ssr高很多，在windows里用tping测试延迟才和ssr一致。

抱歉，主要昨天人工工作量比较大，后来看ssr服务均已正常，为了避免用户切换平台的麻烦，就暂时关闭在线客服了。

现在有什么问题可以直接联系在线客服。

**Comment by cg3s** [comment]
cgs的网站一直都慢的，我们有时候认为慢点会更安全，比那些需要翻墙才能开的安全很多。
