### ISSUE TITLE
点击订阅，出现服务器错误500，究竟如何解决？？？？

### ISSUE THREAD

**Issue by xuyuanze** [cg3s/forum#29]
点击订阅，出现服务器错误500，究竟如何解决？？？？

**Comment by xuyuanze** [comment]
更改DNS 依然出现 服务器错误500  常见问题中 哪一条能解决这个问题呢

**Comment by cg3s** [comment]
文档/常见问题列表 购买 / 3.页面出现500服务器错误或购买卡密出现违规警示 有解释

**Comment by xuyuanze** [comment]
好难啊 整了 一下午 没看到你说的这个东西呢

**Comment by cg3s** [comment]
chrome的话 按下 ctrl+F5键

**Comment by xuyuanze** [comment]
终于找到了！！！
