### ISSUE TITLE
电脑端一直显示服务器订阅更新失败，不能使用，不知道怎么回事，

### ISSUE THREAD

**Issue by 909754123** [cg3s/forum#290]
**因本问答区会被搜索引擎索引，我们禁止在问答区暴露本站域名及节点信息，一旦出现，我们将立即删除您发起的提问**

## 提交问题请按照格式填写
```因不严格按照格式填写，不严格按照教程操作导致的问题，可能不会得到我们及时的处理。```

- 账户邮箱： 
```请马赛克处理，如123456@qq.com改成12xxx56@qq.com，我们可模糊查询```

- 操作系统：[Windows|Mac|Linux|iOS|Android|路由器] 
```保留一项即可```

### 提交前的必要步骤
```(是: 在[]内填 x, 否: 留空) ```

- [] 是否已更新节点列表 

- [] 是否已查看最新系统公告

- [] 是否已查看常见问题列表

- [] 是否已搜索已解决问题列表

**本问答为公开页面，为保护我们的服务安全和您的个人隐私，文字与截图中禁止出现以下信息，文字请用其他词汇代替，图片请马赛克处理。**
- 本站网址
- 本站节点的任何信息

### 备注：
- [常见问题列表](https://github.com/cg3s/forum/wiki/常见问题列表)
- [已解决问题列表](https://github.com/cg3s/forum/issues?q=is%3Aissue+is%3Aclosed)
- 如想立即得到我们的回复，请在我们的工作时间内提交问题（工作日的10:00-17:00），大多数时候我们能保持快速响应，但不排除我们的工作人员在忙其他的事情，如果我们没有及时回应，请耐心等待。
- 如需上传截图，对敏感信息马赛克后拖拽或拷贝图片到本编辑器中即可。

**Comment by cg3s** [comment]
看下所选端口是否和我们公告说的一致

**Comment by 909754123** [comment]
> 看下所选端口是否和我们公告说的一致

- -端口怎么看啊。。

**Comment by cg3s** [comment]
哦，你是更新订阅失败，那就按教程重新走一遍吧

**Comment by cg3s** [comment]
端口认准 9001

**Comment by 909754123** [comment]
> 哦，你是更新订阅失败，那就按教程重新走一遍吧

重新设置很多次了，，还是不行，端口怎么看啊。。。9001是我自己手动输入还是？？？？

**Comment by cg3s** [comment]
订阅设置链接没粘贴进去吧

**Comment by 909754123** [comment]
> 订阅设置链接没粘贴进去吧

进去了。。

**Comment by 909754123** [comment]
> 订阅设置链接没粘贴进去吧

你能帮我远程操作一下吗。。。我真的是不知道怎么搞了。我是做外贸的，急死了。。

**Comment by cg3s** [comment]
你发下向日葵识别码吧

**Comment by 909754123** [comment]
> 向日葵识别码

637 229 437

**Comment by cg3s** [comment]
下次请按严格按照教程操作。

**Comment by 909754123** [comment]
> 下次请按严格按

> 下次请按严格按照教程操作。

好的，谢谢。。。

**Comment by cg3s** [comment]
不客气
