### ISSUE TITLE
解析 gui-c*****.****啥啥出错，可能需要密码解密，这个密码是啥，我输入我的密码不对啊

### ISSUE THREAD

**Issue by lyh521133** [cg3s/forum#293]
**因本问答区会被搜索引擎索引，我们禁止在问答区暴露本站域名及节点信息，一旦出现，我们将立即删除您发起的提问**

## 提交问题请按照格式填写
```因不严格按照格式填写，不严格按照教程操作导致的问题，可能不会得到我们及时的处理。```

- 账户邮箱： 
```请马赛克处理，如123456@qq.com改成12xxx56@qq.com，我们可模糊查询```

- 操作系统：[Windows|Mac|Linux|iOS|Android|路由器] 
```保留一项即可```

### 提交前的必要步骤
```(是: 在[]内填 x, 否: 留空) ```

- [] 是否已更新节点列表 

- [] 是否已查看最新系统公告

- [] 是否已查看常见问题列表

- [] 是否已搜索已解决问题列表

**本问答为公开页面，为保护我们的服务安全和您的个人隐私，文字与截图中禁止出现以下信息，文字请用其他词汇代替，图片请马赛克处理。**
- 本站网址
- 本站节点的任何信息

### 备注：
- [常见问题列表](https://github.com/cg3s/forum/wiki/常见问题列表)
- [已解决问题列表](https://github.com/cg3s/forum/issues?q=is%3Aissue+is%3Aclosed)
- 如想立即得到我们的回复，请在我们的工作时间内提交问题（工作日的10:00-17:00），大多数时候我们能保持快速响应，但不排除我们的工作人员在忙其他的事情，如果我们没有及时回应，请耐心等待。
- 如需上传截图，对敏感信息马赛克后拖拽或拷贝图片到本编辑器中即可。

**Comment by lyh521133** [comment]
解析 gui-c*****.****啥啥出错，可能需要密码解密，这个密码是啥，我输入我的密码不对啊

**Comment by cg3s** [comment]
请按格式填写

**Comment by lyh521133** [comment]
[x] 是否已更新节点列表

[x] 是否已查看最新系统公告

[x] 是否已查看常见问题列表

[x] 是否已搜索已解决问题列表

**Comment by lyh521133** [comment]
Windows，解析 gui-c*****.****啥啥出错，可能需要密码解密，这个密码是啥，我输入我的密码不对啊

**Comment by cg3s** [comment]
我们从未遇到过此类情况，可以发个截图？

**Comment by lyh521133** [comment]
![微信图片_20200504125628](https://user-images.githubusercontent.com/64764942/80937193-b2447400-8e06-11ea-982b-e77746c5ba33.png)

**Comment by lyh521133** [comment]
我放在E盘了

**Comment by lyh521133** [comment]
![微信图片_20200504125628](https://user-images.githubusercontent.com/64764942/80937330-3bf44180-8e07-11ea-89f5-6ed7fb55ed2d.png)

**Comment by cg3s** [comment]
您有动过gui-config.json文件么，可以试下删除软件目录下的gui-config.json 重新按教程走一遍

**Comment by lyh521133** [comment]
好的，我试试

**Comment by lyh521133** [comment]
按照你的方法，已解决，谢谢~

**Comment by cg3s** [comment]
不客气
