### ISSUE TITLE
转到CGR按照说明操作还是无法fq

### ISSUE THREAD

**Issue by WOLOCao** [cg3s/forum#296]
## 提交问题请按照格式填写

- 账号：982xxx974@qq.com

- 操作系统：Windows

- [x] 是否已更新节点列表

- [x] 是否已查看最新系统公告

- [x] 是否已查看常见问题列表

- [x] 是否已搜索已解决问题列表

**本问答为公开页面，为保护我们的服务安全和您的个人隐私，如截图中含有以下敏感信息，请马赛克处理。**
- 本站网址
- 本站节点的任何信息

### 问题描述：
信息反馈：
2020/05/15 11:57:05 tcp:127.0.0.1:55963 accepted tcp:content-autofill.googleapis.com:443 [proxy] 
2020/05/15 11:57:05 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal)

### 备注：
- [常见问题列表](https://github.com/cg3s/forum/wiki/)
- [已解决问题列表](https://github.com/cg3s/forum/issues?q=is%3Aissue+is%3Aclosed)
- 如想立即得到我们的回复，请在我们的工作时间内提交问题（工作日的10:00-17:00）
- 如需上传截图，对敏感信息马赛克后拖拽或拷贝图片到本编辑器中即可。

**Comment by kangmiaomi** [comment]
我也是

**Comment by cg3s** [comment]
同步了时间么

**Comment by cg3s** [comment]
https://github.com/v2ray/v2ray-core/issues/2284
https://zhuanlan.zhihu.com/p/97526800
https://github.com/v2ray/v2ray-core/issues/1843
https://github.com/v2ray/v2ray-core/issues/653
https://github.com/v2ray/v2ray-core/issues/2284
参考以上回答

**Comment by cg3s** [comment]
https://download.visualstudio.microsoft.com/download/pr/014120d7-d689-4305-befd-3cb711108212/1f81f3962f75eff5d83a60abd3a3ec7b/ndp48-web.exe

另外请下载安装下这个，安装后重启下电脑试试

**Comment by WOLOCao** [comment]
> [v2ray/v2ray-core#2284](https://github.com/v2ray/v2ray-core/issues/2284)
> https://zhuanlan.zhihu.com/p/97526800
> [v2ray/v2ray-core#1843](https://github.com/v2ray/v2ray-core/issues/1843)
> [v2ray/v2ray-core#653](https://github.com/v2ray/v2ray-core/issues/653)
> [v2ray/v2ray-core#2284](https://github.com/v2ray/v2ray-core/issues/2284)
> 参考以上回答

同步系统时间后可以用了，谢谢

**Comment by cg3s** [comment]
好的，不客气
