### ISSUE TITLE
为什么申请不了V2的邮箱，不知道以前是否申请，如果有申请也收不到验证码，就是用同一个邮箱申请的。

### ISSUE THREAD

**Issue by cansey** [cg3s/forum#297]
账号：32147xxx@qq.com

操作系统：Windows

- [] 是否已更新节点列表 

- [] 是否已查看最新系统公告

- [] 是否已查看常见问题列表

**Comment by cansey** [comment]
说错了，是申请cgray的邮箱

**Comment by cg3s** [comment]
您是说的邮箱验证码？是需要找回密码，还是要注册呢

**Comment by cansey** [comment]
已经收到了，按照步骤操作后，显示订阅内容解码失败（非BASE64码）

**Comment by cansey** [comment]
更新订阅开始

**Comment by cansey** [comment]
订阅设置填写以后，然后更新订阅
更新订阅开始
1-》开始获取订阅内容
1-》获取订阅内容成功
1-》订阅内容解码失败（非BASE64码）

**Comment by cg3s** [comment]
你没订阅淘套餐，请看下公告里的使用须知
