### ISSUE TITLE
如何更改地址

### ISSUE THREAD

**Issue by cansey** [cg3s/forum#299]
- 账户邮箱： 321xxx97@qq.com，

- 操作系统：Windows

### 提交前的必要步骤
```(是: 在[]内填 x, 否: 留空) ```

 x [] 是否已更新节点列表 

 x [] 是否已查看最新系统公告

 x [] 是否已查看常见问题列表

- [] 是否已搜索已解决问题列表

请问在V2rayN里如何切换地址，因为好像网速不太好，比如默认是香港A1，如何切换新加坡A1，还有一个问题是如何更改ip地址？

**Comment by cg3s** [comment]
选择节点后enter就行，或者右键设为活动服务器

大家都选香港A1自然网速不好，您切换节点后自然就切换ip了。
