### ISSUE TITLE
订单一直被取消，联系个客服这么复杂

### ISSUE THREAD

**Issue by tony1847** [cg3s/forum#30]
![image](https://user-images.githubusercontent.com/82773882/115154759-12cbd000-a0af-11eb-8924-9ba85b4eba5c.png)

**Comment by cg3s** [comment]
问答区只是备用的客服方式，在遇到网站宕机的情况下，这里提问不会受影响
最直接的就提交工单，工作时间基本能实时秒回复。

提交订单后还需要点一下结账。
