### ISSUE TITLE
是否有国内节点

### ISSUE THREAD

**Issue by iotsin** [cg3s/forum#35]
意思是，添加国内的出口点，用于加速学校过滤机制的网站，延迟相对香港低一些

**Comment by cg3s** [comment]
那不就是中转方案？
徐州 杭州 中山 广州都是中转线路

**Comment by iotsin** [comment]
我在广州，用广州的中转就行了吧，是不是广州的IP地址，这样登录国内服务不会异地异常

**Comment by cg3s** [comment]
中转有落地ip，不会是接入地的ip，节点名里能看到落地地区，国内网站默认也不会走代理，更没有用国内节点来访问国内网站的需求一说，这种一般海外用户有这个需求，但一般不会有服务商去提供
