### ISSUE TITLE
账户已被停止使用

### ISSUE THREAD

**Issue by saibuhei** [cg3s/forum#38]
- 账户邮箱（必填）：
499xxx945@qq.com

- 操作系统：[Windows] 

### 提交前的必要步骤
```(是: 在[]内填 x, 否: 留空) ```

- [x] 是否已更新节点列表 

- [x] 是否已查看最新系统公告

- [x] 是否已查看常见问题列表

- [x] 是否已搜索已解决问题列表

### 问题描述：
9月9日发生账户被冻结现象

### 备注：
能确认自己使用没有站内规定，请告知原因
如果是因为被人吸引，我可以解释和说明，谢谢！

**Comment by cg3s** [comment]
您好，因为您邀请的用户 626422xxx@qq.com 修改了我们的AppleID的密码，造成我们的ID无法使用，迫使我们只能重新注册ID并且重新购买小火箭软件。

**Comment by saibuhei** [comment]
您好，我都不知道。如果修改回去的话你们还能用吗？&nbsp;
我和同事说一下，可能她不知道。有没有什么办法可以挽回？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cg3s/forum"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月15日(星期三) 凌晨0:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cg3s/forum] 账户已被停止使用 (#38)





 
您好，因为您邀请的用户 ***@***.*** 修改了我们的AppleID的密码，造成我们的ID无法使用，迫使我们只能重新注册ID并且重新购买小火箭软件。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by saibuhei** [comment]
您好，我和同事聊过了，确认没有修改你们的ID密码




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cg3s/forum"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月15日(星期三) 凌晨0:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cg3s/forum] 账户已被停止使用 (#38)





 
您好，因为您邀请的用户 ***@***.*** 修改了我们的AppleID的密码，造成我们的ID无法使用，迫使我们只能重新注册ID并且重新购买小火箭软件。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by saibuhei** [comment]
您好，不好意思。我刚刚和同事确认了，她是因为一直登录不了，然后是有修改过。
这里有什么办法可以帮我开通吗？ 她那边会愿意承担责任




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cg3s/forum"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月15日(星期三) 凌晨0:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cg3s/forum] 账户已被停止使用 (#38)





 
您好，因为您邀请的用户 ***@***.*** 修改了我们的AppleID的密码，造成我们的ID无法使用，迫使我们只能重新注册ID并且重新购买小火箭软件。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by saibuhei** [comment]
收到，感谢！ 后续我再邀请人的话会告诉他们仔细阅读合作条款




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cg3s/forum"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月17日(星期五) 晚上10:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cg3s/forum] 账户已被停止使用 (#38)





 
@saibuhei 您的账户已解封， ***@***.***的用户不再解封
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
