### ISSUE TITLE
为什么我选择了洛杉矶节点后ip并没有到美国

### ISSUE THREAD

**Issue by mymymy94** [cg3s/forum#56]
我需要到一个美国网站购物，但现在默认因为地址是在国内，就近跳转到日本官网，但我现在是选择了洛杉矶节点的，之前换了节点后成功定位到了美国一次，现在又不行了， 按道理换美国节点位置肯定在美国的吧，我用了下别的手机vpn，选了美国节点后网站是能成功跳转到美国的，不知道是不是我哪里选择的不对、希望给解答一下谢谢。

**Comment by cg3s** [comment]
洛杉矶的节点ip是在美国的，有可能你在pc上没有使用全局模式，代理规则没有切换到全局，导致访问这个美国购物网站使用的ip没有切换到洛杉矶节点上，手机vpn之所以能跳转，主要是手机上一般都是全局的。
