### ISSUE TITLE
如何进行退款

### ISSUE THREAD

**Issue by fionanico** [cg3s/forum#61]
提交问题前的注意事项：
1. 为了我们快速解决您的问题，请填上您的账号信息（如123456789@qq.com可改成123xxx789@qq.com填写，后台可模糊查询）

2. 遇到服务器连接不上，请首先查看公告。

3. 请先在 常见问题列表 和 已解决问题列表 中查看是否有同类情况。
  - 常见问题列表：https://github.com/cg3s/forum/wiki/
  - 已解决问题列表：https://github.com/cg3s/forum/issues?q=is%3Aissue+is%3Aclosed
  
4. 本问答为公开页面，为保护我们的服务安全和您的个人隐私，如截图中含有以下敏感信息，请马赛克处理。
  - 本站网址
  - 本站节点的任何信息
  - 您的账户邮箱（如123456789@qq.com可改成123xxx789@qq.com填写，后台可模糊查询）

如想立即得到我们的回复，请在我们的工作时间内提交问题（工作日的10:00-17:00）。

阅读完以上信息后，您可清空该内容并填写您的问题详情，如需上传截图，对敏感信息马赛克后拖拽图片到本编辑器中即可。

**Comment by fionanico** [comment]
如何退款呢？步骤是什么

**Comment by cg3s** [comment]
您账户是什么

**Comment by fionanico** [comment]
61323847@qq.com

**Comment by fionanico** [comment]
请问是退回微信上面吗？

**Comment by cg3s** [comment]
对的

**Comment by fionanico** [comment]
好的谢谢

**Comment by fionanico** [comment]
大概什么时候会收到退款呢？

**Comment by fionanico** [comment]
收款码？

**Comment by fionanico** [comment]
收款码在哪里找到？

**Comment by fionanico** [comment]
我有购买的订单号

**Comment by fionanico** [comment]
订单号： KM180906108210373277

**Comment by cg3s** [comment]
打开微信后，右上角“收付款”，然后选择二维码收款，把这个二维码发上来，我们才好给你转账。

**Comment by fionanico** [comment]
好的请稍等

**Comment by cg3s** [comment]
我们能查到你留的联系方式，但我们不会去加你微信好友，收款码可以匿名转账

**Comment by fionanico** [comment]
如何发图片？

**Comment by cg3s** [comment]
拖进来就行

**Comment by fionanico** [comment]
![_20180907103919](https://user-images.githubusercontent.com/43054164/45195540-b1062100-b28a-11e8-9c34-62ef51d03bfd.png)

**Comment by fionanico** [comment]
![_20180907104237](https://user-images.githubusercontent.com/43054164/45195563-d3983a00-b28a-11e8-9ddb-902bd72ad711.jpg)

**Comment by fionanico** [comment]
能看到了吗？

**Comment by cg3s** [comment]
不是这个，这是付款码（不要轻易外发），是下面的收款码

**Comment by fionanico** [comment]
![_20180907104547](https://user-images.githubusercontent.com/43054164/45195658-40133900-b28b-11e8-969f-011cfffa7bcb.jpg)

**Comment by cg3s** [comment]
稍等，一会给您转过去，另外能告知下退款原因？

**Comment by fionanico** [comment]
原因之一是我没有办法正确安装好

**Comment by fionanico** [comment]
然后第二个原因是找到了国外一个免费的嘻嘻

**Comment by cg3s** [comment]
哦，好的，了解了，如果免费的不好用，欢迎再次购买，另外不会安装的问题，我们可以远程支持。

**Comment by fionanico** [comment]
好的谢谢你

**Comment by cg3s** [comment]
![photo_2018-09-07_10-59-31](https://user-images.githubusercontent.com/28707826/45196090-2b37a500-b28d-11e8-9096-19ee94e59eb1.jpg)
已转，请查收。
