### ISSUE TITLE
youtube 搜索显示 我们的系统检测到您的计算机网络中存在异常流量。请稍后重新发送请求。

### ISSUE THREAD

**Issue by EricCenVFX** [cg3s/forum#65]
youtube 搜索显示 我们的系统检测到您的计算机网络中存在异常流量。请稍后重新发送请求。

**Comment by cg3s** [comment]
[请查看常见问题列表-第16条](https://github.com/cg3s/forum/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E5%88%97%E8%A1%A8#16-%E5%BD%93%E7%94%A8googleyoutube%E6%90%9C%E7%B4%A2%E6%97%B6%E6%8F%90%E7%A4%BA%E6%88%91%E4%BB%AC%E7%9A%84%E7%B3%BB%E7%BB%9F%E6%A3%80%E6%B5%8B%E5%88%B0%E6%82%A8%E7%9A%84%E8%AE%A1%E7%AE%97%E6%9C%BA%E7%BD%91%E7%BB%9C%E4%B8%AD%E5%AD%98%E5%9C%A8%E5%BC%82%E5%B8%B8%E6%B5%81%E9%87%8F%E8%AF%B7%E7%A8%8D%E5%90%8E%E9%87%8D%E6%96%B0%E5%8F%91%E9%80%81%E8%AF%B7%E6%B1%82%E5%A6%82%E4%BD%95%E9%81%BF%E5%85%8D%E8%BF%99%E7%A7%8D%E6%83%85%E5%86%B5)

**Comment by EricCenVFX** [comment]
好，谢谢！

**Comment by cg3s** [comment]
不客气
