### ISSUE TITLE
如何删除已经登录的设备终端

### ISSUE THREAD

**Issue by squaremxc** [cg3s/forum#76]
## 提交问题请按照格式填写

- 账号：

- 操作系统：[Windows|Mac|Linux|iOS|Android]

- [ ] 是否已更新节点列表：[是|否]

- [ ] 是否已查看最新系统公告：[是|否]

- [ ] 是否已查看常见问题列表：[是|否]

- [ ] 是否已搜索已解决问题列表：[是|否]

### 备注：
- [常见问题列表](https://github.com/cg3s/forum/wiki/)
- [已解决问题列表](https://github.com/cg3s/forum/issues?q=is%3Aissue+is%3Aclosed)
- 如想立即得到我们的回复，请在我们的工作时间内提交问题（工作日的10:00-17:00）
- 如需上传截图，对敏感信息马赛克后拖拽或拷贝图片到本编辑器中即可。

**本问答为公开页面，为保护我们的服务安全和您的个人隐私，如截图中含有以下敏感信息，请马赛克处理。**
- 本站网址
- 本站节点的任何信息

**Comment by cg3s** [comment]
修改节点连接密码，并重置链接（用户中心/软件下载与使用 右上角）即可，同时，完成以上两步请重新配置节点信息
