### ISSUE TITLE
按照教程设置了SSR出现1090端口出现问题怎么解决呀？

### ISSUE THREAD

**Issue by Starsyiyiyi** [cg3s/forum#79]
- 账号：asdxxx85@163.com

- 操作系统：路由器

- [ ] 是否已更新节点列表：是

- [ ] 是否已查看最新系统公告：是

- [ ] 是否已查看常见问题列表：是

- [ ] 是否已搜索已解决问题列表：是

### 问题描述：
按照SSR设置已经正确设置，开启SSR之后提示1090端口出现问题

Oct 28 21:34:44 dnsmasq[21929]: exiting on receipt of SIGTERM
Oct 28 21:34:44 dnsmasq[22082]: started, version 2.76 cachesize 1024
Oct 28 21:34:44 dnsmasq[22082]: compile time options: IPv6 GNU-getopt no-RTC no-DBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP no-conntrack ipset no-auth no-DNSSEC no-loop-detect no-inotify
Oct 28 21:34:44 dnsmasq-dhcp[22082]: DHCP, IP range 192.168.123.2 -- 192.168.123.244, lease time 1d
Oct 28 21:34:44 dnsmasq-dhcp[22082]: DHCP, sockets bound exclusively to interface br0
Oct 28 21:34:44 dnsmasq[22082]: using 6084 more nameservers
Oct 28 21:34:44 dnsmasq[22082]: read /etc/hosts - 3 addresses
Oct 28 21:34:44 dnsmasq[22082]: read /etc/storage/dnsmasq/hosts - 0 addresses
Oct 28 21:34:44 dnsmasq-dhcp[22082]: read /etc/dnsmasq/dhcp/dhcp-hosts.rc
Oct 28 21:34:44 dnsmasq[22082]: using 6087 more nameservers
Oct 28 21:34:59 【SS】: [2018-10-28 21:34:15]  SS 服务器 1090 检测到问题, 1
Oct 28 21:34:59 dnsmasq[22082]: exiting on receipt of SIGTERM
Oct 28 21:34:59 dnsmasq[22101]: started, version 2.76 cachesize 1024
Oct 28 21:34:59 dnsmasq[22101]: compile time options: IPv6 GNU-getopt no-RTC no-DBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP no-conntrack ipset no-auth no-DNSSEC no-loop-detect no-inotify
Oct 28 21:34:59 dnsmasq-dhcp[22101]: DHCP, IP range 192.168.123.2 -- 192.168.123.244, lease time 1d
Oct 28 21:34:59 dnsmasq-dhcp[22101]: DHCP, sockets bound exclusively to interface br0
Oct 28 21:34:59 dnsmasq[22101]: using 6084 more nameservers
Oct 28 21:34:59 dnsmasq[22101]: read /etc/hosts - 3 addresses
Oct 28 21:34:59 dnsmasq[22101]: read /etc/storage/dnsmasq/hosts - 0 addresses
Oct 28 21:34:59 dnsmasq-dhcp[22101]: read /etc/dnsmasq/dhcp/dhcp-hosts.rc
Oct 28 21:34:59 dnsmasq[22101]: using 6087 more nameservers
Oct 28 21:35:08 dnsmasq[22101]: nameserver 192.168.1.1 refused to do a recursive query
Oct 28 21:35:34 dnsmasq[22101]: exiting on receipt of SIGTERM
Oct 28 21:35:35 dnsmasq[22186]: started, version 2.76 cachesize 1024
Oct 28 21:35:35 dnsmasq[22186]: compile time options: IPv6 GNU-getopt no-RTC no-DBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP no-conntrack ipset no-auth no-DNSSEC no-loop-detect no-inotify
Oct 28 21:35:35 dnsmasq-dhcp[22186]: DHCP, IP range 192.168.123.2 -- 192.168.123.244, lease time 1d
Oct 28 21:35:35 dnsmasq-dhcp[22186]: DHCP, sockets bound exclusively to interface br0
Oct 28 21:35:35 dnsmasq[22186]: using 6084 more nameservers
Oct 28 21:35:35 dnsmasq[22186]: read /etc/hosts - 3 addresses
Oct 28 21:35:35 dnsmasq[22186]: read /etc/storage/dnsmasq/hosts - 0 addresses
Oct 28 21:35:35 dnsmasq-dhcp[22186]: read /etc/dnsmasq/dhcp/dhcp-hosts.rc
Oct 28 21:35:35 dnsmasq[22186]: using 6087 more nameservers
Oct 28 21:35:50 【SS】: [2018-10-28 21:35:08]  SS 服务器 1090 检测到问题, 2
Oct 28 21:35:50 dnsmasq[22186]: exiting on receipt of SIGTERM
Oct 28 21:35:50 dnsmasq[22227]: started, version 2.76 cachesize 1024
Oct 28 21:35:50 dnsmasq[22227]: compile time options: IPv6 GNU-getopt no-RTC no-DBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP no-conntrack ipset no-auth no-DNSSEC no-loop-detect no-inotify
Oct 28 21:35:50 dnsmasq-dhcp[22227]: DHCP, IP range 192.168.123.2 -- 192.168.123.244, lease time 1d
Oct 28 21:35:50 dnsmasq-dhcp[22227]: DHCP, sockets bound exclusively to interface br0
Oct 28 21:35:50 dnsmasq[22227]: using 6084 more nameservers
Oct 28 21:35:50 dnsmasq[22227]: read /etc/hosts - 3 addresses
Oct 28 21:35:50 dnsmasq[22227]: read /etc/storage/dnsmasq/hosts - 0 addresses
Oct 28 21:35:50 dnsmasq-dhcp[22227]: read /etc/dnsmasq/dhcp/dhcp-hosts.rc
Oct 28 21:35:50 dnsmasq[22227]: using 6087 more nameservers
Oct 28 21:35:59 dnsmasq[22227]: nameserver 192.168.1.1 refused to do a recursive query
Oct 28 21:36:25 dnsmasq[22227]: exiting on receipt of SIGTERM
Oct 28 21:36:25 dnsmasq[22296]: started, version 2.76 cachesize 1024
Oct 28 21:36:25 dnsmasq[22296]: compile time options: IPv6 GNU-getopt no-RTC no-DBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP no-conntrack ipset no-auth no-DNSSEC no-loop-detect no-inotify
Oct 28 21:36:25 dnsmasq-dhcp[22296]: DHCP, IP range 192.168.123.2 -- 192.168.123.244, lease time 1d
Oct 28 21:36:25 dnsmasq-dhcp[22296]: DHCP, sockets bound exclusively to interface br0
Oct 28 21:36:25 dnsmasq[22296]: using 6084 more nameservers
Oct 28 21:36:25 dnsmasq[22296]: read /etc/hosts - 3 addresses
Oct 28 21:36:25 dnsmasq[22296]: read /etc/storage/dnsmasq/hosts - 0 addresses
Oct 28 21:36:25 dnsmasq-dhcp[22296]: read /etc/dnsmasq/dhcp/dhcp-hosts.rc
Oct 28 21:36:25 dnsmasq[22296]: using 6087 more nameservers

**Comment by cg3s** [comment]
你的路由器确定支持SSR么,我看上面
`Oct 28 21:35:50 【SS】: [2018-10-28 21:35:08] SS 服务器 1090 检测到问题, 2`
这行显示的[ss], 我们的节点不支持老版本的ss哦

**Comment by Starsyiyiyi** [comment]
没事自己解决了，我去更新了新版的固件后就能正常使用了

**Comment by Starsyiyiyi** [comment]
想问一下用PS4联机的怎么设置是最好的
![qq 20181028215349](https://user-images.githubusercontent.com/35342150/47616759-07aa1180-dafc-11e8-9e47-9a64fdb3903f.png)

**Comment by Starsyiyiyi** [comment]
> 您的路由器固件确定支持SSR么,我看上面
> `Oct 28 21:35:50 【SS】: [2018-10-28 21:35:08] SS 服务器 1090 检测到问题, 2`
> 这行显示的[ss], 我们的节点不支持老版本的ss哦

有必要开启GFW吗？用于PS4的话

**Comment by cg3s** [comment]
gfw只是更新一下规则列表,ps4的服务器应该没有被墙吧,没有被墙就没什么区别.

**Comment by Starsyiyiyi** [comment]
> gfw只是更新一下规则列表,ps4的服务器应该没有被墙吧,没有被墙就没什么区别.

就是觉得不用代理的话PS4的服务器很慢，打开PSN都要半天

**Comment by cg3s** [comment]
你能让ps4走代理就行了,gfw保持更新又没什么影响
