### ISSUE TITLE
SSR无互联网连接

### ISSUE THREAD

**Issue by keep-slience** [cg3s/forum#80]
## 提交问题请按照格式填写

- 账号：645xxx036@qq.com

- 操作系统：Android
- [ ] 是否已更新节点列表：是

- [ ] 是否已查看最新系统公告：是

- [ ] 是否已查看常见问题列表：是

- [ ] 是否已搜索已解决问题列表：否

### 问题描述：
看到#67公告需要重新更新节点列表，已经卸载重新安装SSR的APK，导入节点列表后有一瞬间可以ping通谷歌，之后就无互联网连接了

### 备注：
- [常见问题列表](https://github.com/cg3s/forum/wiki/)
- [已解决问题列表](https://github.com/cg3s/forum/issues?q=is%3Aissue+is%3Aclosed)
- 如想立即得到我们的回复，请在我们的工作时间内提交问题（工作日的10:00-17:00）
- 如需上传截图，对敏感信息马赛克后拖拽或拷贝图片到本编辑器中即可。

**本问答为公开页面，为保护我们的服务安全和您的个人隐私，如截图中含有以下敏感信息，请马赛克处理。**
- 本站网址
- 本站节点的任何信息

**Comment by cg3s** [comment]
软件右上角的按钮点击后，能启动成功么？

**Comment by keep-slience** [comment]
可以成功，然后成功的那一瞬间点检测连接可以成功，之后就无网络链接了

**Comment by cg3s** [comment]
https://sunlogin.oray.com/zh_CN/download 你在手机上装下这个软件，我远程你看看呢

**Comment by keep-slience** [comment]
没用过这个远程，他说在控方登陆同一账号，需要我把向日葵账号提供给你吗

**Comment by cg3s** [comment]
恩，我以为电脑可以远程，手机上是要登录id密码，不过我登不上呢

**Comment by keep-slience** [comment]
向日葵账户 18811375755，密码 l645985036

**Comment by keep-slience** [comment]
我看到你连上了，现在是可以链接的，然后过个五分钟左右就无互联网链接了，估计那时候向日葵也看不到了

**Comment by keep-slience** [comment]
这次好像没问题了，不过经常性无互联网链接，关闭SSR后才能用正常通道上网，这个有什么好的方法解决吗

**Comment by cg3s** [comment]
目前没有其他用户反应这个情况，具体原因不远程我们也无法判断呢，你再找找是不是哪里设置有问题？

**Comment by cg3s** [comment]
远程我这边是黑屏的，不过即使连上一连ssr，估计远程就会中断，也会比较麻烦

**Comment by keep-slience** [comment]
用的是WIFI，节点所有的都会断

**Comment by cg3s** [comment]
4G网络呢

**Comment by keep-slience** [comment]
没有试过，我现在用流量估计也要等五到十分钟才有结果，因为这个无互联网连接是在一段时间后出现的

**Comment by keep-slience** [comment]
![screenshot_2018-11-01-10-55-16-198_in zhaoj shado](https://user-images.githubusercontent.com/42854161/47830147-9a310600-ddc5-11e8-9723-746a2469bbc1.png)

**Comment by cg3s** [comment]
https://github.com/shadowsocksrr/shadowsocksr-android/issues/89 你看看这个问答，情况是否类似

**Comment by keep-slience** [comment]
我的安卓是8.0系统，刚刚测试了一下4G情况，也是过了五到十分钟左右开始断线，但是流量情况在之后又能重新连接成功，WIFI没有测试断线之后的情况，估计区别不大。是节点的网络波动么？我自己的网络前几天测试了没有问题，波动很小，麻烦你那边看一下节点的波动情况

**Comment by cg3s** [comment]
安卓用户目前没有其他人反馈这个情况，我这边测试一下

**Comment by keep-slience** [comment]
好的，多谢

**Comment by cg3s** [comment]
你用订阅模式更新下节点呢，我这边测试正常，另外我们传了另外两个ssrr和ssd的客户端，如果ssr不行，你再试试另外两个。

**Comment by cg3s** [comment]
另外你在连上ssr之后，是否用了百度的浏览器去浏览网页？如果是这样你最好下载一个chrome浏览器去访问youtube测试，因为后台有关于百度的审计规则，使用百度的浏览器访问可能会出现网络阻断的情况。

**Comment by keep-slience** [comment]
好的，我再试试，电脑端没有问题，只是安卓端有问题，我这边是一部8.0安卓手机和两个安卓模拟器，均有上述我说的情况，我去试试SSRR

**Comment by keep-slience** [comment]
SSRR也出现上述问题，检测显示connection closed by peer，对所有节点测试均连接失败

**Comment by cg3s** [comment]
建议换个手机测试

**Comment by cg3s** [comment]
![image](https://user-images.githubusercontent.com/28707826/47849855-0b94a700-de0e-11e8-8eef-8ba6e00afb52.png)
这两个ip都是你在使用么

**Comment by keep-slience** [comment]
不是，我是192的

**Comment by keep-slience** [comment]
之前已经卸载了SSR，换了SSRR，好了一段时间后现在又出现了这个问题

**Comment by cg3s** [comment]
https://www.ipip.net/ip.html 你再这里查下你的ip是哪个

**Comment by cg3s** [comment]
感觉像是你的ip数超了,同时在线设备超了

**Comment by keep-slience** [comment]
42.56.134.78

**Comment by cg3s** [comment]
不是这个,这是我们服务器的ip,发你的isp服务商ip,不翻墙状态下的

**Comment by cg3s** [comment]
你要不重置一下订阅链接和节点连接密码,再试

**Comment by keep-slience** [comment]
这个是我关闭SSRR时候测试的，显示的物理地址也是我家的地址，我试试重置连接

**Comment by cg3s** [comment]
哦哦,我看错了, 那就是辽宁联通嘛,但你的在线记录里有广州和江苏的,麻烦你注意下账号不要分享,不然会封号

**Comment by keep-slience** [comment]
我用的两个模拟器，所以显示的是不同的地方，是因为这三个冲突导致无互联网连接吗

**Comment by cg3s** [comment]
商品里写了,最多不超过2个设备,超过肯定就不行了

**Comment by keep-slience** [comment]
已经都关了，我只开启我的手机的SSR，还是显示无互联网连接

**Comment by cg3s** [comment]
关了后等几分钟再试,在线ip的记录会有几分钟的延迟

**Comment by keep-slience** [comment]
删除手机里的缓存后，现在重新添加SSR订阅，订阅列表为空

**Comment by cg3s** [comment]
添加订阅后请点击确认并升级

**Comment by cg3s** [comment]
用户使用超出账户限制（不同ip的设备数量大于2）
