### ISSUE TITLE
关于360对于VPN的影响问题

### ISSUE THREAD

**Issue by MessiahC1987** [cg3s/forum#85]
- 账号：530xxx86@qq.com

- 操作系统：安卓&PC

- [x] 是否已更新节点列表：[是|

- [x] 是否已查看最新系统公告：[是|

- [x] 是否已查看常见问题列表：[是|

- [x] 是否已搜索已解决问题列表：[是|

### 问题描述：
我的VPN被封了4个小时，说检测到360，因为我手机是360产的，所以默认有安全卫士，而且无法卸载，请问，我后续把360对于CGSSS的权限全开，改成信任的话，是否不会出现这种状况，我很无奈发生这个情况

**Comment by cg3s** [comment]
改成信任只是系统防火墙对ssr的网络连接采取放行措施，不能屏蔽手机自带的360服务去连接360的服务器，建议换个手机，如果不行我们可以支持退款。

**Comment by MessiahC1987** [comment]
你好，可否暂时帮我退款，因为目前手机还没有到换的时候，VPN还是被监测出360全家桶，有点无奈，VPN确实很快，如果后面换手机了再来购买，谢谢！

**Comment by cg3s** [comment]
请打开微信,右上角+号,选择"收付款",再点击"二维码收款"
截屏后把图片发到这里即可.(电脑上把图片拽进来即可上传)

**Comment by MessiahC1987** [comment]
![_20181203230453](https://user-images.githubusercontent.com/45453697/49381864-de5e5000-f74f-11e8-9988-291085ffe06e.png)

**Comment by cg3s** [comment]
![image](https://user-images.githubusercontent.com/28707826/49418290-57938c80-f7bc-11e8-8c13-c70f322707a5.png)
已付
