### ISSUE TITLE
之前一直使用正常，昨天到期，续了费之后就不行了，更新了节点列表也没用

### ISSUE THREAD

**Issue by tomatoj23** [cg3s/forum#90]
## 提交问题请按照格式填写

- 账号：tom****j@foxmail.com

- 操作系统：Windows，Android

- [x] 是否已更新节点列表 ```(是: 在[]内填 x, 否: 留空) ```

- [x] 是否已查看最新系统公告

- [x] 是否已查看常见问题列表

- [x] 是否已搜索已解决问题列表

**本问答为公开页面，为保护我们的服务安全和您的个人隐私，如截图中含有以下敏感信息，请马赛克处理。**
- 本站网址
- 本站节点的任何信息

### 问题描述：

之前一直使用正常，昨天到期，续了费之后就不行了，更新了节点列表也没用,手机和电脑都不能用了

### 备注：
- [常见问题列表](https://github.com/cg3s/forum/wiki/)
- [已解决问题列表](https://github.com/cg3s/forum/issues?q=is%3Aissue+is%3Aclosed)
- 如想立即得到我们的回复，请在我们的工作时间内提交问题（工作日的10:00-17:00）
- 如需上传截图，对敏感信息马赛克后拖拽或拷贝图片到本编辑器中即可。

**Comment by cg3s** [comment]
您现在更新一下节点列表，然后连下试试

**Comment by tomatoj23** [comment]
> 您现在更新一下节点列表，然后连下试试

好的

**Comment by tomatoj23** [comment]
> 您的账户等级不对，然后流量被清零了，现在您的账户正常了，您现在更新一下节点列表，然后连下试试

再问一句，手机上的ssr和ssrr有什么区别呢

**Comment by cg3s** [comment]
ssrr主要添加了几个加密协议，目前对于我们平台来说没多大差别，随便用哪个都行

**Comment by tomatoj23** [comment]
> ssrr主要添加了几个加密协议，目前对于我们平台来说没多大差别，随便用哪个都行

好的
