### ISSUE TITLE
使用ipad按照公告删除旧的节点在更新后，新的节点却不见了？

### ISSUE THREAD

**Issue by fatiao123** [cg3s/forum#91]
## 提交问题请按照格式填写

- 账号：258954xxx@qq.com

- 操作系统： iOS

- [x] 是否已更新节点列表 ```(是: 在[]内填 x, 否: 留空) ```

- [x] 是否已查看最新系统公告

- [x] 是否已查看常见问题列表

- [x] 是否已搜索已解决问题列表

**本问答为公开页面，为保护我们的服务安全和您的个人隐私，如截图中含有以下敏感信息，请马赛克处理。**

### 问题描述：
使用ipad按照公告删除旧的节点在更新后，新的节点却不见了。第一行连接只显示新加坡   在全局路由也选择的是代理。在服务器订阅那里却没有了以前的各地的节点。

### 备注：
- [常见问题列表](https://github.com/cg3s/forum/wiki/)
- [已解决问题列表](https://github.com/cg3s/forum/issues?q=is%3Aissue+is%3Aclosed)
- 如想立即得到我们的回复，请在我们的工作时间内提交问题（工作日的10:00-17:00）
- 如需上传截图，对敏感信息马赛克后拖拽或拷贝图片到本编辑器中即可。

**Comment by cg3s** [comment]
你订阅地址是对的么，是否重置过订阅链接？

**Comment by fatiao123** [comment]
1 我是直接删除了全部节点。应该是在数据下删除的本地节点。
2 后来见刷新不出来，我又在设备下重置了。（Tunnel配置）（用户设置）
3因为我在尝试的时候设置乱了。 所以麻烦您了。。

**Comment by cg3s** [comment]
数据里删，你要重新添加一些服务器订阅才行

**Comment by fatiao123** [comment]
我在从新添加了 服务器订阅也是按照教程走的。但就是还是没有节点？

**Comment by cg3s** [comment]
不行你就删掉软件，重新下载重新配置吧，我不确定是不是你动了tunnel那个的原因还是你其他地方操作不对。

**Comment by fatiao123** [comment]
大哥 我错了 刚才看了配置竟然不是最新的URL 实在不好意思

**Comment by fatiao123** [comment]
一直复制的都是旧的

**Comment by cg3s** [comment]
订阅地址还能复制到旧的？你不是登录网站上去复制的哦，没事，一次生两次熟
