### ISSUE TITLE
关于新的售价方案

### ISSUE THREAD

**Issue by cg3s** [cg3s/forum#92]
欢迎您的宝贵意见，最后我们将根据大家的意见做出相应的调整，如无异议则按原计划进行。

**Comment by xtvjxk123456** [comment]
没异议，因为我已经续了一年了-v-

**Comment by cg3s** [comment]
@xtvjxk123456 谢谢支持

**Comment by qinfc317** [comment]
我已经推荐十几个人了，就想知道再买会不会有优惠🤣🤣🤣

**Comment by alvinxhc** [comment]
额~~我之前充了15，一直没用~能不能再冲1块把这钱用掉呢？

**Comment by cg3s** [comment]
当然可以

**Comment by alvinxhc** [comment]
> 当然可以

不过我看充值页面最低只能充16耶？我要怎么操作呢？

**Comment by cg3s** [comment]
> > 当然可以
> 
> 不过我看充值页面最低只能充16耶？我要怎么操作呢？

cgs非套餐里有1元的卡密

**Comment by alvinxhc** [comment]
> > > 当然可以
> > 
> > 
> > 不过我看充值页面最低只能充16耶？我要怎么操作呢？
> 
> cgs非套餐里有1元的卡密

原来如此~找到了~谢谢~
