### ISSUE TITLE
CG福利计划

### ISSUE THREAD

**Issue by cg3s** [cg3s/forum#93]
为回馈本站CG用户，我们计划长期但不定期的购买一些CG类相关资源作为套餐福利，具体细则如下：

1. 仅限付费用户
2. 资源包括与CG相关的APP, 教程, 电子书, 等等
3. 购买的商品需不绑定设备
4. 单个购买项价格需小于等于用户积分分值，且不超过1000元（人民币，可能会分阶段调整峰值）
5. 积分机制，以10-20倍积分计算，即充值100元，积1000分，或邀请获利10元，积20分，后期根据情况调整
6. 积分福利的兑换比率为100,即10000积分即可申请购买100元的CG资源
7. 积分不可转移到其他用户
8. 积分仅用于申请CG福利，不能作为购买本站服务使用
9. 如所购项为视频教程，则采用一机一码分发，仅支持windows

如您有需要购买的CG资源，可先在此留言，后面福利中心开发完成后，到福利中心申请福利即可，同时本问答也暂时作为问卷调查反馈之用，我们将根据大家的反馈调整本计划的详细规则。

注意：因为积分及福利体系正在开发中，目前暂时为手动统计，实际流程还需要到福利中心提交申请

为了制定更加合理的福利细则，以上可能会随时变更，以便提高开发效率。

**Comment by ypypjay** [comment]
希望能购买cgworkshop的一个名为FX for Games的教程，[https://cgsociety.org/workshops/fx-for-games#instructors](https://cgsociety.org/workshops/fx-for-games#instructors)

**Comment by cg3s** [comment]
@ypypjay 价格超出1000元，暂时不会考虑

**Comment by xtvjxk123456** [comment]
卧槽？还有这好事?

**Comment by cg3s** [comment]
@xtvjxk123456 可以，你的积分算下来够，这个购买后是能下到所有文件？

**Comment by xtvjxk123456** [comment]
应该能吧，你从他主页也能看到，有视频教程和源文件的

**Comment by ypypjay** [comment]
> @ypypjay 价格超出1000元，暂时不会考虑，可作为众筹计划备选（ps: 众筹不属于福利计划）

ok，众筹也不错

**Comment by cg3s** [comment]
@xtvjxk123456 ok, 预计会从下周开始购买

**Comment by cg3s** [comment]
@ypypjay 福利计划也支持多个人同时申请购买一个购买项，也算另外一种众筹了

**Comment by cg3s** [comment]
福利中心已初步开发完成，本贴关闭讨论
