### ISSUE TITLE
福利得需要申请才可以有？

### ISSUE THREAD

**Issue by xtvjxk123456** [cg3s/forum#97]
福利是需要申请才可以有的么？
我还以为是类似商店一样的形式，可以选择的。

**Comment by cg3s** [comment]
初期需要用户申请，后期我们才好沉淀很多商品供用户使用积分购买

**Comment by cg3s** [comment]
你可以提交一个申请项测试一下，价格就填你积分够的数字，看看这个功能是否比之前的问答反馈更合理些

**Comment by xtvjxk123456** [comment]
emmmm，我想了想，没找到30块的教程

**Comment by xtvjxk123456** [comment]
众筹功能（可能有bug）？,刚才我是先删了原先非众筹的申请，然后又开了一个众筹的，申请成功后显示有3个人参与了，我就是觉得有些快了点，请检查下是否有那么多人参与了

**Comment by cg3s** [comment]
> 众筹功能（可能有bug）？,刚才我是先删了原先非众筹的申请，然后又开了一个众筹的，申请成功后显示有3个人参与了，我就是觉得有些快了点，请检查下是否有那么多人参与了

他人参与众筹的功能还没好，我们默认设了个3的数字，一会会变成1

**Comment by cg3s** [comment]
现在众筹的功能基本好了，其他人也可以参与到你的申购项里了
