### ISSUE TITLE
人在国外（澳洲），住的宿舍成人网站（如：草榴）被blocked了

### ISSUE THREAD

**Issue by JackZhu426** [cg3s/forum#98]
应该如何用proxy绕过？请大神指点！~ 微信 cdyxx184

**Comment by cg3s** [comment]
全局模式+绕过局域网和非中国
![image](https://user-images.githubusercontent.com/28707826/52609547-a47c9900-2eb8-11e9-8f90-51c6d03323ac.png)
![image](https://user-images.githubusercontent.com/28707826/52609560-ab0b1080-2eb8-11e9-9768-2380ad5fa1a3.png)

**Comment by JackZhu426** [comment]
我之前试过了 还是不行，有什么办法吗还？

**Comment by cg3s** [comment]
用QQ远程？我远程你看看，加3181677150

**Comment by JackZhu426** [comment]
加不了 你加我 76562114

**Comment by cg3s** [comment]
初步确定电脑环境无法正常使用ssr代理，我们将部署国外vps测试windows环境。

**Comment by cg3s** [comment]
已解决，原因有两个：
1、用户自行将节点配置为了ss模式（本站早已不兼容ss）
2、用户所在学校可能屏蔽了非https的加密协议，导致B组节点无法使用，切换到A组后正常。
